### ISSUE TITLE
h2o.ls() produces java.lang.ArrayIndexOutOfBoundsException: 71

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#1056]
After SW was upgraded to 2.3.22 (and a matching h2o backend cluster version),
`h2o.ls()` started producing following exception on a freshly created session / freshly created 
h2o backend cluster

```
Fail to execute line 2: h2o.ls()
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/h2o.py", line 915, in ls
    return H2OFrame._expr(expr=ExprNode("ls")).as_data_frame(use_pandas=True)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/frame.py", line 1297, in as_data_frame
    return pandas.read_csv(StringIO(self.get_frame_data()), low_memory=False, skip_blank_lines=False)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/frame.py", line 1311, in get_frame_data
    return h2o.api("GET /3/DownloadDataset", data={"frame_id": self.frame_id, "hex_string": False})
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/frame.py", line 276, in frame_id
    return self._frame()._ex._cache._id
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/frame.py", line 504, in _frame
    self._ex._eager_frame()
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/expr.py", line 95, in _eager_frame
    self._eval_driver(True)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/expr.py", line 113, in _eval_driver
    res = ExprNode.rapids(exec_str)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/expr.py", line 241, in rapids
    return h2o.api("POST /99/Rapids", data={"ast": expr, "session_id": h2o.connection().session_id})
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/h2o.py", line 104, in api
    return h2oconn.request(endpoint, data=data, json=json, filename=filename, save_to=save_to)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/backend/connection.py", line 407, in request
    return self._process_response(resp, save_to)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/backend/connection.py", line 748, in _process_response
    raise H2OServerError("HTTP %d %s:\n%r" % (status_code, response.reason, data))
H2OServerError: HTTP 500 Server Error:
Server error java.lang.RuntimeException:
  Error: DistributedException from pc1udatahad30/10.20.33.144:55099: '71', caused by java.lang.ArrayIndexOutOfBoundsException: 71
  Request: None

```

SW (PySpark) connects to a h2o backend cluster.

**Comment by jakubhava** [comment]
We have a JIRA here https://0xdata.atlassian.net/browse/PUBDEV-6239
