### ISSUE TITLE
rsparkling connection issue using latest packages

### ISSUE THREAD

**Issue by javierluraschi** [h2oai/sparkling-water#1078]
I'm trying the following with the latest versions of `sparklyr` and `rsparkling` but hitting dependency check errors, looks related to https://github.com/h2oai/sparkling-water/issues/960:

```r
library(sparklyr)
library(rsparkling)
library(dplyr)
library(h2o)

sc <- spark_connect(master = "local", version = '2.3.2')
```

```
Spark version 2.3 detected. Will call latest Sparkling Water version 2.3.23
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (90150): Gateway in localhost:8880 did not respond.
    Path: /Users/javierluraschi/spark/spark-2.3.2-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.3.23','ai.h2o:sparkling-water-ml_2.11:2.3.23','ai.h2o:sparkling-water-repl_2.11:2.3.23','no.priv.garshol.duke:duke:1.2', '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 90150
    Log: /var/folders/ks/wm_bx4cn70s6h0r5vgqpsldm0000gn/T//RtmpFvkprS/file181ed73a9408d_spark.log


---- Output Log ----
	com.google.protobuf#protobuf-java-util;3.5.1 from central in [default]
	com.googlecode.matrix-toolkits-java#mtj;1.0.4 from central in [default]
	com.jamesmurty.utils#java-xmlbuilder;0.4 from central in [default]
	com.spatial4j#spatial4j;0.3 from central in [default]
	commons-codec#commons-codec;1.9 from central in [default]
	commons-io#commons-io;2.4 from local-m2-cache in [default]
	commons-lang#commons-lang;2.6 from local-m2-cache in [default]
	commons-logging#commons-logging;1.2 from local-m2-cache in [default]
	gov.nist.math#jama;1.0.3 from central in [default]
	io.grpc#grpc-context;1.9.0 from central in [default]
	io.opencensus#opencensus-api;0.11.1 from central in [default]
	io.opencensus#opencensus-contrib-http-util;0.11.1 from central in [default]
	javax.xml.bind#jaxb-api;2.3.0 from central in [default]
	joda-time#joda-time;2.9.9 from central in [default]
	log4j#log4j;1.2.17 from local-m2-cache in [default]
	net.java.dev.jets3t#jets3t;0.9.0 from central in [default]
	net.java.dev.jna#jna;4.0.0 from central in [default]
	net.sf.opencsv#opencsv;2.3 from local-m2-cache in [default]
	net.sourceforge.f2j#arpack_combined_all;0.1 from local-m2-cache in [default]
	no.priv.garshol.duke#duke;1.2 from central in [default]
	org.apache.commons#commons-math3;3.3 from central in [default]
	org.apache.httpcomponents#httpclient;4.3.6 from central in [default]
	org.apache.httpcomponents#httpcore;4.3.3 from central in [default]
	org.apache.lucene#lucene-analyzers-common;4.0.0 from central in [default]
	org.apache.lucene#lucene-core;4.0.0 from central in [default]
	org.apache.lucene#lucene-queries;4.0.0 from central in [default]
	org.apache.lucene#lucene-spatial;4.0.0 from central in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.11 from central in [default]
	org.eclipse.jetty#jetty-client;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-continuation;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-http;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-io;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-jndi;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-plus;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-security;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-server;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-servlet;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-servlets;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-util;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-webapp;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty#jetty-xml;8.1.21.v20160908 from central in [default]
	org.eclipse.jetty.orbit#javax.activation;1.1.0.v201105071233 from central in [default]
	org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v201005082020 from central in [default]
	org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 from central in [default]
	org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 from central in [default]
	org.javassist#javassist;3.23.1-GA from central in [default]
	org.joda#joda-convert;1.7 from central in [default]
	org.kohsuke#libpam4j;1.8 from central in [default]
	org.mapdb#mapdb;0.9.9 from central in [default]
	org.threeten#threetenbp;1.3.3 from central in [default]
	:: evicted modules:
	com.google.code.gson#gson;2.6.2 by [com.google.code.gson#gson;2.7] in [default]
	com.github.fommil.netlib#core;1.1 by [com.github.fommil.netlib#core;1.1.2] in [default]
	commons-codec#commons-codec;1.4 by [commons-codec#commons-codec;1.9] in [default]
	commons-logging#commons-logging;1.1.1 by [commons-logging#commons-logging;1.2] in [default]
	org.apache.httpcomponents#httpclient;4.1.2 by [org.apache.httpcomponents#httpclient;4.3.6] in [default]
	org.apache.httpcomponents#httpcore;4.1.2 by [org.apache.httpcomponents#httpcore;4.3.3] in [default]
	commons-logging#commons-logging;1.1.3 by [commons-logging#commons-logging;1.2] in [default]
	commons-codec#commons-codec;1.6 by [commons-codec#commons-codec;1.9] in [default]
	joda-time#joda-time;2.8.1 by [joda-time#joda-time;2.9.9] in [default]
	joda-time#joda-time;2.9.2 by [joda-time#joda-time;2.9.9] in [default]
	org.apache.httpcomponents#httpclient;4.0.1 by [org.apache.httpcomponents#httpclient;4.3.6] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |  129  |   0   |   0   |   11  ||  118  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar (2ms)

	==== local-m2-cache: tried

	  file:/Users/javierluraschi/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1-javadoc.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1303)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:53)
	at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:364)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

```r
sessionInfo()
```
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] h2o_3.22.1.3      dplyr_0.8.0.9002  rsparkling_0.2.18 sparklyr_0.9.4   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0.3      dbplyr_1.3.0.9000 compiler_3.5.1    pillar_1.3.1      later_0.7.5       bitops_1.0-6     
 [7] r2d3_0.2.3        base64enc_0.1-3   tools_3.5.1       digest_0.6.18     packrat_0.4.9-3   jsonlite_1.6     
[13] tibble_2.0.1      nlme_3.1-137      lattice_0.20-35   pkgconfig_2.0.2   rlang_0.3.1.9000  shiny_1.2.0      
[19] DBI_1.0.0.9001    rstudioapi_0.9.0  parallel_3.5.1    yaml_2.2.0        knitr_1.20        withr_2.1.2.9000 
[25] httr_1.4.0        askpass_1.1       rappdirs_0.3.1    generics_0.0.2    htmlwidgets_1.3   rprojroot_1.3-2  
[31] grid_3.5.1        tidyselect_0.2.5  glue_1.3.0        forge_0.1.9002    R6_2.4.0          purrr_0.3.0      
[37] tidyr_0.8.2       magrittr_1.5      backports_1.1.3   promises_1.0.1    htmltools_0.3.6   assertthat_0.2.0 
[43] mime_0.6          xtable_1.8-3      httpuv_1.4.5      config_0.3        openssl_1.2.1     RCurl_1.95-4.11  
[49] lazyeval_0.2.1    broom_0.5.1       crayon_1.3.4 
```

**Comment by navdeep-G** [comment]
Any ideas @jakubhava ?

**Comment by jakubhava** [comment]
@javierluraschi to avoid any confusion, can you please please try to clean your ivy cache first and let us know? Thanks

**Comment by javierluraschi** [comment]
@jakubhava Yes, I did clean my cache with `rm -rf ~/.ivy2/cache/`.

**Comment by jakubhava** [comment]
@javierluraschi I have just tried with latest rsparkling and was able to reproduce. I will work on a fix which will probably be in the next release of Sparkling Water and RSparkling. Can you please just create a JIRA at https://0xdata.atlassian.net and mention it here? Thank you for the bug report!

**Comment by jakubhava** [comment]
Please use this jira to track progress of this issue https://0xdata.atlassian.net/browse/SW-1152
