### ISSUE TITLE
pysparkling.ml.H2OGridSearch - hyperParameters not accepted

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#1207]
Trying to run simple code to test **pysparkling.ml.H2OGridSearch** inside PySpark ML pipeline and getting following error:

**_code:_**
```
from pysparkling.ml import H2OGridSearch, H2OXGBoost

grid_params = {'ntrees':[100, 150, 200]}
grid_search = H2OGridSearch(algo=H2OXGBoost(), hyperParameters=grid_params)
grid_search.fit(set_train) #set_train is spark dataframe
```

**_error:_**
```
Py4JJavaError: An error occurred while calling o2966.fit.
: java.lang.NoSuchFieldException: ntrees
	at java.lang.Class.getField(Class.java:1703)
	at org.apache.spark.ml.h2o.algos.H2OGridSearch.findField(H2OGridSearch.scala:177)
	at org.apache.spark.ml.h2o.algos.H2OGridSearch.processHyperParams(H2OGridSearch.scala:161)
	at org.apache.spark.ml.h2o.algos.H2OGridSearch.fit(H2OGridSearch.scala:73)
	at org.apache.spark.ml.h2o.algos.H2OGridSearch.fit(H2OGridSearch.scala:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
```

I've tried to tune various algorithm parameters (ntrees, eta, sampleRate..) but still getting same error. 
Same situation when I changed algo from XGBoost to GBM.

`Using PySparkling /2.4.11/ & H2O /3.24.0.3/ on YARN-cluster mode.`

**Comment by jakubhava** [comment]
@dataspekulant please try to use `_ntrees` as the name of the hyper parameter. At this moment we are using internal named of the arguments from H2O for hyper param names, but thanks, this is definitely a good signal that we should improve this.

**Comment by dataspekulant** [comment]
Thank you for the advice. It helped.
