### ISSUE TITLE
Cannot add primary key (or any column) to scoreContributions output

### ISSUE THREAD

**Issue by sergiocalde94** [h2oai/sparkling-water#1253]
Hi! I´m using score contributions in sparkling water and it works perfect except of I can´t add a primary key that I need for joining purpouses.

My code is very simple:

```
val gbmModelToExplain: GBMModel = ModelSerializationSupport
        .loadH2OModel[GBMModel](destinationURI)

val dataToExplainH2O: H2OFrame = hc
        .asH2OFrame(dataToExplainWithSNAMetrics)

val explanations: DataFrame = hc
        .asDataFrame(gbmModelToExplain
          .scoreContributions(
            dataToExplainH2O, Key.make()
          )
          .add(dataToExplainH2O('my_primary_key)))

```

This throw an error:

```
java.lang.ArrayIndexOutOfBoundsException: 59
        at org.apache.spark.h2o.backends.internal.InternalReadConverterCtx.returnOption(InternalReadConverterCtx.scala:46)
        at org.apache.spark.h2o.converters.ReadConverterCtx$$anonfun$org$apache$spark$h2o$converters$ReadConverterCtx$$OptionReadersMap$1$$anonfun$apply$1.apply(ReadConverterCtx.scala:120)
        at org.apache.spark.h2o.converters.ReadConverterCtx$$anonfun$org$apache$spark$h2o$converters$ReadConverterCtx$$OptionReadersMap$1$$anonfun$apply$1.apply(ReadConverterCtx.scala:120)
        at org.apache.spark.h2o.converters.ReadConverterCtx$$anonfun$columnValueProviders$2$$anonfun$1.apply(ReadConverterCtx.scala:69)
        at org.apache.spark.h2o.converters.ReadConverterCtx$$anonfun$columnValueProviders$2$$anonfun$1.apply(ReadConverterCtx.scala:69)
        at org.apache.spark.h2o.converters.H2ODataFrame$$anon$1$$anonfun$readOptionalData$1.apply(H2ODataFrame.scala:90)
        at org.apache.spark.h2o.converters.H2ODataFrame$$anon$1$$anonfun$readOptionalData$1.apply(H2ODataFrame.scala:90)

```

My dataframe has 60 colums (59 predicted variables and 1 primary key), if I execute without the add statement everything goes perfect but the problem is that I haven´t the primary key.

Any ideas?

**Comment by sergiocalde94** [comment]
I got the solution.

I leave the code here in case it can help someone.

```
val gbmModelToExplain: GBMModel = ModelSerializationSupport
        .loadH2OModel[GBMModel](destinationURI)

val dataToExplainH2O: H2OFrame = hc
        .asH2OFrame(dataToExplainWithSNAMetrics)

val explanationsFrame: H2OFrame = hc
        .asH2OFrame(gbmModelToExplain
          .scoreContributions(dataToExplainH2O, Key.make()))

val explanations: Frame = H2OFrameSupport.withLockAndUpdate(explanationsFrame) {
        _.add(dataToExplainH2O('telefono_contacto_bbdd))
      }

```

**Comment by sergiocalde94** [comment]
I got the solution.

I leave the code here in case it can help someone.

```
val gbmModelToExplain: GBMModel = ModelSerializationSupport
        .loadH2OModel[GBMModel](destinationURI)

val dataToExplainH2O: H2OFrame = hc
        .asH2OFrame(dataToExplainWithSNAMetrics)

val explanationsFrame: H2OFrame = hc
        .asH2OFrame(gbmModelToExplain
          .scoreContributions(dataToExplainH2O, Key.make()))

val explanations: Frame = H2OFrameSupport.withLockAndUpdate(explanationsFrame) {
        _.add(dataToExplainH2O('primary_key))
      }

```
