### ISSUE TITLE
java.lang.NullPointerException in hamOrSpamMultiAlgo

### ISSUE THREAD

**Issue by maziyarpanahi** [h2oai/sparkling-water#1311]
- Sparkling Water/PySparkling/RSparkling version
Spark 2.4.0-cdh6.2.0
ai.h2o:sparkling-water-package_2.11:2.4.13
- Hadoop Version & Distribution
Cloudera 6.2.0
- Execution mode `YARN-client`, `YARN-cluster`, standalone, local ..
YARN-client
- YARN logs in case of running on yarn. To collect such logs you may run `yarn logs -applicationId <application ID>` where the application ID is displayed when Sparkling Water is started
I don't see any error in my YARN logs.

- Are you using Windows/Linux/MAC?
Linux
- Spark & Sparkling Water configuration including the memory configuration
I just disabled spark.dynamicAllocation.enabled false

I am trying to test this example inside my Zeppelin which the specs I mentioned:
https://github.com/h2oai/sparkling-water/blob/master/examples/pipelines/hamOrSpamMultiAlgo.script.scala

Everything works all the way to `pipeline.fit(smsDataFrame)`. I get this error:

```bash
java.lang.NullPointerException
  at org.apache.spark.ml.h2o.models.H2OMOJOModel$.org$apache$spark$ml$h2o$models$H2OMOJOModel$$removeMetaField(H2OMOJOModel.scala:172)
  at org.apache.spark.ml.h2o.models.H2OMOJOModel$.getModelDetails(H2OMOJOModel.scala:188)
  at org.apache.spark.ml.h2o.models.H2OMOJOModel$.createFromMojo(H2OMOJOModel.scala:205)
  at org.apache.spark.ml.h2o.algos.H2OAlgorithm.fit(H2OAlgorithm.scala:69)
  at org.apache.spark.ml.h2o.algos.H2OAlgorithm.fit(H2OAlgorithm.scala:38)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
  at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
```
The interesting part is that I can see H2OFlow is still running the job and finishes successfully. I can even do predict without any problem. It just the `.fit()` part fails before H2O job finishes.

Has anyone ever experienced something similar that can help me narrow it down?

Since I have changed some parts of the code, I share my example:

```scala
import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate(spark)
import h2oContext._

val sparkSmsDF = spark.read
.option("header", false)
.option("delimiter", "\t")
.option("mode", "DROPMALFORMED")
.csv("/user/maziyar/input/smsData/smsData.txt") // this is on HDFS
.select($"_c0".as("label"), $"_c1".as("text"))

val tokenizer = new RegexTokenizer().
  setInputCol("text").
  setOutputCol("words").
  setMinTokenLength(3).
  setGaps(false).
  setPattern("[a-zA-Z]+")

// Remove ignored words
val stopWordsRemover = new StopWordsRemover().
  setInputCol(tokenizer.getOutputCol).
  setOutputCol("filtered").
  setStopWords(Array("the", "a", "", "in", "on", "at", "as", "not", "for")).
  setCaseSensitive(false)

// Hash the words
val hashingTF = new HashingTF().
  setNumFeatures(1 << 10).
  setInputCol(stopWordsRemover.getOutputCol).
  setOutputCol("wordToIndex")

// Create inverse document frequencies model
val idf = new IDF().
  setMinDocFreq(4).
  setInputCol(hashingTF.getOutputCol).
  setOutputCol("tf_idf")

// I removed the rest because H2OXGBoost and H2OGridSearch had some problems
val algo = "dl"

val algoStage = algo match {
//   case "gbm" =>
    // Create GBM model
    // new H2OGBM().
    //   setSplitRatio(0.8).
    //   setSeed(1).
    //   setFeaturesCols("tf_idf").
    //   setLabelCol("label")
  case "dl" =>
    // Create H2ODeepLearning model
    new H2ODeepLearning().
      setEpochs(10).
      setL1(0.001).
      setL2(0.0).
      setSeed(1).
      setHidden(Array[Int](200, 200)).
      setFeaturesCols("tf_idf").
      setLabelCol("label")
}

// Create the pipeline by defining all the stages
val pipeline = new Pipeline().
  setStages(Array(tokenizer, stopWordsRemover, hashingTF, idf, algoStage))

// fails here in Spark, but continues in H2OFlow 
val model = pipeline.fit(sparkSmsDF)

```

**Comment by jakubhava** [comment]
Thanks @maziyarpanahi for the report. We have been working on improving the parsing of the model details and my colleague is working on long-term improvements in the H2O package. 

For now I will create a fix on Sparkling Water side which will be available in the next release.

Thanks for the report!

**Comment by jakubhava** [comment]
Here's the JIRA to track the progress https://0xdata.atlassian.net/browse/SW-1390
