### ISSUE TITLE
Not able to initiate H2OContext on Windows 10, pysparkling

### ISSUE THREAD

**Issue by danielhanbitlee** [h2oai/sparkling-water#1383]
I'm trying to use pysparkling on my system and I'm getting a py4j.protocol.Py4JError.

System I'm using:

 - Windows 10
 - Python 3.6.1
 - Anaconda 4.4.0
 - pyspark 2.4.3
 - h2o
 - h2o-pysparkling-2.4

I followed instructions on [h2o website](https://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/10/doc/pysparkling.html#what-is-pysparkling) and downloaded and unpacked sparkling-water from [here](https://s3.amazonaws.com/h2o-release/sparkling-water/rel-2.4/13/index.html). I also set SPARK_HOME environment variable to pyspark package in my python virtual environment path. I then go to Sparkling Water project directory and run PySparkling shell using ```bin\pysparkling```. Then I enter the following code:

```python
from pysparkling import *
import h2o
hc = H2OContext.getOrCreate(spark)
```

And I get the following error:

```
19/07/27 18:15:18 WARN InternalH2OBackend: To avoid non-deterministic behavior of Spark broadcast-based joins,
we recommend to set `spark.sql.autoBroadcastJoinThreshold` property of SparkSession to -1.
E.g. spark.conf.set("spark.sql.autoBroadcastJoinThreshold", -1)
We also recommend to avoid using broadcast hints in your Spark SQL code.
19/07/27 18:15:18 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 0 (Infinitive) as we need to ensure we run on the nodes with H2O
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/windows_32/xgboost4j_gpu.dll
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_gpu.dll
19/07/27 18:15:18 WARN NativeLibrary: Failed to load library from both native path and jar!
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/windows_32/xgboost4j_omp.dll
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_omp.dll
19/07/27 18:15:18 WARN NativeLibrary: Failed to load library from both native path and jar!
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/windows_32/xgboost4j_minimal.dll
19/07/27 18:15:18 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_minimal.dll
19/07/27 18:15:18 WARN NativeLibrary: Failed to load library from both native path and jar!
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "C:\Documents\python-virtual-environments\env_sparkling\Lib\site-packages\pyspark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1152, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\python-virtual-environments\env_sparkling\Lib\site-packages\pyspark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "C:\Documents\python-virtual-environments\env_sparkling\Lib\site-packages\pyspark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\AppData\Local\Temp\spark\work\spark-73591629-3b87-438c-b5da-06016978b0a1\userFiles-89ed1c65-8515-4511-b986-6328a42f692d\h2o_pysparkling_2.4-2.4.13.zip\pysparkling\context.py", line 161, in getOrCreate
  File "C:\Documents\python-virtual-environments\env_sparkling\Lib\site-packages\pyspark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1257, in __call__
  File "C:\Documents\python-virtual-environments\env_sparkling\lib\site-packages\pyspark\sql\utils.py", line 63, in deco
    return f(*a, **kw)
  File "C:\Documents\python-virtual-environments\env_sparkling\Lib\site-packages\pyspark\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py", line 336, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate

```

Any suggestions on how to resolve this?

**Comment by jakubhava** [comment]
@danielhanbitlee is this intermittent issue or demetermistic? Is your PySpark application starting fine without Sparkling Water?

**Comment by jakubhava** [comment]
@danielhanbitlee closing this issue as there is no input. Feel free to re-open if you would like to continue verifying this.
