### ISSUE TITLE
Connecting to H2O External Cluster from Jupyter/Spark Standalone failing

### ISSUE THREAD

**Issue by ramkrishnan8994** [h2oai/sparkling-water#1453]
I'm using "h2odriver-sw2.4.3-extended.jar" to create an External Standalone H2O Cluster. 
From jupyter, I'm trying to connect to the Cluster. Jupyter runs on Spark Standalone Cluster.
@jakubhava 
```
from pysparkling import *
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("SparklingWaterExternal").getOrCreate()
conf = H2OConf(spark).set_external_cluster_mode().use_manual_cluster_start().set_h2o_cluster("10.xxx.xx.x", 54321).set_cloud_name("h2o").set_cluster_size(1).set_client_network_mask("10.xx.x.x/xx")
print(conf)
hc = H2OContext.getOrCreate(spark, conf)
print(hc)
```

**The whole setup is in a Kubernetes environment with Spark standalone**. The application NEVER once got connected to the external H2O cluster.

These are the issues we've faced:

**H2O Logs say that a client got accepted, but Spark fails to initalize the context.**
` **H2o Logs**: #P-Accept INFO: Client reconnected with a new timestamp=-1375, old client: /10.xx.x.xx:54321(timestamp=-24176, watchdog=false, cloud_name_hash=xxxxxx)`
```
**Spark Logs** - An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: Cloud size 0 under 2
	at water.H2O.waitForCloudSize(H2O.java:1819)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:203)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:128)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:396)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

**H2O crashes as soon as there's a client connection made**
`Error: #P-Accept FATAL: missing eom sentinel when opening new tcp channel`

**Also, I get this random error**
`AttributeError: 'H2OConf' object has no attribute 'set_cluster_size'`

What are the reasons behind these errors. It's becoming a pain to set the cluster up.

Internal mode works for us, but as soon as there is one or more applications submitted, the second application fails with JVM error.

**Comment by jakubhava** [comment]
Please try on the latest Sparkling Water for your environment and let us know, thanks

**Comment by ramkrishnan8994** [comment]
@jakubhava - Why

**Comment by ramkrishnan8994** [comment]
@jakubhava - What is different in the new version. Why and how would it solve the issues?

**Comment by jakubhava** [comment]
The version you are trying is 12 releases old, since then, several bug fixes has been done on all fronts. I want to first try on the latest release before digging deeper. Thanks for respecting that

**Comment by ramkrishnan8994** [comment]
The latest file downloaded from - https://s3.amazonaws.com/h2o-release/sparkling-water/spark-2.4/3.26.2-2.4/sparkling-water-3.26.2-2.4.zip, throws the following error when I run :

```
bin/get-extended-h2o.sh standalone

File not found: https://h2o-release.s3.amazonaws.com/sparkling-water/rel-3.26/2-2/extended/h2odriver-3.26.0.2-extended.jar
```

**Comment by jakubhava** [comment]
You hit a bug, will be fixed asap https://github.com/h2oai/sparkling-water/pull/1454

In the meanwhile, please download this extended jar from https://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.26.2-2.4/extended/h2odriver-3.26.0.2-extended.jar

**Comment by smschauhan** [comment]
@jakubhava, it's great to see how far H2o has evolved from the initial days interacting with Satish. Your help in getting these issues resolved is appreciated.

**Comment by ramkrishnan8994** [comment]
@jakubhava - When will this get resolved?
I'm still getting a 404 - 
`File not found: https://h2o-release.s3.amazonaws.com/sparkling-water/rel-3.26/2-2/extended/h2odriver-3.26.0.2-extended.jar`

**Comment by jakubhava** [comment]
For now, pls download from https://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.26.2-2.4/extended/h2odriver-3.26.0.2-extended.jar the script will be fixed in the next relase

**Comment by ramkrishnan8994** [comment]
@jakubhava - There still seems to be an issue. This is how the whole setup is.
I've setup an External Cluster hosted on K8s environment and it is up. I can see the Cluster UI as well.
From jupyter, I'm trying to connect to the external cluster : 
```
from pysparkling import *
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("SparklingWaterExternal").getOrCreate()
conf = H2OConf(spark).set_external_cluster_mode().use_manual_cluster_start().set_h2o_cluster("10.xxx.xx.x", 54321).set_cloud_name("h2o").set_cluster_size(1).set_client_network_mask("10.xx.x.x/xx")
print(conf)
hc = H2OContext.getOrCreate(spark, conf)
print(hc)
```
The External cluster logs show the following - 
**#P-Accept INFO: New (possible) client found, timestamp=-19590**

But, in the end the following error is thrown - 
```
Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: Cloud size 0 under 2
	at water.H2O.waitForCloudSize(H2O.java:1819)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:203)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:128)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:396)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ramkrishnan8994** [comment]
@jakubhava - Can you please tell my why exactly does this error pop up - 
```
Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: Cloud size x under y
```
We've seen this error come up in multiple places. Even while using Internal Cluster.

**Comment by jakubhava** [comment]
This means that the h2o client could not discover the rest of the worker nodes. Could you please send us complete YARN logs of the both spark application and external h2o cluster? Ideally in the minimal scenario and debug logs enabled. Thank you for helping with this!

**Comment by ramkrishnan8994** [comment]
@jakubhava - The H2O Cluster we've setup is on a Kubernetes environment. It's one single instance for now which has resources allocated to it. 
This is a statefulset in K8s. The command to start the instance we've used is - 
`java -jar h2odriver-3.26.0.2-extended.jar -name g101-h2o-ds -ip $(MY_POD_IP)`
Ideally, if we scale the statefulset to more pods, they should associate themselves with the H2O cluster. But this does not happen.

We also are trying to connect to it from a jupyter instance, which runs a spark standalone cluster within it.

**Comment by ramkrishnan8994** [comment]
@jakubhava - 
Is there an issue setting up a H2O Cluster in Kubernetes -
https://stackoverflow.com/questions/43109777/h2o-in-kubernetes/57622143#57622143

**Comment by ramkrishnan8994** [comment]
> This means that the h2o client could not discover the rest of the worker nodes. Could you please send us complete YARN logs of the both spark application and external h2o cluster? Ideally in the minimal scenario and debug logs enabled. Thank you for helping with this!

@jakubhava - 
H2O does not follow a Master-Slave architecture from what I see. So why is it looking for "worker nodes" ?
If I have a H2OCluster that has one node with say 3 cores and 20GB RAM, isnt that sufficient to connect to from outside? Do I need to have a multi node cluster?

**Comment by ramkrishnan8994** [comment]
```
    h2ocontext = H2OContext.getOrCreate(spark)
  File "/usr/lib/python2.7/site-packages/ai/h2o/sparkling/H2OContext.py", line 180, in getOrCreate
    jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: Cloud size 1 under 2
	at water.H2O.waitForCloudSize(H2O.java:1819)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OCluster(InternalH2OBackend.scala:102)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:74)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:128)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:396)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

I'm getting this error even on an Internal Backend. Can you please explain how that happens?

**Comment by jakubhava** [comment]
Sparkling Water 3.28.0.3 is released which fixes several clouding issues:

    Spark 2.4: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.3-1-2.4/index.html
    Spark 2.3: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.3/3.28.0.3-1-2.3/index.html
    Spark 2.2: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.2/3.28.0.3-1-2.2/index.html
    Spark 2.1: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.1/3.28.0.3-1-2.1/index.html

If you bump into any new or existing ssues, please create new or feel free to reopen this issue.
