### ISSUE TITLE
pysparkling deploy

### ISSUE THREAD

**Issue by haiyuni** [h2oai/sparkling-water#1535]
File "/mnt/yarn/usercache/hadoop/appcache/application_1568798387424_0005/container_1568798387424_0005_01_000001/PY3/ml_h2o/lib/python3.6/site-packages/ai/h2o/sparkling/H2OContext.py", line 180, in getOrCreate
    jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1568798387424_0005/container_1568798387424_0005_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/mnt/yarn/usercache/hadoop/appcache/application_1568798387424_0005/container_1568798387424_0005_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt/yarn/usercache/hadoop/appcache/application_1568798387424_0005/container_1568798387424_0005_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: Cloud size 6 under 7
	at water.H2O.waitForCloudSize(H2O.java:1819)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OCluster(InternalH2OBackend.scala:102)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:74)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:128)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:400)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

==============================================
user pysparkling-3.26.5-2.3  aws emr  c5.4xlarge 
submit code:
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
--archives s3://spark-ml-train-new/xiaomi_dsp/code/ml_h2o.zip#PY3 \
--conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=./PY3/ml_h2o/bin/python3 \
--conf spark.executorEnv.PYSPARK_PYTHON=./PY3/ml_h2o/bin/python3 \
--conf spark.ext.h2o.fail.on.unsupported.spark.param=false \
--conf spark.dynamicAllocation.enabled=false \

**Comment by jakubhava** [comment]
I think this might be related to https://0xdata.atlassian.net/browse/SW-1559 which we are fixing in release this week. To be sure, please provide us with a complete YARN logs
