### ISSUE TITLE
Sparkling Water on CDH 5.8 Sandbox Spark 1.6

### ISSUE THREAD

**Issue by myworld0630** [h2oai/sparkling-water#157]
I run sparkling 1.6.8 on spark 1.6, and i got the following error.

```
Sparkling Water Context:
 * H2O name: sparkling-water-cloudera_-1596704912
 * cluster size: 1
 * list of used nodes:
  (executorId, host, port)
  ------------------------
  (driver,localhost,54321)
  ------------------------

  Open H2O Flow in browser: http://127.0.0.1:54321 (CMD + click in Mac OSX)
    
Exception in thread "main" DistributedException from localhost/127.0.0.1:54321, caused by water.parser.ParseDataset$H2OParseException: Cannot determine file type. for hdfs://127.0.0.1/user/cloudera/allyears2k_headers.csv.gz
	at water.MRTask.getResult(MRTask.java:477)
	at water.MRTask.getResult(MRTask.java:485)
	at water.MRTask.doAll(MRTask.java:401)
	at water.parser.ParseSetup.guessSetup(ParseSetup.java:263)
	at water.parser.ParseSetup.guessSetup(ParseSetup.java:246)
	at water.parser.ParseDataset.parse(ParseDataset.java:38)
	at water.parser.ParseDataset.parse(ParseDataset.java:32)
	at water.util.FrameUtils.parseFrame(FrameUtils.java:58)
	at water.util.FrameUtils.parseFrame(FrameUtils.java:47)
	at water.fvec.H2OFrame.<init>(H2OFrame.scala:66)
	at H2ODeepLearning$.main(H2ODeepLearning.scala:36)
	at H2ODeepLearning.main(H2ODeepLearning.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: water.parser.ParseDataset$H2OParseException: Cannot determine file type. for hdfs://127.0.0.1/user/cloudera/allyears2k_headers.csv.gz
	at water.parser.ParseSetup.guessSetup(ParseSetup.java:541)
	at water.parser.ParseSetup.guessSetup(ParseSetup.java:533)
	at water.parser.ParseSetup$GuessSetupTsk.map(ParseSetup.java:350)
	at water.MRTask.compute2(MRTask.java:595)
	at water.H2O$H2OCountedCompleter.compute1(H2O.java:1201)
	at water.parser.ParseSetup$GuessSetupTsk$Icer.compute1(ParseSetup$GuessSetupTsk$Icer.java)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1197)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

Because there is only one node in the Sandbox, so I referenced previous issues and set spark configuration as following command:

```
spark-submit --master local[*] --conf spark.dynamicAllocation.enabled=false --conf spark.ext.h2o.repl.enabled=false --conf spark.ext.h2o.backend.cluster.mode=internal --class H2ODeepLearning SparkApp-assembly-1.0.jar

```

and the exception occur when call H2OFrame function 
```
val conf = configure("Sparkling Water: Deep Learning on Airlines data")
    val sc = new SparkContext(conf)
    //addFiles(sc, absPath("allyears2k_headers.csv.gz"))

    implicit val sqlContext = SQLContext.getOrCreate(sc)
    import sqlContext.implicits._ // import implicit conversions

    // Run H2O cluster inside Spark cluster
    val h2oContext = H2OContext.getOrCreate(sc)
    import h2oContext._
    import h2oContext.implicits._

    // Load H2O from CSV file (i.e., access directly H2O cloud)
    // Use super-fast advanced H2O CSV parser !!!
    // val airlinesData = new H2OFrame(new File(SparkFiles.get("allyears2k_headers.csv.gz")))
    val airlinesData = new H2OFrame(new java.net.URI("hdfs://127.0.0.1/user/cloudera/allyears2k_headers.csv.gz"))
```

and my build.sbt
```
name := "SparkApp"

version := "1.0"

scalaVersion := "2.10.5"

libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.6.0" % "provided"

libraryDependencies += "org.apache.spark" % "spark-sql_2.10" % "1.6.0" % "provided"

libraryDependencies += "org.apache.spark" % "spark-mllib_2.10" % "1.6.0" % "provided"

libraryDependencies += "org.apache.spark" % "spark-streaming_2.10" % "1.6.0" % "provided"

libraryDependencies += "org.apache.spark" % "spark-streaming-kafka_2.10" % "1.6.0" % "provided"

libraryDependencies += "javax.xml.bind" % "jsr173_api" % "1.0" % "provided"

libraryDependencies += "ai.h2o" % "sparkling-water-core_2.10" % "1.6.8"

libraryDependencies += "ai.h2o" % "sparkling-water-examples_2.10" % "1.6.8"

resolvers += "Akka Repository" at "http://repo.akka.io/releases/"

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```

**Comment by mdymczyk** [comment]
@myworld0630 this is most probably because you're not including all required (h2o) libraries in your `build.sbt`. We have a sample droplet with a Gradle build file which lists all the required libraries, check it out to see what has to go into the fat jar https://github.com/h2oai/h2o-droplets/blob/master/sparkling-water-droplet/build.gradle#L152
