### ISSUE TITLE
I have this problem after running the crime example using sparkling water 1.6.2 with python   

### ISSUE THREAD

**Issue by MiraArikat** [h2oai/sparkling-water#158]
File "/home/cloudera/crime.py", line 166, in <module>     df_weather = h2oContext.as_spark_frame(f_weather)   File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 157, in as_spark_frame   File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 33, in get_java_h2o_frame   File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__   File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco   File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value py4j.protocol.Py4JJavaError: An error occurred while calling o47.asH2OFrame. : java.lang.ArrayIndexOutOfBoundsException: 65535 	at water.DKV.get(DKV.java:202) 	at water.DKV.get(DKV.java:175) 	at water.fvec.H2OFrame.<init>(H2OFrame.scala:37) 	at water.fvec.H2OFrame.<init>(H2OFrame.scala:45) 	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:91) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:606) 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) 	at py4j.Gateway.invoke(Gateway.java:259) 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133) 	at py4j.commands.CallCommand.execute(CallCommand.java:79) 	at py4j.GatewayConnection.run(GatewayConnection.java:209) 	at java.lang.Thread.run(Thread.java:745)

**Comment by mdymczyk** [comment]
@MiraArikat 1.6.2 is pretty old, please try with 1.6.8. If the problem persists please open a new issue, next time please provide us with your environment (you're running on Cloudera?), how you're running the example etc.

**Comment by mmalohlava** [comment]
FYI: h2o is not running for some reason. More logs would be helpful.

**Comment by MiraArikat** [comment]
I updated the version and end with the following error 
 File "/home/cloudera/crime.py", line 92, in <module>
    h2oContext = H2OContext.getOrCreate(sc)
  File "build/bdist.linux-x86_64/egg/pysparkling/context.py", line 128, in getOrCreate
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o36.invoke.
: java.lang.AbstractMethodError

**Comment by MiraArikat** [comment]
Im working in cloudera 5.8

**Comment by mdymczyk** [comment]
@MiraArikat I think this will be a duplicate of #127 @jakubhava is looking into it
