### ISSUE TITLE
Details: ERRR on field: XGBoost: XGBoost is not available on all nodes

### ISSUE THREAD

**Issue by uzair4520** [h2oai/sparkling-water#1593]
I am trying to use H2O XGBoost model with my pyspark pipeline but i am getting below mentioned exception. I have pip installed following libs for using H2O model with pyspark.

Libs:
 h2o_pysparkling_2.4
h2o
sparkling

Exception:

water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for XGBoost model: XGBoost_model_1572937136323_1.  Details: ERRR on field: XGBoost: XGBoost is not available on all nodes!

	at water.exceptions.H2OModelBuilderIllegalArgumentException.makeFromBuilder(H2OModelBuilderIllegalArgumentException.java:19)
	at hex.tree.xgboost.XGBoost.init(XGBoost.java:119)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.computeImpl(XGBoost.java:234)
	at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:222)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1417)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

Any help will be highly appreciated

**Comment by jakubhava** [comment]
@honzasterba do you think that is something on our side? H2O should bundle XGboost, shouldn't it?

**Comment by honzasterba** [comment]
Yes, XGBoost is bundled with H2O. This message means that H2O was unable to load the XGBoost native library. The usualy cause for this is missing dynamically linked dependencies, most frequently libgomp.
