### ISSUE TITLE
h2o cluster created, but H2O context hasn't been started successfully

### ISSUE THREAD

**Issue by ananbas** [h2oai/sparkling-water#1610]
Cluster: CDH 5.14
execute sparkling using:
```
spark2-shell \ 
  --packages ai.h2o:sparkling-water-package_2.11:3.26.10-2.4  \
  --conf spark.dynamicAllocation.enabled=false
```

Output:
```
scala> val h2oContext = H2OContext.getOrCreate(spark)
java.lang.ArrayIndexOutOfBoundsException: 10
	at water.UDPRebooted.checkForSuicide(UDPRebooted.java:58)
	at water.TCPReceiverThread.basic_packet_handling(TCPReceiverThread.java:292)
	at water.TCPReceiverThread$UDP_TCP_ReaderThread.run(TCPReceiverThread.java:249)
onExCompletion for water.FJPacket@7e1a57da
java.lang.ArrayIndexOutOfBoundsException: 10
	at water.AutoBuffer.getEnum(AutoBuffer.java:1269)
	at water.UDPClientEvent$ClientEvent$Icer.read9(UDPClientEvent$ClientEvent$Icer.java)
	at water.UDPClientEvent$ClientEvent$Icer.read(UDPClientEvent$ClientEvent$Icer.java)
	at water.Iced.read(Iced.java:69)
	at water.UDPClientEvent.call(UDPClientEvent.java:18)
	at water.FJPacket.compute2(FJPacket.java:29)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1417)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:347)
  at scala.None$.get(Option.scala:345)
  at org.apache.spark.h2o.SparkSpecificUtils$.addSparklingWaterTab(SparkSpecificUtils.scala:43)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:139)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:400)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:428)
  ... 51 elided

scala> import h2oContext._
<console>:26: error: not found: value h2oContext
       import h2oContext._
              ^

scala> val h2oContext = H2OContext.getOrCreate(spark)
java.lang.IllegalArgumentException:
H2O context hasn't been started successfully in the previous attempt and H2O client with previous configuration is already running.
Because of the current H2O limitation that it can't be restarted within a running JVM,
please restart your job or spark session and create new H2O context with new configuration.")
```

Log attached.
[h2o_10.30.225.202_54321-3-info.log](https://github.com/h2oai/sparkling-water/files/3832512/h2o_10.30.225.202_54321-3-info.log)

**Comment by ananbas** [comment]
open new : https://github.com/h2oai/sparkling-water/issues/1763
