### ISSUE TITLE
Convert Spark Dataframe to H2o Dataframee

### ISSUE THREAD

**Issue by hemanshupaliwa7** [h2oai/sparkling-water#1686]
Hello @jakubhava and Team... Hope you are doing good!!

I bring another issue of the same topic Spark DF to H2O Df in scala

I am following this notebook https://docs.databricks.com/_static/notebooks/h2o-sparkling-water-scala.html
And i get this error when I am converting spark dataframe to h2o

`[error] (run-main-0) java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
	at jsr166y.CountedCompleter.__tryComplete(CountedCompleter.java:427)
	at jsr166y.CountedCompleter.tryComplete(CountedCompleter.java:383)
	at water.Atomic.compute2(Atomic.java:78)
	at water.Atomic.fork(Atomic.java:39)
	at water.Atomic.invoke(Atomic.java:31)
	at water.Lockable.write_lock(Lockable.java:61)
	at water.Lockable.delete_and_lock(Lockable.java:70)
	at water.Lockable.delete_and_lock(Lockable.java:67)
	at water.fvec.Frame.preparePartialFrame(Frame.java:1044)
	at water.fvec.FrameUtils$class.preparePartialFrame(FrameUtils.scala:30)
	at water.fvec.FrameUtils$.preparePartialFrame(FrameUtils.scala:72)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.initFrame(InternalWriteConverterCtx.scala:43)
	at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.convert(WriteConverterCtxUtils.scala:85)
	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:81)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:89)
	at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:64)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:212)
	at analyticsvidya.loanprediction3.H2OMain$.delayedEndpoint$com$vodafone$aquaduct$core$analyticsvidya$loanprediction3$H2OMain$1(H2OMain.scala:34)
	at analyticsvidya.loanprediction3.H2OMain$delayedInit$body.apply(H2OMain.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at analyticsvidya.loanprediction3.H2OMain$.main(H2OMain.scala:7)
	at analyticsvidya.loanprediction3.H2OMain.main(H2OMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppress`

**Comment by jakubhava** [comment]
@hemanshupaliwa7 can you please share information about your environment and versions?  Without that it's hard to reason about possible issues

**Comment by hemanshupaliwa7** [comment]
Hello @jakubhava...

I am working with sbt(0.13.15) with scala (2.11.1)

MY build.sbt file looks like this for spark and sparkling water

`val sparkVersion = "2.4.0"
val sparklingWaterVersion = "3.26.11-2.4"

libraryDependencies ++= Seq(
  //Spark Libreries
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" %% "spark-streaming" % sparkVersion,
  "org.apache.spark" %% "spark-streaming-kafka-0-10" % sparkVersion,
  "org.apache.spark" %% "spark-sql-kafka-0-10" % sparkVersion,
  "org.apache.spark" %% "spark-sql" % sparkVersion,
  "org.apache.spark" %% "spark-mllib" % sparkVersion,
  "org.apache.spark" %% "spark-hive" % sparkVersion,
  "org.apache.spark" %% "spark-repl" % sparkVersion,
  //Sparkling Water
  "ai.h2o" %% "sparkling-water-core" % sparklingWaterVersion,
  "ai.h2o" %% "sparkling-water-utils" % sparklingWaterVersion,
  "ai.h2o" %% "sparkling-water-repl" % sparklingWaterVersion,
  "ai.h2o" %% "sparkling-water-ml" % sparklingWaterVersion,
  "ai.h2o" %% "sparkling-water-package" % sparklingWaterVersion,
  "ai.h2o" %% "sparkling-water-scoring" % sparklingWaterVersion,
  "org.codehaus.jsr166-mirror" % "jsr166y" % "1.7.0"
  )`

**Comment by jakubhava** [comment]
Can you just define  `"ai.h2o" %% "sparkling-water-package" % sparklingWaterVersion` this dependency? The `sparkling-water-package` contains all other required dependencies needed for Sparkling Water to run, including some shadowed libraries.

I would firstly try:

```
val sparkVersion = "2.4.0"
val sparklingWaterVersion = "3.26.11-2.4"

libraryDependencies ++= Seq(
//Spark Libreries
"org.apache.spark" %% "spark-core" % sparkVersion,
"org.apache.spark" %% "spark-streaming" % sparkVersion,
"org.apache.spark" %% "spark-streaming-kafka-0-10" % sparkVersion,
"org.apache.spark" %% "spark-sql-kafka-0-10" % sparkVersion,
"org.apache.spark" %% "spark-sql" % sparkVersion,
"org.apache.spark" %% "spark-mllib" % sparkVersion,
"org.apache.spark" %% "spark-hive" % sparkVersion,
"org.apache.spark" %% "spark-repl" % sparkVersion,
//Sparkling Water
"ai.h2o" %% "sparkling-water-package" % sparklingWaterVersion,
"org.codehaus.jsr166-mirror" % "jsr166y" % "1.7.0"
)
```
And would go from there

**Comment by hemanshupaliwa7** [comment]
Okay Let me Try this out

**Comment by hemanshupaliwa7** [comment]
Got the same error :(

`19/12/10 19:18:31 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 0 (Infinitive) as we need to ensure we run on the nodes with H2O
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/windows_64/xgboost4j_gpu.dll
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_gpu.dll
19/12/10 19:18:31 WARN NativeLibrary: Failed to load library from both native path and jar!
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/windows_64/xgboost4j_omp.dll
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_omp.dll
19/12/10 19:18:31 WARN NativeLibrary: Failed to load library from both native path and jar!
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/windows_64/xgboost4j_minimal.dll
19/12/10 19:18:31 WARN NativeLibrary: Cannot load library from path lib/xgboost4j_minimal.dll
19/12/10 19:18:31 WARN NativeLibrary: Failed to load library from both native path and jar!
[error] (run-main-0) java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
	at jsr166y.CountedCompleter.__tryComplete(CountedCompleter.java:427)
	at jsr166y.CountedCompleter.tryComplete(CountedCompleter.java:383)
	at water.Atomic.compute2(Atomic.java:78)
	at water.Atomic.fork(Atomic.java:39)
	at water.Atomic.invoke(Atomic.java:31)
	at water.Lockable.write_lock(Lockable.java:61)`

**Comment by hemanshupaliwa7** [comment]
@jakubhava...

I have run the application as java, and think i got a detailed error here now..

`Exception in thread "main" DistributedException from DESKTOP-RM16H20/192.168.0.5:54321: 'Chunks have different sizes in different vectors: 2 in vector 1 and3 in vector 0', caused by java.lang.IllegalArgumentException: Chunks have different sizes in different vectors: 2 in vector 1 and3 in vector 0
	at water.MRTask.getResult(MRTask.java:479)
	at water.MRTask.getResult(MRTask.java:487)
	at water.MRTask.doAll(MRTask.java:391)
	at water.MRTask.doAll(MRTask.java:386)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$.checkNumberOfEntriesInEachChunk(InternalWriteConverterCtx.scala:178)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$.org$apache$spark$h2o$backends$internal$InternalWriteConverterCtx$$validateFrame(InternalWriteConverterCtx.scala:160)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.finalizeFrame(InternalWriteConverterCtx.scala:58)
	at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.convert(WriteConverterCtxUtils.scala:121)
	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:81)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:89)
	at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:64)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:212)
	at myorg.com.process.H2OMain$.delayedEndpoint$myorg$com$process$H2OMain$1(H2OMain.scala:34)
	at myorg.com.process.H2OMain$delayedInit$body.apply(H2OMain.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at myorg.com.process.H2OMain$.main(H2OMain.scala:7)
	at myorg.com.process.H2OMain.main(H2OMain.scala)
Caused by: java.lang.IllegalArgumentException: Chunks have different sizes in different vectors: 2 in vector 1 and3 in vector 0`

**Comment by jakubhava** [comment]
@hemanshupaliwa7 could you please share with us the shape of data you are trying to convert? Or the reproducible code snippet? Thank you

**Comment by hemanshupaliwa7** [comment]
@jakubhava 

I solved the error "'Chunks have different sizes in different vectors: 2 in vector 1 and3 in vector 0', caused by java.lang.IllegalArgumentException: Chunks have different sizes in different vectors: 2 in vector 1 and3 in vector 0" by converting my feature vector column to Sparse.

But i am getting the error that I was getting before on my office system and some thing is working on my personal system 

Current Error = "Exception in thread "main" java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
        at jsr166y.CountedCompleter.__tryComplete(CountedCompleter.java:427)
        at jsr166y.CountedCompleter.tryComplete(CountedCompleter.java:383)
"

**Comment by jakubhava** [comment]
Could you please describe the environment you have in your office & home systems, what are the differences there?

**Comment by jakubhava** [comment]
@hemanshupaliwa7 it would help us a lot if you could please share with us on which data the `Chunks have different sizes in different vectors` exception happen as it is possible we have a bug in the code on one specific edge case?

Also could you please remove `"org.codehaus.jsr166-mirror" % "jsr166y" % "1.7.0"` from your dependencies and try it again like:


```val sparkVersion = "2.4.0"
val sparklingWaterVersion = "3.28.0.3-1-2.4"

libraryDependencies ++= Seq(
//Spark Libreries
"org.apache.spark" %% "spark-core" % sparkVersion,
"org.apache.spark" %% "spark-streaming" % sparkVersion,
"org.apache.spark" %% "spark-streaming-kafka-0-10" % sparkVersion,
"org.apache.spark" %% "spark-sql-kafka-0-10" % sparkVersion,
"org.apache.spark" %% "spark-sql" % sparkVersion,
"org.apache.spark" %% "spark-mllib" % sparkVersion,
"org.apache.spark" %% "spark-hive" % sparkVersion,
"org.apache.spark" %% "spark-repl" % sparkVersion,
//Sparkling Water
"ai.h2o" %% "sparkling-water-package" % sparklingWaterVersion,
)
```

**Comment by hemanshupaliwa7** [comment]
@jakubhava

Sorry I was away for a while, everything seems to be working fine now. I am working in SBT, I had to add Sparkling Water Jar file in the lib folder in SBT Structure...Chunks issue was related to Vector field which has both sparse and dense vector in it. After converting to Sparse Vector I didn't get Chunks Issue...

**Comment by hemanshupaliwa7** [comment]
Thanks @jakubhava for your support !!!

**Comment by jakubhava** [comment]
Thank you! I will add test for the case with dense & sparse vector to our test suite! Glad to help :)
