### ISSUE TITLE
Fails when passing a vector as an input column through new H2OAutoML.setFeaturesCol()

### ISSUE THREAD

**Issue by prarshah** [h2oai/sparkling-water#1721]
Providing us with the observed and expected behavior definitely helps. Giving us with the following information definitively helps:

- Sparkling Water/PySparkling/RSparkling version - LATEST
- Hadoop Version & Distribution
- Execution mode local
- H2O & Spark logs if not running on YARN. You can find these logs in Spark work directory
Exception in thread "main" DistributedException from localhost/127.0.0.1:54321: 'Chunks have different sizes in different vectors: 1203 in vector 1 and608 in vector 7', caused by java.lang.IllegalArgumentException: Chunks have different sizes in different vectors: 1203 in vector 1 and608 in vector 7
	at water.MRTask.getResult(MRTask.java:479)
	at water.MRTask.getResult(MRTask.java:487)
	at water.MRTask.doAll(MRTask.java:391)
	at water.MRTask.doAll(MRTask.java:386)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$.checkNumberOfEntriesInEachChunk(InternalWriteConverterCtx.scala:177)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$.org$apache$spark$h2o$backends$internal$InternalWriteConverterCtx$$validateFrame(InternalWriteConverterCtx.scala:159)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.finalizeFrame(InternalWriteConverterCtx.scala:58)
	at org.apache.spark.h2o.converters.WriteConverterCtxUtils$ClientBasedConverter$.convert(WriteConverterCtxUtils.scala:146)
	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrameKeyString(SparkDataFrameConverter.scala:101)
	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:68)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:227)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:227)
	at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:78)
	at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:62)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:227)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:224)
	at ai.h2o.sparkling.ml.algos.H2OAlgoCommonUtils$class.prepareDatasetForFitting(H2OAlgoCommonUtils.scala:48)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.prepareDatasetForFitting(H2OAutoML.scala:38)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:53)
	at PocSparklingWater.iris$.main(iris.scala:98)
	at PocSparklingWater.iris.main(iris.scala)
Caused by: java.lang.IllegalArgumentException: Chunks have different sizes in different vectors: 1203 in vector 1 and608 in vector 7
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$$anon$1$$anonfun$map$1.apply(InternalWriteConverterCtx.scala:171)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$$anon$1$$anonfun$map$1.apply(InternalWriteConverterCtx.scala:169)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$$anon$1.map(InternalWriteConverterCtx.scala:169)
	at water.MRTask.compute2(MRTask.java:641)
	at water.H2O$H2OCountedCompleter.compute1(H2O.java:1458)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx$$anon$1$Icer.compute1(InternalWriteConverterCtx$$anon$1$Icer.java)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1454)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
19/12/24 11:55:26 INFO SparkContext: Invoking stop() from shutdown hook

- Are you using Windows/Linux/MAC? MAC
- Spark & Sparkling Water configuration including the memory configuration - Default

**Comment by prarshah** [comment]
It was because VectorAssembler creates a different representation for sparse vectors, by writing a udf for un-dencesing the vector, it solved my issue. Thankyou.
