### ISSUE TITLE
Exception in model.fit method 

### ISSUE THREAD

**Issue by BhushG** [h2oai/sparkling-water#1722]
Exception in thread "main" java.lang.IllegalAccessError: tried to access class ml.dmlc.xgboost4j.java.NativeLibLoader from class hex.tree.xgboost.XGBoostExtension
	at hex.tree.xgboost.XGBoostExtension.initXgboost(XGBoostExtension.java:68)
	at hex.tree.xgboost.XGBoostExtension.isEnabled(XGBoostExtension.java:49)
	at water.ExtensionManager.isEnabled(ExtensionManager.java:189)
	at water.ExtensionManager.registerCoreExtensions(ExtensionManager.java:103)
	at water.H2O.main(H2O.java:2044)
	at water.H2OStarter.start(H2OStarter.java:22)
	at water.H2OStarter.start(H2OStarter.java:52)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.startH2OWorkerAsClient(InternalH2OBackend.scala:118)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OCluster(InternalH2OBackend.scala:95)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:41)
	at org.apache.spark.h2o.H2OContext$H2OContextClientBased.initBackend(H2OContext.scala:448)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:150)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:606)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:634)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:641)
	at org.exadatum.xstream.driver.Utils.automl.components.H2OObj$.main(H2OObj.scala:30)
	at org.exadatum.xstream.driver.Utils.automl.components.H2OObj.main(H2OObj.scala)

**Comment by BhushG** [comment]
Hi, I found a turnaround for this problem. Apparently, the sequence of the dependencies matters in maven. So I moved the dependency of h2o above dependency of xgboost4j-spark and it worked.

    <dependency>
        <groupId>ai.h2o</groupId>
        <artifactId>sparkling-water-package_2.11</artifactId>
        <version>${h2o.automl.version}</version>
    </dependency>
    <dependency>
        <groupId>ml.dmlc</groupId>
        <artifactId>xgboost4j-spark</artifactId>
        <version>${xgboost4j.spark.verion}</version>
    </dependency>
Thus h2o doesn't throw any error related to XGBoost

**Comment by garimagupta25** [comment]
hi, how to change this sequence of dependency? I am getting the same error!
