### ISSUE TITLE
java.lang.RuntimeException: Cloud size 1 under 2 Error : java.lang.RuntimeException: Cloud size 1 under 2

### ISSUE THREAD

**Issue by snallam12** [h2oai/sparkling-water#1768]
Below are the version of h2o/sparkling water we are using
**install.packages("sparklyr")
library(sparklyr)
install.packages("h2o", type = "source", repos = "https://h2o-release.s3.amazonaws.com/h2o/rel-yu/1/R")
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.1-1-2.4/R")**

Using spark 2.4.4

We had issues with as_h2o_frame function saying it doesn't exist in a different version so we started using the above. It resolved the issue but we now have a new one. When we try to run our scripts on databricks clusters we see the error when we run as_h2o_frame function again:

**java.lang.RuntimeException: Cloud size 1 under 2 Error : java.lang.RuntimeException: Cloud size 1 under 2
	at water.H2O.waitForCloudSize(H2O.java:1860)**

This issue is not consistent and scripts sometimes works well but mostly throw this error. 

[](url)

**Comment by jakubhava** [comment]
@snallam12 could you please share the logs with us?

Also we are fixing several issues in the internal backend of Sparkling Water affecting the cloud up in the next release 3.28.0.3. It is possible this might be related

**Comment by snallam12** [comment]
Hi Jakub,

PFB logs.

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
/databricks/python/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/databricks/python/lib/python3.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated since IPython 4.0. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
Mon Feb  3 16:21:27 2020 py4j imported
Mon Feb  3 16:21:27 2020 Python shell started with PID  2795  and guid  11c250e7ff2c437da3923514075aacf8
Mon Feb  3 16:21:28 2020 Python shell executor start
Dropped logging in PythonShell:

b'/local_disk0/tmp/1580746885452-0/PythonShell.py:747: DeprecationWarning: The `use_readline` parameter is deprecated and ignored since IPython 6.0.\n  parent=self,\n'
/databricks/python/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/databricks/python/lib/python3.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated since IPython 4.0. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
Mon Feb  3 16:21:36 2020 py4j imported
Mon Feb  3 16:21:36 2020 Python shell started with PID  2860  and guid  508402dcec204958a62c5e6591e2c2c1
Mon Feb  3 16:21:36 2020 Python shell executor start
20/02/03 16:25:32 ERROR sparklyr: Gateway (65529) failed calling getOrCreate on org.apache.spark.h2o.H2OContext: java.lang.RuntimeException: Cloud size 1 under 2
                at water.H2O.waitForCloudSize(H2O.java:1860)
                at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OCluster(InternalH2OBackend.scala:105)
                at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:41)
                at org.apache.spark.h2o.H2OContext$H2OContextClientBased.initBackend(H2OContext.scala:448)
                at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:150)
                at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:606)
                at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:622)
                at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at sparklyr.Invoke.invoke(invoke.scala:147)
                at sparklyr.StreamHandler.handleMethodCall(stream.scala:122)
                at sparklyr.StreamHandler.read(stream.scala:65)
                at sparklyr.BackendHandler.channelRead0(handler.scala:53)
                at sparklyr.BackendHandler.channelRead0(handler.scala:12)
                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
                at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)

Thanks,
Swetha

**Comment by jakubhava** [comment]
Would it be possible to collect YARN logs? there are just the driver logs. In the full yarn logs we can see what actually went wrong

**Comment by kaleb-thompson** [comment]
> @snallam12 could you please share the logs with us?
> 
> Also we are fixing several issues in the internal backend of Sparkling Water affecting the cloud up in the next release 3.28.0.3. It is possible this might be related

Hi Jakub,

When do you all plan to release 3.28.0.3? We are using this in a production solution and we may need to work on an alternative solution if the fix is not imminent.

Thanks,

Kaleb

**Comment by jakubhava** [comment]
Without the YARN logs I can verify the nature of the issues. But to answer the question regarding release -> the release will go out this week

**Comment by kaleb-thompson** [comment]
> Without the YARN logs I can verify the nature of the issues. But to answer the question regarding release -> the release will go out this week

She sent these via email:

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
/databricks/python/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/databricks/python/lib/python3.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated since IPython 4.0. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
Mon Feb  3 16:21:27 2020 py4j imported
Mon Feb  3 16:21:27 2020 Python shell started with PID  2795  and guid  11c250e7ff2c437da3923514075aacf8
Mon Feb  3 16:21:28 2020 Python shell executor start
Dropped logging in PythonShell:

b'/local_disk0/tmp/1580746885452-0/PythonShell.py:747: DeprecationWarning: The `use_readline` parameter is deprecated and ignored since IPython 6.0.\n  parent=self,\n'
/databricks/python/lib/python3.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/databricks/python/lib/python3.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated since IPython 4.0. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
Mon Feb  3 16:21:36 2020 py4j imported
Mon Feb  3 16:21:36 2020 Python shell started with PID  2860  and guid  508402dcec204958a62c5e6591e2c2c1
Mon Feb  3 16:21:36 2020 Python shell executor start
20/02/03 16:25:32 ERROR sparklyr: Gateway (65529) failed calling getOrCreate on org.apache.spark.h2o.H2OContext: java.lang.RuntimeException: Cloud size 1 under 2
                at water.H2O.waitForCloudSize(H2O.java:1860)
                at org.apache.spark.h2o.backends.internal.InternalH2OBackend$.org$apache$spark$h2o$backends$internal$InternalH2OBackend$$startH2OCluster(InternalH2OBackend.scala:105)
                at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:41)
                at org.apache.spark.h2o.H2OContext$H2OContextClientBased.initBackend(H2OContext.scala:448)
                at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:150)
                at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:606)
                at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:622)
                at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at sparklyr.Invoke.invoke(invoke.scala:147)
                at sparklyr.StreamHandler.handleMethodCall(stream.scala:122)
                at sparklyr.StreamHandler.read(stream.scala:65)
                at sparklyr.BackendHandler.channelRead0(handler.scala:53)
                at sparklyr.BackendHandler.channelRead0(handler.scala:12)
                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
                at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)

**Comment by jakubhava** [comment]
These are only logs from the driver. We need logs from all the executors etc

**Comment by kaleb-thompson** [comment]
> These are only logs from the driver. We need logs from all the executors etc

We are working on it. We'll send them over shortly..  Thanks!

**Comment by snallam12** [comment]
20/02/03 21:21:47 INFO MemoryStore: Block broadcast_42_piece0 stored as bytes in memory (estimated size 25.0 KB, free 20.8 GB)
20/02/03 21:21:47 INFO TorrentBroadcast: Reading broadcast variable 42 took 6 ms
20/02/03 21:21:47 INFO MemoryStore: Block broadcast_42 stored as values in memory (estimated size 85.3 KB, free 20.8 GB)
20/02/03 21:21:47 INFO Utils: Successfully started service 'sparkling-water-h2o-start-0' on port 40489.
20/02/03 21:21:47 INFO Executor: Finished task 3.0 in stage 30.0 (TID 138). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 15.0 in stage 30.0 (TID 150). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 9.0 in stage 30.0 (TID 144). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 5.0 in stage 30.0 (TID 140). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 1.0 in stage 30.0 (TID 136). 1082 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 13.0 in stage 30.0 (TID 148). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Finished task 7.0 in stage 30.0 (TID 142). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO CoarseGrainedExecutorBackend: Got assigned task 151
20/02/03 21:21:47 INFO Executor: Running task 16.0 in stage 30.0 (TID 151)
20/02/03 21:21:47 INFO CoarseGrainedExecutorBackend: Got assigned task 152
20/02/03 21:21:47 INFO Executor: Running task 17.0 in stage 30.0 (TID 152)
20/02/03 21:21:47 INFO CoarseGrainedExecutorBackend: Got assigned task 153
20/02/03 21:21:47 INFO Executor: Running task 18.0 in stage 30.0 (TID 153)
20/02/03 21:21:47 INFO CoarseGrainedExecutorBackend: Got assigned task 154
20/02/03 21:21:47 INFO Executor: Running task 19.0 in stage 30.0 (TID 154)
20/02/03 21:21:47 INFO CoarseGrainedExecutorBackend: Got assigned task 155
20/02/03 21:21:47 INFO Executor: Finished task 11.0 in stage 30.0 (TID 146). 1039 bytes result sent to driver
20/02/03 21:21:47 INFO Executor: Running task 20.0 in stage 30.0 (TID 155)
20/02/03 21:21:48 INFO Executor: Finished task 19.0 in stage 30.0 (TID 154). 1039 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 16.0 in stage 30.0 (TID 151). 1039 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 18.0 in stage 30.0 (TID 153). 1039 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 20.0 in stage 30.0 (TID 155). 1039 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 17.0 in stage 30.0 (TID 152). 1039 bytes result sent to driver
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 157
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 159
20/02/03 21:21:48 INFO Executor: Running task 1.0 in stage 31.0 (TID 157)
20/02/03 21:21:48 INFO Executor: Running task 3.0 in stage 31.0 (TID 159)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 161
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 163
20/02/03 21:21:48 INFO Executor: Running task 5.0 in stage 31.0 (TID 161)
20/02/03 21:21:48 INFO Executor: Running task 7.0 in stage 31.0 (TID 163)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 165
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 167
20/02/03 21:21:48 INFO Executor: Running task 11.0 in stage 31.0 (TID 167)
20/02/03 21:21:48 INFO Executor: Running task 9.0 in stage 31.0 (TID 165)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 169
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 171
20/02/03 21:21:48 INFO Executor: Running task 13.0 in stage 31.0 (TID 169)
20/02/03 21:21:48 INFO Executor: Running task 15.0 in stage 31.0 (TID 171)
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Updating epoch to 9 and clearing cache
20/02/03 21:21:48 INFO TorrentBroadcast: Started reading broadcast variable 43
20/02/03 21:21:48 INFO MemoryStore: Block broadcast_43_piece0 stored as bytes in memory (estimated size 2.3 KB, free 20.8 GB)
20/02/03 21:21:48 INFO TorrentBroadcast: Reading broadcast variable 43 took 4 ms
20/02/03 21:21:48 INFO MemoryStore: Block broadcast_43 stored as values in memory (estimated size 4.0 KB, free 20.8 GB)
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.139.64.10:33801)
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 8, fetching them
20/02/03 21:21:48 INFO MapOutputTrackerWorker: Got the output locations
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO Executor: Finished task 11.0 in stage 31.0 (TID 167). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 1.0 in stage 31.0 (TID 157). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 5.0 in stage 31.0 (TID 161). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 9.0 in stage 31.0 (TID 165). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 13.0 in stage 31.0 (TID 169). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 7.0 in stage 31.0 (TID 163). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 15.0 in stage 31.0 (TID 171). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 3.0 in stage 31.0 (TID 159). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 172
20/02/03 21:21:48 INFO Executor: Running task 16.0 in stage 31.0 (TID 172)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 173
20/02/03 21:21:48 INFO Executor: Running task 17.0 in stage 31.0 (TID 173)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 174
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 175
20/02/03 21:21:48 INFO Executor: Running task 19.0 in stage 31.0 (TID 175)
20/02/03 21:21:48 INFO Executor: Running task 18.0 in stage 31.0 (TID 174)
20/02/03 21:21:48 INFO CoarseGrainedExecutorBackend: Got assigned task 176
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO Executor: Finished task 16.0 in stage 31.0 (TID 172). 1114 bytes result sent to driver
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO Executor: Finished task 17.0 in stage 31.0 (TID 173). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 19.0 in stage 31.0 (TID 175). 1114 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Finished task 18.0 in stage 31.0 (TID 174). 1157 bytes result sent to driver
20/02/03 21:21:48 INFO Executor: Running task 20.0 in stage 31.0 (TID 176)
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks including 0 local blocks and 0 remote blocks
20/02/03 21:21:48 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
20/02/03 21:21:48 INFO Executor: Finished task 20.0 in stage 31.0 (TID 176). 1114 bytes result sent to driver
20/02/03 21:21:48 INFO NativeLibrary: Loaded library from lib/linux_64/libxgboost4j_gpu.so (/local_disk0/tmp/libxgboost4j_gpu435782995545325068.so)
20/02/03 21:21:48 INFO log: Logging initialized @235228ms
20/02/03 21:21:48 INFO Server: jetty-9.3.z-SNAPSHOT
20/02/03 21:21:48 INFO ContextHandler: Started a.h.o.e.j.s.ServletContextHandler@7585c463{/,null,AVAILABLE}
20/02/03 21:21:48 INFO AbstractConnector: Started ServerConnector@1d28ce24{HTTP/1.1,[http/1.1]}{0.0.0.0:54321}
20/02/03 21:21:48 INFO Server: Started @235358ms
**20/02/03 21:21:54 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[TCP-SMALL-SEND-/10.139.64.9:54321,10,main]
java.lang.UnsupportedOperationException
	at java.nio.ByteBuffer.array(ByteBuffer.java:994)
	at water.H2ONode$SmallMessagesSendThread.run(H2ONode.java:586)
20/02/03 21:21:55 INFO privateLog: "Executor task launch worker for task 157" #56 TIMED_WAITING
	sun.misc.Unsafe.park(Native Method)
	java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)**
	java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)



Is this useful?

**Comment by jakubhava** [comment]
Yes, thank you. This error is fixed in the release we are doing this week -> 3.28.0.3

**Comment by kaleb-thompson** [comment]
> Yes, thank you. This error is fixed in the release we are doing this week -> 3.28.0.3

Great thank you. Is there any way for us to safeguard against things like this? I guess I don't understand why everything was working fine and it just randomly broke. 

I understand things happen but we need to have some degree of certainty that we can depend on this not to break unless we shouldn't be using it in production.

**Comment by jakubhava** [comment]
The error was there for a long time already, but wasn't deterministic. The non-deterministic behaviour might also depend on the infrastructure changes on DBC side.

We have added tests on our site for this specific issue to make sure it won't ever go back

**Comment by jakubhava** [comment]
Sparkling Water 3.28.0.3 is released which fixes the issues above:

    Spark 2.4: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.3-1-2.4/index.html
    Spark 2.3: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.3/3.28.0.3-1-2.3/index.html
    Spark 2.2: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.2/3.28.0.3-1-2.2/index.html
    Spark 2.1: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.1/3.28.0.3-1-2.1/index.html

**Comment by jakubhava** [comment]
If you happen to bump into any new issues, please feel free to start a new or re-open this ticket
