### ISSUE TITLE
ArrayIndexOutOfBoundsException when loading a larger data sample

### ISSUE THREAD

**Issue by sanchopansa** [h2oai/sparkling-water#182]
Hello, devs!

First of all, thanks for making this very nice library open source.

While experimenting with sparkling-water, I hit the following issue:
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 97 in stage 25.0 failed 4 times, most recent failure: Lost task 97.3 in stage 25.0 (TID 2553, prtlap02): j
ava.lang.ArrayIndexOutOfBoundsException: 65535
        at water.DKV.get(DKV.java:202)
        at water.DKV.get(DKV.java:175)
        at water.Key.get(Key.java:83)
        at water.fvec.Frame.createNewChunks(Frame.java:887)
        at water.fvec.FrameUtils$class.createNewChunks(FrameUtils.scala:43)
        at water.fvec.FrameUtils$.createNewChunks(FrameUtils.scala:70)
        at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.createChunks(InternalWriteConverterCtx.scala:29)
        at org.apache.spark.h2o.converters.SparkDataFrameConverter$.org$apache$spark$h2o$converters$SparkDataFrameConverter$$perSQLPartition(SparkDataFrameConverter.scala:94)
        at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$2.apply(SparkDataFrameConverter.scala:73)
        at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$2.apply(SparkDataFrameConverter.scala:73)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:86)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Please note that I am seeing this error only when trying to load a larger user sample (500K users) and it works fine with a smaller one (200K users). I am using sparkling-water v2.0.3 and the following deployment script for my application:
```
#!/usr/bin/env bash

# Change this to point to an existing log4j.properties file
LOGFILE=file:///home/sancho/app/log4j.properties

/usr/local/spark-2.0.1-bin-hadoop2.7/bin/spark-submit \
--driver-java-options "-Dspark.network.timeout=480s
-Dspark.cores.max=$3 -Dlog4j.configuration=$LOGFILE" \
--class $2 \
--conf "spark.cores.max=$3" \
--conf "spark.executor.cores=$4" \
--conf "spark.kryoserializer.buffer.max=1024m" \
--conf "spark.dynamicAllocation.enabled=false" \
--executor-memory 50G \
--driver-memory 15G \
$1 h2o 200 5 0.1
```

Prior to the `ArrayIndexOutOfBoundsException`, I see two warnings. I am not sure if they are related, but posting them here for reference:

```
2017-02-03 09:27:28,551 WARN  could not create Vfs.Dir from url. ignoring the exception and continuing <org.reflections.Reflections>
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at org.reflections.Reflections.<init>(Reflections.java:170)
        at org.reflections.Reflections.<init>(Reflections.java:143)
        at water.api.SchemaServer.registerAllSchemasIfNecessary(SchemaServer.java:197)
        at water.H2O.finalizeRegistration(H2O.java:1512)
        at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:115)
        at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:102)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:279)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:301)
        at tera.profile.experimental.ml.App$.main(App.scala:41)
        at tera.profile.experimental.ml.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

```
2017-02-03 09:27:28,699 WARN  could not create Dir using jarFile from url file:/mnt/ux0//hadoop-2.7.2/share/hadoop/tools/lib/hadoop-aws-2.7.1.jar. skipping. <org.reflections.Reflections>
java.lang.NullPointerException
        at java.util.zip.ZipFile.<init>(ZipFile.java:207)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:212)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at org.reflections.Reflections.<init>(Reflections.java:170)
        at org.reflections.Reflections.<init>(Reflections.java:143)
        at water.api.SchemaServer.registerAllSchemasIfNecessary(SchemaServer.java:197)
        at water.H2O.finalizeRegistration(H2O.java:1512)
        at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:115)
        at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:102)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:279)
        at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:301)
        at tera.profile.experimental.ml.App$.main(App.scala:41)
        at tera.profile.experimental.ml.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I find the second warning a bit weird: it's looking for a 2.7.1 file inside the Hadoop 2.7.2 folder. This file is not present and instead I have `hadoop-aws-2.7.2.jar`.

I hope you can point me in the right direction, as I am not sure how to debug this further.

Thanks!

**Comment by mdymczyk** [comment]
Hey @sanchopansa I noticed this issue already but all the devs are quite swamped with work right now. Did you investigate it a bit more yourself?

**Comment by sanchopansa** [comment]
Hi @mdymczyk, thanks for getting in touch. TBH, I am not sure how to investigate further. If you give me some pointers what to try/look for, I could do it later during the week.

**Comment by mmalohlava** [comment]
Hi @sanchopansa , it seems like H2O was not started inside executor (Reflection can be the cause which cancelled H2O boot). Do you have logs from executors? That would be helpful.

**Comment by jakubhava** [comment]
@sanchopansa any update on this ? Could you provide us with the logs please ?

**Comment by DINESHKUMARMURUGAN** [comment]
@sanchopansa Any update on this? Did you fix this, if so, how?

**Comment by jakubhava** [comment]
@sanchopansa I'm closing this issue for now as there is no response. Please feel free to open an new issue if you see a similar problem. Thanks!

**Comment by fabboe** [comment]
Thanks for the support @jakubhava. Unfortunately neither @sanchopansa nor me had time to get back to this. We'll come back when we come back :)

**Comment by Tagar** [comment]
@sanchopansa @mdymczyk @DINESHKUMARMURUGAN did you guys find a way to fix or work around this issue ? 

just opened https://github.com/h2oai/sparkling-water/issues/597 which seems to be the same issue

**Comment by sanchopansa** [comment]
I wasn't able to find a fix for this and sadly didn't have time to look into it further. We ended up using a different library for the computation.
