### ISSUE TITLE
Issue with Obtain SHAP values from MOJO model

### ISSUE THREAD

**Issue by hemanshupaliwa7** [h2oai/sparkling-water#1828]
Hello,

I am facing issue "Caused by: java.lang.ArrayIndexOutOfBoundsException: -1" while trying to get the SHAP Values getting details from "http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/shap_values.html"

My Sparkling Version is latest "3.28.0.3-1-2.4" and Spark Version is 2.4.4. 
Code 
` import ai.h2o.sparkling.ml.algos.H2OXGBoost
  val xgBoost = new H2OXGBoost()
    .setLabelCol("label")
    .setFeaturesCol("indexedFeatures")
    .setDetailedPredictionCol("detailed_prediction")
    .setWithDetailedPredictionCol(true)

  val xgBoostModel = xgBoost.fit(trainH2ODf)

  val testPredictionsXGBoost = xgBoostModel.transform(testH2ODf)
  testPredictionsXGBoost.printSchema()
  testPredictionsXGBoost.select("detailed_prediction.contributions").show()
`

Received Error
`*** H2O Configuration and Context
20/02/12 08:57:25 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 0 (Infinitive) as we need to ensure we run on the nodes with H2O
*** H2O Train and Test Frames
*** Perform H2O XGBoost
20/02/12 08:57:27 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 0 (Infinitive) as we need to ensure we run on the nodes with H2O
20/02/12 08:57:36 WARN H2OConf: The method 'externalWriteConfirmationTimeout' is deprecated.
root
 |-- label: string (nullable = false)
 |-- indexedFeatures: vector (nullable = true)
 |-- detailed_prediction: struct (nullable = true)
 |    |-- label: string (nullable = true)
 |    |-- p0: double (nullable = false)
 |    |-- p1: double (nullable = false)
 |    |-- contributions: array (nullable = true)
 |    |    |-- element: float (containsNull = false)
 |-- prediction: string (nullable = true)

20/02/12 08:57:51 ERROR Executor: Exception in task 23.0 in stage 295.0 (TID 19159)
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$getBinomialPredictionUDF$3: (struct<indexedFeatures:struct<type:tinyint,size:int,indices:array<int>,values:array<double>>>, double) => struct<label:string,p0:double,p1:double,contributions:array<float>>)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage9.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:136)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:181)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:181)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:181)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:181)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.calculateContributions(TreeSHAP.java:237)
        at hex.genmodel.algos.tree.TreeSHAPEnsemble.calculateContributions(TreeSHAPEnsemble.java:29)
        at hex.genmodel.algos.xgboost.XGBoostJavaMojoModel$XGBoostContributionsPredictor.calculateContributions(XGBoostJavaMojoModel.java:187)
        at hex.genmodel.easy.EasyPredictModelWrapper.predictBinomial(EasyPredictModelWrapper.java:580)
        at ai.h2o.sparkling.ml.models.H2OMOJOPredictionBinomial$$anonfun$getBinomialPredictionUDF$3.apply(H2OMOJOPredictionBinomial.scala:54)
        at ai.h2o.sparkling.ml.models.H2OMOJOPredictionBinomial$$anonfun$getBinomialPredictionUDF$3.apply(H2OMOJOPredictionBinomial.scala:52)
        ... 21 more
`

**Comment by jakubhava** [comment]
Thanks for the report @hemanshupaliwa7, I will try to reproduce

**Comment by michalkurka** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:136)
```

This is suspicious and looks like a bug in the TreeSHAP code.

@hemanshupaliwa7 Are there any details you could share with us? Having the model (if it doesn't have any proprietary information) would be the best.

**Comment by hemanshupaliwa7** [comment]
@michalkurka Sorry, I wouldn't be able to share the model. However, I could help you the steps that I followed in my program. If that helps?

**Comment by hemanshupaliwa7** [comment]
@michalkurka 
I have a mock-project on GitHub where I was working on Some random dataset from the the web. I get the same exact error here as well when I try to see SHAP info. 

GitHub Project: https://github.com/hemanshupaliwa7/LoanPredictionIII
Model: https://github.com/hemanshupaliwa7/LoanPredictionIII/blob/master/MyOrgModel.tar.gz

Hope this helps you!

**Comment by jakubhava** [comment]
@hemanshupaliwa7 I have created JIRA to track progress of this issue https://0xdata.atlassian.net/browse/PUBDEV-7307

**Comment by michalkurka** [comment]
@hemanshupaliwa7 thank you, this is very helpful - I will look into the issue

**Comment by hemanshupaliwa7** [comment]
Hello @michalkurka  @jakubhava ,

Is it solved yet ??

**Comment by michalkurka** [comment]
@hemenkapadia I am not sure - I did make improvements of the Shapley calculation that should prevent the issue from happening but I didn't yet have the time to validate the improvements with your reproducer

**Comment by hemanshupaliwa7** [comment]
Hello @michalkurka ,

I tried with latest version of Sparkling Water "3.28.1.2-1-2.4" with Spark Version "2.4.5"

I can now see the SHAP Values. Seems like it's working for me now.

**Comment by hemanshupaliwa7** [comment]
Hello @michalkurka @jakubhava ,

As mentioned it's working seamlessly now with the given versions (Sparkling Water "3.28.1.2-1-2.4" with Spark Version "2.4.5"), however performance is really low now. 

My goal is to extract probabilities for each classes from detailed_prediction attributes, I could do that but it takes around 2-3 hours for 100k records. 

This is how I am doing it: https://github.com/hemanshupaliwa7/LoanPredictionIII/blob/rel-1.0/src/main/scala/myorg/com/process/H2OMain.scala

```
val flattenedPredXGBoost = testPredictionsXGBoost
    //.select("label", "prediction", "detailed_prediction.probabilities")
    //.withColumn("keys", map_keys(col("detailed_prediction.probabilities")))
    //.withColumn("values", map_values(col("detailed_prediction.probabilities")))
    //.select("label", "prediction", "keys", "values")
    //.withColumn("p0", extractValue0(col("values")))
    //.withColumn("p1", extractValue1(col("values")))
      .withColumn("p0", element_at(col("detailed_prediction.probabilities"), "0"))
      .withColumn("p1", element_at(col("detailed_prediction.probabilities"), "1"))
      .select("label", "prediction", "p0", "p1")
```

**Comment by michalkurka** [comment]
@hemanshupaliwa7 thank you for the report, this is definitely not expected - let me see what I can do to improve the performance

**Comment by hemanshupaliwa7** [comment]
@michalkurka Thanks, I will share more details if i get anything relevant and important to be shared with you

**Comment by hemanshupaliwa7** [comment]
Hello @michalkurka 

Related to this https://github.com/h2oai/sparkling-water/issues/1828#issuecomment-610436051.

I ran GLM, GBM, XGBoost, AutoML(DRF and StackedEnsemble) and DRF in sequence in one session, first four ran successfully and returned SHAP values really fast, however DRF was error out with this error 

`[WARN] 2020-04-09 14:44:08,252 org.apache.spark.scheduler.TaskSetManager logWarning - Lost task 400.0 in stage 1558.0 (TID 122560, localhost, executor driver): org.apache.spark.SparkException: Fail
ed to execute user defined function($anonfun$getBinomialPredictionUDF$3: (struct<indexedFeatures:struct<type:tinyint,size:int,indices:array<int>,values:array<double>>>, double) => struct<label:stri
ng,probabilities:map<string,double>,contributions:array<float>>)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$1$$anon$1.hasNext(InMemoryRelation.scala:125)
        at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
        at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:308)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 36
        at hex.genmodel.algos.tree.TreeSHAP$PathPointer.move(TreeSHAP.java:206)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:123)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.treeShap(TreeSHAP.java:177)
        at hex.genmodel.algos.tree.TreeSHAP.calculateContributions(TreeSHAP.java:237)
        at hex.genmodel.algos.tree.TreeSHAPEnsemble.calculateContributions(TreeSHAPEnsemble.java:29)
        at hex.genmodel.algos.tree.ContributionsPredictor.calculateContributions(ContributionsPredictor.java:18)
        at hex.genmodel.easy.EasyPredictModelWrapper.predictBinomial(EasyPredictModelWrapper.java:580)
        at ai.h2o.sparkling.ml.models.H2OMOJOPredictionBinomial$$anonfun$getBinomialPredictionUDF$3.apply(H2OMOJOPredictionBinomial.scala:54)
        at ai.h2o.sparkling.ml.models.H2OMOJOPredictionBinomial$$anonfun$getBinomialPredictionUDF$3.apply(H2OMOJOPredictionBinomial.scala:52)
        ... 34 more
`


Also if i run them in separate sessions, then DRF SHAP values run for longer time as mentioned here  https://github.com/h2oai/sparkling-water/issues/1828#issuecomment-610436051

**Comment by hemanshupaliwa7** [comment]
I noticed one more this related to above issue. If I run all models in sequence, and DRF Model is running at the end, then it runs successfully but it takes lot of time to give SHAP Values. And if DRF is not at the end somewhere in the middle then it error out.
