### ISSUE TITLE
DistributedException caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by rahuljain788** [h2oai/sparkling-water#187]
I am getting the error when running the below code :

scala> val dataFile = "examples/smalldata/allyears2k_headers.csv.gz"
dataFile: String = examples/smalldata/allyears2k_headers.csv.gz

scala>

scala> val airlinesData = new H2OFrame(new File(dataFile))
DistributedException from <servername>, caused by java.lang.NullPointerException
Caused by: java.lang.NullPointerException
        at water.parser.ParseSetup$GuessSetupTsk.map(ParseSetup.java:400)
        at water.MRTask.compute2(MRTask.java:595)
        at water.H2O$H2OCountedCompleter.compute1(H2O.java:1201)
        at water.parser.ParseSetup$GuessSetupTsk$Icer.compute1(ParseSetup$GuessSetupTsk$Icer.java)
        at water.H2O$H2OCountedCompleter.compute(H2O.java:1197)
        at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
        at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
        at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by mdymczyk** [comment]
@rahuljain788 from which location are you starting `sparkling-shell`?

**Comment by rahuljain788** [comment]
@mdymczyk  am running it from the shell using command bin/sparkling-shell --num-executors 3 --executor-memory 2g --master yarn-client  

Its is successfully creating sql and sparContext but here it's throwing error

**Comment by mdymczyk** [comment]
@rahuljain788 when you're running it on `yarn` then the data file has to be accessible to all executors (either on a distributed FS like HDFS or copied to all the executors). You're getting an NPE because you're trying to pass a local path to the parser and that file is accessible only from your driver. Passing the absolute path might work if your Hadoop cluster is running on your laptop.

**Comment by rahuljain788** [comment]
@mdymczyk Thank you for your reply. 

The path i am passing is indeed HDFS directory path and not my driver path.

**Comment by mdymczyk** [comment]
@rahuljain788 so it's different than `val dataFile = "examples/smalldata/allyears2k_headers.csv.gz"`? Because that's not a proper HDFS URI, this will look for files on your local drive.

Please post the exact failing scenario.

**Comment by rahuljain788** [comment]
you are right this is the local path and i was assuming it to be HDFS. 

Thank you
