### ISSUE TITLE
NullPointerException in Docker run-example.sh

### ISSUE THREAD

**Issue by tcfuji** [h2oai/sparkling-water#19]
Getting the following exception after running `bin/run-example.sh` within the bash container:
```
15/10/20 16:29:02 INFO TaskSetManager: Finished task 196.0 in stage 17.0 (TID 1040) in 565 ms on 0b4ad106ca69 (200/200)
15/10/20 16:29:02 INFO TaskSchedulerImpl: Removed TaskSet 17.0, whose tasks have all completed, from pool
15/10/20 16:29:02 INFO DAGScheduler: Stage 17 (runJob at H2OContext.scala:258) finished in 20.698 s
15/10/20 16:29:02 INFO DAGScheduler: Job 8 finished: runJob at H2OContext.scala:258, took 21.150594 s
Exception in thread "main" java.lang.NullPointerException
	at org.apache.spark.examples.h2o.AirlinesWithWeatherDemo2$.main(AirlinesWithWeatherDemo2.scala:83)
	at org.apache.spark.examples.h2o.AirlinesWithWeatherDemo2.main(AirlinesWithWeatherDemo2.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

^C15/10/20 16:32:24 INFO ExecutorRunner: Killing process!
15/10/20 16:32:24 INFO ExecutorRunner: Killing process!
15/10/20 16:32:24 INFO ExecutorRunner: Killing process!
15/10/20 16:32:24 ERROR FileAppender: Error writing stream to file /opt/spark/work/app-20151020162558-0000/1/stderr
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.spark.util.logging.FileAppender.appendStreamToFile(FileAppender.scala:70)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply$mcV$sp(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1460)
	at org.apache.spark.util.logging.FileAppender$$anon$1.run(FileAppender.scala:38)
15/10/20 16:32:24 ERROR FileAppender: Error writing stream to file /opt/spark/work/app-20151020162558-0000/0/stderr
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.spark.util.logging.FileAppender.appendStreamToFile(FileAppender.scala:70)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply$mcV$sp(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1460)
	at org.apache.spark.util.logging.FileAppender$$anon$1.run(FileAppender.scala:38)
15/10/20 16:32:24 ERROR FileAppender: Error writing stream to file /opt/spark/work/app-20151020162558-0000/2/stderr
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.spark.util.logging.FileAppender.appendStreamToFile(FileAppender.scala:70)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply$mcV$sp(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1460)
	at org.apache.spark.util.logging.FileAppender$$anon$1.run(FileAppender.scala:38)
15/10/20 16:32:25 INFO Worker: Executor app-20151020162558-0000/2 finished with state EXITED message Command exited with code 130 exitStatus 130
15/10/20 16:32:25 INFO Worker: Executor app-20151020162558-0000/0 finished with state EXITED message Command exited with code 130 exitStatus 130
15/10/20 16:32:25 ERROR TaskSchedulerImpl: Lost executor 0 on 0b4ad106ca69: remote Akka client disassociated
```

**Comment by mmalohlava** [comment]
@tcfuji make sure that you have example files available fro docker environment.

**Comment by tcfuji** [comment]
@mmalohlava Do you mean I need to download the examples from github? 

Right now there is only:
```
ls examples/scripts/
Meetup20141217.md  dlDemo.script
```

**Comment by mmalohlava** [comment]
@tcfuji which version of Sparkling Water are you using?

**Comment by tcfuji** [comment]
I cloned it from github about 6 hours ago. I'm using the Dockerfile that
was included in that clone.

**Comment by mmalohlava** [comment]
ahh,my fault, it is using old Sparkling Water version:
```
RUN curl -s http://d3kbcqa49mib13.cloudfront.net/spark-1.2.0-bin-cdh4.tgz | tar -xz -C /opt && \
    ln -s /opt/spark-1.2.0-bin-cdh4 /opt/spark && \
    mkdir /opt/spark/work && \
    chmod 0777 /opt/spark/work

# Install Sparkling water latest version
RUN curl -s http://h2o-release.s3.amazonaws.com/sparkling-water/master/75/sparkling-water-0.2.10-75.zip --output sw.zip && \
  unzip sw.zip -d /opt/ && \
  ln -s /opt/sparkling-water-0.2.10-75 /opt/sparkling-water && \
```

If you edit it and replace spark by, for example:
 `http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop2.4.tgz`

and sparkling water by:
 `http://h2o-release.s3.amazonaws.com/sparkling-water/rel-1.5/2/sparkling-water-1.5.2.zip`

Please free to make PR.

**Comment by tcfuji** [comment]
Updating the versions seem to have introduced memory allocation problems.
When running `docker run -i -t --rm sparkling-test-base bin/run-example.sh`:
```
---------
  Using example                  : org.apache.spark.examples.h2o.AirlinesWithWeatherDemo2
  Using master    (MASTER)       : local-cluster[3,2,1024]
  Deploy mode     (DEPLOY_MODE)  : client
  Driver memory   (DRIVER_MEMORY): 1G
  H2O JVM options (H2O_SYS_OPS)  :
---------
Spark Command: /usr/lib/jvm/java-7-oracle/jre/bin/java -cp /opt/spark/conf/:/opt/spark/lib/spark-assembly-1.5.1-hadoop2.4.0.jar:/opt/spark/lib/datanucleus-core-3.2.10.jar:/opt/spark/lib/datanucleus-rdbms-3.2.9.jar:/opt/spark/lib/datanucleus-api-jdo-3.2.6.jar -Xms1G -Xmx1G org.apache.spark.deploy.SparkSubmit --master local-cluster[3,2,1024] --deploy-mode client --conf spark.driver.memory=1G --conf spark.driver.extraJavaOptions= --class org.apache.spark.examples.h2o.AirlinesWithWeatherDemo2 /opt/sparkling-water-1.5.2/assembly/build/libs/sparkling-water-assembly-1.5.2-all.jar
========================================
15/10/21 02:35:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/10/21 02:35:44 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
15/10/21 02:35:45 WARN H2OContext: Increasing 'spark.locality.wait' to value 30000
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fa71956d000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.
```
When running  `docker run -i -t --rm sparkling-test-base bin/sparkling-shell`:
```
-----
  Spark master (MASTER)     : local-cluster[3,2,2048]
  Spark home   (SPARK_HOME) : /opt/spark
  H2O build version         : 3.2.0.5 (slater)
  Spark build version       : 1.5.0
----

Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000740000000, 2147483648, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
```

**Comment by tcfuji** [comment]
@mmalohlava Should I make a PR anyway?

**Comment by mmalohlava** [comment]
Yes please :+1:

**Comment by srisatish** [comment]
yes, please make a PR.

my guess is that the native mem oom might mean new flags to manage the
offheap DirectByteBuffers that might be needed in 1.5

thanks, sri


On Fri, Oct 23, 2015 at 1:00 PM, Ted <notifications@github.com> wrote:

> @mmalohlava <https://github.com/mmalohlava> Should I make a PR anyway?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/h2oai/sparkling-water/issues/19#issuecomment-150633682>
> .
>



-- 
*culture . code . customer*
c o m m u n i t y*, **h2o**.ai, *
+1-408.316.8192

**Comment by tcfuji** [comment]
Done

**Comment by MadMan0708** [comment]
Hi tcfuji, 
  thanks for creating PR and sorry for so late response. We have actually created gradle task which creates docker file and determines latest version of sparkling-water automatically. It's gonna be in master and hopefully in a new sparkling-water release soon. 

Kuba
