### ISSUE TITLE
java.nio.channels.ClosedChannelException in Standalone Mode

### ISSUE THREAD

**Issue by AarynBaelish** [h2oai/sparkling-water#1987]
- Sparkling Water version
- Execution mode  standalone
- Are you using Windows/Linux/MAC? ubuntu

I had a SPARK cluster with one master and two workers, and had tested SparkPi successfully.

when trying to start  Sparkling Water as a Spark Package, like this:
```$SPARK_HOME/bin/spark-shell --packages ai.h2o:sparkling-water-package_2.11:3.28.1.2-1-2.4```

get a spark shell:
```Ivy Default Cache set to: /home/spark/.ivy2/cache
The jars for the packages stored in: /home/spark/.ivy2/jars
:: loading settings :: url = jar:file:/home/spark/spark-2.4.5-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
ai.h2o#sparkling-water-package_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f6da72a7-494f-4e9f-87a8-8a1f57d8b9dc;1.0
	confs: [default]
	found ai.h2o#sparkling-water-package_2.11;3.28.1.2-1-2.4 in central
:: resolution report :: resolve 232ms :: artifacts dl 5ms
	:: modules in use:
	ai.h2o#sparkling-water-package_2.11;3.28.1.2-1-2.4 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-f6da72a7-494f-4e9f-87a8-8a1f57d8b9dc
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/8ms)
20/03/24 18:52:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://10.18.96.152:4040
Spark context available as 'sc' (master = spark://10.18.96.152:7077, app id = app-20200324185239-0004).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.5
      /_/

Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_242)
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```
Then, I follow the tutorial ,Create an H2O cloud inside the Spark cluster:
```
import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate()
import h2oContext._
```
BUT , I got ERROR when `val h2oContext = H2OContext.getOrCreate()`:
```
scala> val h2oContext = H2OContext.getOrCreate()
20/03/24 19:01:09 WARN InternalH2OBackend: To avoid non-deterministic behavior of Spark broadcast-based joins,
we recommend to set `spark.sql.autoBroadcastJoinThreshold` property of SparkSession to -1.
E.g. spark.conf.set("spark.sql.autoBroadcastJoinThreshold", -1)
We also recommend to avoid using broadcast hints in your Spark SQL code.
20/03/24 19:01:09 WARN H2OConf: The method 'clientWebEnabled' is deprecated.  This method will be removed in the release 3.30.
20/03/24 19:01:09 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 0 (Infinitive) as we need to ensure we run on the nodes with H2O
20/03/24 19:01:09 WARN InternalH2OBackend: The property 'spark.scheduler.minRegisteredResourcesRatio' is not specified!
We recommend to pass `--conf spark.scheduler.minRegisteredResourcesRatio=1`
[Stage 0:>                                                        (0 + 20) / 21]20/03/24 19:03:10 ERROR TransportRequestHandler: Error sending result StreamResponse{streamId=/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, byteCount=118726847, body=FileSegmentManagedBuffer{file=/home/spark/.ivy2/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, offset=0, length=118726847}} to /10.18.96.150:53650; closing connection
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
20/03/24 19:03:10 ERROR TransportRequestHandler: Error sending result StreamResponse{streamId=/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, byteCount=118726847, body=FileSegmentManagedBuffer{file=/home/spark/.ivy2/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, offset=0, length=118726847}} to /10.18.96.198:45762; closing connection
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
	at sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:428)
	at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:493)
	at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:605)
	at io.netty.channel.DefaultFileRegion.transferTo(DefaultFileRegion.java:139)
	at org.apache.spark.network.protocol.MessageWithHeader.transferTo(MessageWithHeader.java:121)
	at io.netty.channel.socket.nio.NioSocketChannel.doWriteFileRegion(NioSocketChannel.java:359)
	at io.netty.channel.nio.AbstractNioByteChannel.doWriteInternal(AbstractNioByteChannel.java:235)
	at io.netty.channel.nio.AbstractNioByteChannel.doWrite0(AbstractNioByteChannel.java:209)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:397)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:361)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:694)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
20/03/24 19:03:10 WARN TaskSetManager: Lost task 5.0 in stage 0.0 (TID 5, 10.18.96.150, executor 1): java.nio.channels.ClosedChannelException
	at org.apache.spark.network.client.StreamInterceptor.channelInactive(StreamInterceptor.java:62)
	at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:176)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:913)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

[Stage 0:>                                                        (0 + 20) / 21]
```
8080 port is shown as normal, but 4040 port always shows 'collect at SpreadRDDBuilder.scala:63'

**Comment by jakubhava** [comment]
What is your Spark configuration? Are you using Spark Local/YARN or Standalone mode?

**Comment by AarynBaelish** [comment]
> What is your Spark configuration? Are you using Spark Local/YARN or Standalone mode?

Standalone mode

**Comment by jakubhava** [comment]
I have just tried:

```
"$SPARK_HOME"/sbin/start-master.sh
```, now go to localhost:8080, get the MASTER URL, pass it to the slave:

```

"$SPARK_HOME"/sbin/start-slave.sh spark://Jakubs-MacBook-Pro.local:7077
```

Start SW:
```
$SPARK_HOME/bin/spark-shell --packages ai.h2o:sparkling-water-package_2.11:3.28.1.2-1-2.4
```
Wait until master sees the worker node.

And run
```
import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate()
import h2oContext._
```

It worked fine for me. 

How are you starting your standalone Spark cluster?

**Comment by AarynBaelish** [comment]
I have tested this case( MASTER and N WORKERS in one physical machine ), and it does work as well.  

The ERROR ABOVE happened when I tried to create `h2oContext` upon several physical machines.

 I put IPs of  physical machines into `$SPARK_HOME/conf/slaves` 
and run```"$SPARK_HOME"/sbin/start-slave.sh```

when running `val h2oContext = H2OContext.getOrCreate()`,
TERMINAL shows the ERROR ABOVE.

I have already seen MASTER and N WORKERS on spark website localhost:8080, BUT this time the connections between each SLAVE and MASTER seem like in some trouble.

What I am confused is that I have tested SparkPi successfully under this Spark Cluster, and  the connections between each SLAVE and MASTER all work.

**Comment by jakubhava** [comment]
Do you have some firewal setup on the nodes? H2O needs to have specific ports opened for the communication ( by default 54321 and 54322 on each node)

**Comment by AarynBaelish** [comment]
When I choose `Kluster Mode` use `Manual Mode of External Backend without Hadoop (standalone)` method based on `flatfile.txt` to create my multi physical machine cluster (port 54321 on each machine), everything is ok (not any `connect error` happened) . The firewall seems to be fine.

**Comment by jakubhava** [comment]
Oki, this verifies the communication between H2O nodes works as expected. 

It first fails on 
```
[Stage 0:>                                                        (0 + 20) / 21]20/03/24 19:03:10 ERROR TransportRequestHandler: Error sending result StreamResponse{streamId=/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, byteCount=118726847, body=FileSegmentManagedBuffer{file=/home/spark/.ivy2/jars/ai.h2o_sparkling-water-package_2.11-3.28.1.2-1-2.4.jar, offset=0, length=118726847}} to /10.18.96.150:53650; closing connection
```

Which seems like Spark is failing to upload the jar to worker node.

Can you please Start regular standalone Spark with Sparkling Water jar dependency and not use Sparkling Water? I would like to verify that it is this case.

**Comment by jakubhava** [comment]
Any update @AarynBaelish ?
