### ISSUE TITLE
which xgboost  hex.tree.xgboost._ vs ai.h2o.sparkling.ml.algos.H2OXGBoost

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#2037]
Hi. 
In my job I found that 
ai.h2o.sparkling.ml.algos.H2OXGBoost is so slow and cluster crash but if I use h2o algortithm import hex.tree.xgboost._ works fine. 
The last works with H2OFrames and the first with spark dataframes. Is some reason to use one or other? In my experience algorithm from hex.tree over H2OFrame (sparkdatafrme to h2oframe converts) is better than the other, at least in my case.  My dataset has over 10 million of rows and around 120 columns

**Comment by jakubhava** [comment]
``ai.h2o.sparkling.ml.algos.H2OXGBoost`` is Sparkling Water API and proffered way how to use H2O algorithms in Sparkling Water. In future versions of H2O we are planning to stop supporting using H2O algos directly due to some architectural changes.

If you can please share the shape of your data, reproducible example and what slow means in term of numbers that would be great.

**Comment by joscani** [comment]
ok, Actually, using ai.h2o.sparkling.ml.algos.H2OXGBoost with my data, process not finish. and I have to kill the process.

**Comment by joscani** [comment]
Hi @jakubhava , I'm using sparkling-water last stable 3.30 in aws emr with spark 2.3
Using 
``` bash
bin/sparkling-shell \
--master yarn \
--conf spark.executor.instances=10 \
--conf spark.num.executors=5 \
--conf spark.executor.memory=20g \
--conf spark.driver.memory=2g \
--conf spark.scheduler.maxRegisteredResourcesWaitingTime=1000000 \
--conf spark.ext.h2o.fail.on.unsupported.spark.param=false \
--conf spark.dynamicAllocation.enabled=false \
--conf yarn.nodemanager.vmem-check-enabled=false \
--conf spark.sql.autoBroadcastJoinThreshold=-1 \
--conf spark.executor.memoryOverhead=10g \
--conf spark.locality.wait=30000 \
--conf spark.scheduler.minRegisteredResourcesRatio=1 \
--deploy-mode client
```
and in sparkling shell 
```scala
// import 

import java.net.URI
import java.io.File
import org.apache.spark.h2o._
import org.apache.spark.h2o.H2OConf
val h2OConf = new H2OConf()
val h2oContext = H2OContext.getOrCreate()

//import water.support.ModelSerializationSupport
//import ai.h2o.sparkling.H2OFrame

import org.apache.spark.sql.functions.udf
import org.apache.spark.sql.types.DoubleType
import org.apache.spark.sql.{DataFrame, SparkSession}

import ai.h2o.sparkling.ml.algos.H2OXGBoost
import ai.h2o.sparkling.ml.models.H2OMOJOModel


// read some data 

val raw_piloto = spark.table("rosetta.train_master_tbl").
  filter($"mes_campana" === "202001" ).
  withColumn("target_residencial", when(col("target") === "RESIDENCIAL","1").
  otherwise("0"))

val ignore_columns = Array[String]("target","telefono","telefono_contacto_bbdd","suffixes","flag_venta","flag_manana","flag_tarde","contactabilidad_manana","contactabilidad_tarde")

val featColNames = raw_piloto.columns.diff(ignore_columns)

// versomo seleccionar solo columnas en el modelo, setFeatures o similar
val featCols = featColNames.map(cn => org.apache.spark.sql.functions.col(cn))

val piloto = raw_piloto.select(featCols: _*)
  
val calib_df = spark.table("rosetta.train_master_tbl").
  filter($"mes_campana" === "201911" ).
  withColumn("target_residencial", when(col("target") === "RESIDENCIAL","1").
  otherwise("0"))


val Array(trainingDF, validDF, testingDF) = piloto.randomSplit(Array(0.5, 0.2, 0.3))

val estimator = new H2OXGBoost().
      setLabelCol("target_residencial")
val model = estimator.fit(trainingDF)  
```
And I get errors like that
```shell
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
```
However If I sparkling-shell in the same way but using old way to  xgboost h2o model

```scala

// import 

import java.net.URI
import org.apache.spark.h2o._
import org.apache.spark.h2o.H2OConf
val h2OConf = new H2OConf()
val h2oContext = H2OContext.getOrCreate()

import h2oContext._
import h2oContext.implicits._
import water.support.H2OFrameSupport._
import water.support.ModelSerializationSupport
import ai.h2o.sparkling.H2OFrame

// import ai.h2o.sparkling.ml.algos.H2OXGBoost 
// import ai.h2o.sparkling.ml.algos.H2ODRF

import _root_.hex.tree.gbm.GBM
import _root_.hex.tree.gbm.GBMModel.GBMParameters
import _root_.hex.ModelMetricsSupervised
import _root_.hex.tree.xgboost.XGBoostModel
import _root_.hex.tree.xgboost._
import _root_.hex.tree.xgboost.XGBoostModel.XGBoostParameters

import ai.h2o.sparkling.ml.algos.H2OXGBoost


import water.support.{H2OFrameSupport, SparkContextSupport, ModelMetricsSupport}
import water.support.SparkContextSupport.addFiles
import water.support.H2OFrameSupport._
import org.apache.spark.h2o.H2OFrame
import water.Key


val piloto = spark.table("rosetta.train_master_tbl").
  filter($"mes_campana" === "202001" ).
  withColumn("target_residencial", when(col("target") === "RESIDENCIAL","1").
  otherwise("0"))
  
val calib_df = spark.table("rosetta.train_master_tbl").
  filter($"mes_campana" === "201911" ).
  withColumn("target_residencial", when(col("target") === "RESIDENCIAL","1").
  otherwise("0"))

//val trainFrame: H2OFrame = h2oContext.asH2OFrame(piloto, Some("h2oframe"))
val trainFrame: H2OFrame = h2oContext.asH2OFrame(piloto, Some("h2otrainframe"))
val calibFrame: H2OFrame = h2oContext.asH2OFrame(calib_df, Some("h2ocalibframe"))

// target to categorical
val trainFrame_prep = trainFrame.toCategoricalCol("target_residencial")
val calibFrame_prep = calibFrame.toCategoricalCol("target_residencial")

//H2OFrameSupport.withLockAndUpdate(trainFrame) { fr =>
//        fr.replace(fr.find("target_residencial"), fr.vec("target_residencial").toCategoricalVec).remove()
//}


val keys = Seq[String]("train.hex", "test.hex", "hold.hex")
val ratios = Seq[Double](0.5, 0.3)
val frs = split(trainFrame_prep, keys, ratios)
val (train, test, hold) = (frs(0), frs(1), frs(2))

val ignore_columns = Array[String]("target","telefono","telefono_contacto_bbdd","suffixes","flag_venta","flag_manana","flag_tarde","contactabilidad_manana","contactabilidad_tarde")

val xgbParams = new XGBoostParameters()

//xgbParams._train = train._key
//xgbParams._valid = test._key

xgbParams._train = train
xgbParams._valid = test
xgbParams._calibrate_model = true
xgbParams._calibration_frame = calibFrame_prep

xgbParams._seed = 42
xgbParams._response_column = "target_residencial"
xgbParams._ignored_columns = ignore_columns
xgbParams._ntrees = 10
xgbParams._max_depth = 3

val model = new XGBoost(xgbParams).trainModel().get()

``` 
works fine and smooth 
```bash
val model = new XGBoost(xgbParams).trainModel().get()
model: hex.tree.xgboost.XGBoostModel =
Model Metrics Type: Binomial
 Description: N/A
 model id: XGBoost_model_1587023221301_1
 frame id: h2otrainframe_part0
 MSE: 0.0013275053
 RMSE: 0.03643495
 AUC: 0.651202
 pr_auc: 0.0029946663
 logloss: 0.026357219
 mean_per_class_error: 0.49201643
 default threshold: 0.030152473598718643
 CM: Confusion Matrix (Row labels: Actual class; Column labels: Predicted class):
               0      1   Error                 Rate
     0  13992568  11998  0.0009  11,998 / 14,004,566
     1     11571    198  0.9832      11,571 / 11,769
Totals  14004139  12196  0.0017  23,569 / 14,016,335
Gains/Lift Table (Avg response rate:  0.08 %, avg score:  2.30 %):
  Group  Cumulative Data Fraction  Lower Threshold      Lift  Cumulative Lift  Response Rate   Score  Cum...


```

Thanks in advanced, I try to show you a reproducible example in next days

**Comment by joscani** [comment]
Anyway, when it works I don't find how to download de mojo in a zip file.

**Comment by jakubhava** [comment]
Oki, thank you. Could you please get us also YARN logs? That would definitely help. We are keen to make this API stable.

**Comment by joscani** [comment]
Hi @jakubhava  Its hard to replicate, sometimes works sometimes not. I'll collect yarn logs next time. I'm a fan of your work, h2o had helped me to save a lot of time.

**Comment by joscani** [comment]
Thanks @jakubhava  I'm learning the new ap. My goal is to use sparkling water in a production environment. Where can I find some tutorial about the new api? I need to get summary of model, gainslift table and etc, specify calibration dataframe but I don't find how to get this in new api

**Comment by jakubhava** [comment]
Hi @joscani, we are not getting rid of old api any time soon as we realize there are still a lot of things we need to expose. But eventually we will be using just the following API https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/sw_xgboost.html?highlight=h2oxgboost

Right now you can rain the models, run predictions, extract various information from the mojo model but we are still not exactly future complete.

To get model summary, you can do `model.getModelDetails()` which returns the JSON with full information about the model. We are also trying to improve this and already started working on this.

For example, to get metrics of the trained model, you can call `model.getCurrentMetrics()`, to get training params you can call `model.getTrainingParams` etc.

Currently we do not provide way how to obtain gainlift table in this API -> I will create JIRA for this

Regarding calibration frame -> currently not exposed, but in-progress @mn-mikke is working on a task which will make sure that our new API will have all original arguments exposed ( we will generate this automatically).

Hope this helps. I think it will take us around 2 major releases to do a complete switch to a new API

**Comment by joscani** [comment]
Thanks @jakubhava
