### ISSUE TITLE
Error while initiating H2OConnect in Databricks

### ISSUE THREAD

**Issue by DarthSimian** [h2oai/sparkling-water#2044]
I am getting the below error while trying to initiate PySparkiling in a Databricks cluster.
The cluster is a Spark 2.4.5, Scala 2.11 environment and is not a ML cluster
Also, I tried turning off Autoscaling and that didn't help either

```
from pysparkling import *
from pyspark.sql import SparkSession
import h2o

spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()

h2oConf = H2OConf(spark).set("spark.ui.enabled", "false").set('spark.dynamicAllocation', 'false')
hc = H2OContext.getOrCreate(spark, conf=h2oConf)

```

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-418156289286121> in <module>
      4 spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
      5 h2oConf = H2OConf(spark).set("spark.ui.enabled", "false").set('spark.dynamicAllocation', 'false')
----> 6 hc = H2OContext.getOrCreate(spark, conf=h2oConf)
      7 #spark.conf.get("spark.databricks.clusterUsageTags.sparkVersion")
      8 

/databricks/python/lib/python3.7/site-packages/ai/h2o/sparkling/H2OContext.py in getOrCreate(spark, conf)
     97         package = getattr(_jvm().org.apache.spark.h2o, "H2OContext$")
     98         module = package.__getattr__("MODULE$")
---> 99         jhc = module.getOrCreate(selected_conf._jconf)
    100         h2o_context._jhc = jhc
    101         h2o_context._conf = selected_conf

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o265.getOrCreate.
: java.lang.NoClassDefFoundError: org/spark_project/jetty/util/thread/ThreadPool
	at org.apache.spark.h2o.H2OContext.<init>(H2OContext.scala:98)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.spark_project.jetty.util.thread.ThreadPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 13 more

**Comment by jakubhava** [comment]
@DarthSimian Thanks for report. This is a known issue on the latest version and is already fixed on the master. The fix will be in the release 3.30.0.2 next week. In the meanwhile, please use 3.28.1.3
