### ISSUE TITLE
Cannot create H2OContext in Azure Databricks cluster

### ISSUE THREAD

**Issue by memoryz** [h2oai/sparkling-water#2230]
- Sparkling Water version: ai.h2o:sparkling-water-package_2.11:3.30.0.6-1-2.4
- Hadoop Version & Distribution: Azure Databricks runtime 6.6 (Spark 2.4.5, Scala 2.11)

```scala
import org.apache.spark.h2o._
val hc = H2OContext.getOrCreate()
```

Error:
![image](https://user-images.githubusercontent.com/6992432/87733033-60638700-c783-11ea-9eb1-ccc0cfdbc13d.png)

I also tried to change to a different random port by modifying spark.ext.h2o.client.web.port, but getting the same error:

![image](https://user-images.githubusercontent.com/6992432/87732565-3362a480-c782-11ea-8561-61fdf0748c00.png)

**Comment by jakubhava** [comment]
Hi @memoryz , can you please try again without specifying the port in your configuration? Sparkling Water chooses the free port automatically on Azure DBC ( should be 9009). Specifically, please remove ``spark.ext.h2o.client.web.port`` from your configuration.

Thanks!

**Comment by memoryz** [comment]
Hi @jakubhava , I tried both specifying the port and not specifying the port. Neither works. 

If I **DO NOT** specify port, I get the error: 
java.lang.RuntimeException: Explicitly specified client web port 9909 is already occupied, please specify a free port!

If I do specify a random port, I get the error:
java.lang.RuntimeException: Explicitly specified client web port [port I choose] is already occupied, please specify a free port!

**Comment by jakubhava** [comment]
Oki, thank you! I will have a look, please use this JIRA to track the problem https://0xdata.atlassian.net/browse/SW-2366

**Comment by VictorBizone** [comment]
I was running into the same issue today. Are you using a single node cluster? Once I turned my cluster into a standard version the issue went away.

**Comment by memoryz** [comment]
> I was running into the same issue today. Are you using a single node cluster? Once I turned my cluster into a standard version the issue went away.

I just created a cluster with 1 driver and 1 worker, and reproduced the error. Here is my cluster config:
```json
{
    "num_workers": 1,
    "cluster_name": "sparkingwatertest",
    "spark_version": "6.4.x-scala2.11",
    "spark_conf": {
        "spark.databricks.delta.preview.enabled": "true"
    },
    "node_type_id": "Standard_DS3_v2",
    "driver_node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {},
    "spark_env_vars": {},
    "autotermination_minutes": 30,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [],
    "cluster_id": "0203-201051-aloft577"
}
```
Sparkling Water version: `ai.h2o:sparkling-water-package_2.11:3.30.0.6-1-2.4`

Code:
```scala
import org.apache.spark.h2o._
val hc = H2OContext.getOrCreate()
```

Error:
```
java.lang.RuntimeException: Explicitly specified client web port 9009 is already occupied, please specify a free port!
	at ai.h2o.sparkling.backend.utils.ProxyStarter$.findNextFreeFlowPort(ProxyStarter.scala:129)
	at ai.h2o.sparkling.backend.utils.ProxyStarter$.startFlowProxy(ProxyStarter.scala:41)
	at org.apache.spark.h2o.H2OContext.<init>(H2OContext.scala:99)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:483)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:521)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1023181963589389:3)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1023181963589389:46)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw$$iw$$iw$$iw.<init>(command-1023181963589389:48)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw$$iw$$iw.<init>(command-1023181963589389:50)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw$$iw.<init>(command-1023181963589389:52)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$$iw.<init>(command-1023181963589389:54)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read.<init>(command-1023181963589389:56)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$.<init>(command-1023181963589389:60)
	at line5e85a52057b64b06be0dd33d558c8eca25.$read$.<clinit>(command-1023181963589389)
	at line5e85a52057b64b06be0dd33d558c8eca25.$eval$.$print$lzycompute(<notebook>:7)
	at line5e85a52057b64b06be0dd33d558c8eca25.$eval$.$print(<notebook>:6)
	at line5e85a52057b64b06be0dd33d558c8eca25.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:714)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:667)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:396)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:373)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:275)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:373)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kaleex** [comment]
Hi, im currently going through this error, is any workaround to this date?

**Comment by mn-mikke** [comment]
@kaleex I looked into this problem some time ago, but I couldn't reproduce it. Can you share the version of your Databricks runtime and the spark properties that you have in your config?

**Comment by krasinski** [comment]
@kaleex after some investigation I noticed that the issue happens probably only in the singleNode mode which is effectively a local mode running on Azure - further investigation is in progress but in the meantime a workaround would be to use a "real" cluster with some worker nodes
