### ISSUE TITLE
External backend - auto mode: failed to start 

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2262]
Trying to launch Sparkling water H2OContext with **External backend - auto mode**, but getting following error:

```
Py4JJavaError: An error occurred while calling o180.getOrCreate.
: java.lang.RuntimeException: 
Cluster notification file /home/jnovotny/notify_prd_ml.h2o_server could not be created. The possible causes are:

1) External H2O cluster did not cloud within the pre-defined timeout. In that case, please try
   to increase the timeout for starting the external cluster as:

   H2OContext.getOrCrete(H2OConf().setClusterStartTimeout(timeout))

2) The file could not be created because of missing write rights.
	at ai.h2o.sparkling.backend.external.ExternalH2OBackend.launchExternalH2OOnYarn(ExternalH2OBackend.scala:69)
	at ai.h2o.sparkling.backend.external.ExternalH2OBackend.startH2OCluster(ExternalH2OBackend.scala:37)
	at org.apache.spark.h2o.H2OContext.<init>(H2OContext.scala:85)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:509)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

During start I can see in YARN applications that External backend MapReduce job is launched but then after 180s (timeout duration) this job is terminated and original SparkSession gets error provided above.

There was no problem to start H2OContext with Internal backend.

_Running PySparkling (3.30.0.7-1-2.4) on YARN._

**Comment by jakubhava** [comment]
@dataspekulant could you please share the YARN logs of the external H2O cluster?

**Comment by dataspekulant** [comment]
Sending you logs from H2O external backend app:

```
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: Cannot initialize XGBoost backend! Xgboost (enabled GPUs) needs: 
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO:   - CUDA 8.0
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: XGboost (minimal version) needs: 
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO:   - GCC 4.7+
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: For more details, run in debug mode: `java -Dlog4j.configuration=file:///tmp/log4j.properties -jar h2o.jar`
07-28 14:02:38.569 127.0.0.1:54321       18034  main      INFO: ----- H2O started  -----
07-28 14:02:38.569 127.0.0.1:54321       18034  main      INFO: Build git branch: rel-zahradnik
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build git hash: 42bc323d9860bac8b25e904eec22b9cf827abcb5
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build git describe: jenkins-3.30.0.6-24-g42bc323
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build project version: 3.30.0.7
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build age: 6 days
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Built by: 'jenkins'
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Built on: '2020-07-21 17:20:25'
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Found H2O Core extensions: [HiveTableImporter, StackTraceCollector]
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: Processed H2O arguments: [-ice_root, /application_1593260267304_117324/container_1593260267304_117324_01_000003/tmp, -hdfs_skip, -name, h2o, -baseport, 54321, -port_offset, 1, -ga_hadoop_ver, Hadoop 2.6.0-cdh5.13.0, -user_name, jnovotny, -log_level, INFO, -rest_api_ping_timeout, 60000]
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: Java availableProcessors: 24
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: Java heap totalMemory: 7.67 GB
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: Java heap maxMemory: 7.67 GB
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: Java version: Java 1.8.0_131 (from Oracle Corporation)
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: JVM launch parameters: [-Djava.net.preferIPv4Stack=true, -Dhadoop.metrics.log.level=WARN, -Xms8G, -Xmx8G, -verbose:gc, -XX:+PrintGCDetails, -XX:+PrintGCTimeStamps, -Dlog4j.defaultInitOverride=true, -Djava.io.tmpdir=/data5/yarn/nm/usercache/jnovotny/appcache/application_1593260267304_117324/container_1593260267304_117324_01_000003/tmp, -Dlog4j.configuration=container-log4j.properties, -Dyarn.app.container.log.dir=/var/log/cloudera/hadoop-yarn/container/application_1593260267304_117324/container_1593260267304_117324_01_000003, -Dyarn.app.container.log.filesize=0, -Dhadoop.root.logger=INFO,CLA, -Dhadoop.root.logfile=syslog]
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: JVM process id: 18034@hadoop
07-28 14:02:38.571 127.0.0.1:54321       18034  main      INFO: OS version: Linux 2.6.32-504.23.4.el6.x86_64 (amd64)
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Machine physical memory: 188.78 GB
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Machine locale: en_US
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: X-h2o-cluster-id: 1595937694476
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: User name: 'jnovotny'
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: IPv6 stack selected: false
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Possible IP Address: bond0 (bond0), 101.154.99.111
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Possible IP Address: bond1 (bond1), 17.25.22.218
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Possible IP Address: bond2 (bond2), 101.147.52.10
07-28 14:02:38.572 127.0.0.1:54321       18034  main      INFO: Possible IP Address: lo (lo), 127.0.0.1
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Multiple local IPs detected:
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO:   /101.154.99.111  /17.25.22.218  /101.147.52.10
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Attempting to determine correct address...
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Failed to determine IP, falling back to localhost.
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Selected H2O.CLOUD_MULTICAST_IF: name:lo (lo) doesn't support multicast
07-28 14:02:38.586 127.0.0.1:54321       18034  main      INFO: H2O node running in unencrypted mode.
07-28 14:02:38.589 127.0.0.1:54321       18034  main      INFO: Internal communication uses port: 54322
07-28 14:02:38.589 127.0.0.1:54321       18034  main      INFO: Listening for HTTP and REST traffic on http://127.0.0.1:54321/
```

**Comment by jakubhava** [comment]
Not sure if this is the possible error, but definitely interesting:

07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Multiple local IPs detected:
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO:   /101.154.99.111  /17.25.22.218  /101.147.52.10
07-28 14:02:38.573 127.0.0.1:54321       18034  main      INFO: Attempting to determine correct address...

Can you specify this Spark option `spark.ext.h2o.node.network.mask` to the network on which you would like to run your external H2O backend? The format is `spark.ext.h2o.node.network.mask=10.10.1.0/24`

**Comment by dataspekulant** [comment]
This helped! Thank you 👍
