### ISSUE TITLE
H20 XGBOOST Out of Memory

### ISSUE THREAD

**Issue by vinhdiesal** [h2oai/sparkling-water#2267]
I'm getting errors when running an `H2O XGBOOST` training session on a Spark Cluster. 
My spark 3.0 cluster is as followings: 
3 machines with GPUs allocated 7 GB per executor. 
I have a 2 GB file which I want to train,my code is as follows using pysparkling: 
```
from pysparkling import *
import h2o
hc = H2OContext.getOrCreate()
%%time
import h2o
file = "nyc-taxi_csv_2014_yellow_tripdata_2014-01.csv"
frame = h2o.import_file(file)
sparkDF = hc.asSparkFrame(frame)
sparkDF.show()
sparkDF = sparkDF.withColumn("total_amount", sparkDF.total_amount.cast("string"))
[trainingDF, testingDF] = sparkDF.randomSplit([0.8, 0.2])
%%time
from pysparkling.ml import H2OXGBoost
estimator = H2OXGBoost(labelCol = "total_amount")
model = estimator.fit(trainingDF)
```
I get the following errors when I run the `estimator.fit`:
```
Py4JJavaError: An error occurred while calling o92.fit.
: java.lang.Exception: H2O Job $0301c0a8016d32d4ffffffff$_9f503a0c6fbabbccdcbbbcea8dc74ccb has failed!
Exception: DistributedException from vinhdiesal-imac/192.168.1.109:54321: 'Java heap space', caused by java.lang.OutOfMemoryError: Java heap space
StackTrace: DistributedException from vinhdiesal-imac/192.168.1.109:54321: 'Java heap space', caused by java.lang.OutOfMemoryError: Java heap space
	at water.MRTask.getResult(MRTask.java:494)
	at water.MRTask.getResult(MRTask.java:502)
	at water.MRTask.doAll(MRTask.java:397)
	at water.MRTask.doAll(MRTask.java:393)
	at hex.tree.xgboost.predict.XGBoostModelMetrics.runScoreTask(XGBoostModelMetrics.java:64)
	at hex.tree.xgboost.predict.XGBoostModelMetrics.compute(XGBoostModelMetrics.java:46)
	at hex.tree.xgboost.XGBoostModel.makeMetrics(XGBoostModel.java:504)
	at hex.tree.xgboost.XGBoostModel.doScoring(XGBoostModel.java:514)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.doScoring(XGBoost.java:624)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.scoreAndBuildTrees(XGBoost.java:459)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.buildModelImpl(XGBoost.java:390)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.buildModel(XGBoost.java:337)
	at hex.tree.xgboost.XGBoost$XGBoostDriver.computeImpl(XGBoost.java:327)
	at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:252)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1557)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at biz.k11i.xgboost.gbm.GBTree.predict(GBTree.java:59)
	at biz.k11i.xgboost.Predictor.predictRaw(Predictor.java:198)
	at biz.k11i.xgboost.Predictor.predict(Predictor.java:190)
	at biz.k11i.xgboost.Predictor.predict(Predictor.java:153)
	at biz.k11i.xgboost.Predictor.predict(Predictor.java:142)
	at hex.tree.xgboost.predict.XGBoostJavaBigScoreChunkPredict.predict(XGBoostJavaBigScoreChunkPredict.java:67)
	at ml.dmlc.xgboost4j.java.XGBoostScoreTask.map(XGBoostScoreTask.java:73)
	at water.MRTask.compute2(MRTask.java:675)
	at water.MRTask.compute2(MRTask.java:607)
	at water.H2O$H2OCountedCompleter.compute1(H2O.java:1560)
	at ml.dmlc.xgboost4j.java.XGBoostScoreTask$Icer.compute1(XGBoostScoreTask$Icer.java)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1556)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.popAndExecAll(ForkJoinPool.java:904)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:977)
	... 2 more

	at ai.h2o.sparkling.backend.H2OJob.waitForFinish(H2OJob.scala:39)
	at ai.h2o.sparkling.ml.utils.EstimatorCommonUtils.trainAndGetDestinationKey(EstimatorCommonUtils.scala:39)
	at ai.h2o.sparkling.ml.utils.EstimatorCommonUtils.trainAndGetDestinationKey$(EstimatorCommonUtils.scala:25)
	at ai.h2o.sparkling.ml.algos.H2OAlgorithm.trainAndGetDestinationKey(H2OAlgorithm.scala:38)
	at ai.h2o.sparkling.ml.algos.H2OAlgorithm.fit(H2OAlgorithm.scala:58)
	at ai.h2o.sparkling.ml.algos.H2OSupervisedAlgorithm.fit(H2OSupervisedAlgorithm.scala:62)
	at ai.h2o.sparkling.ml.algos.H2OTreeBasedSupervisedAlgorithm.fit(H2OTreeBasedSupervisedAlgorithm.scala:32)
	at ai.h2o.sparkling.ml.algos.H2OTreeBasedSupervisedAlgorithm.fit(H2OTreeBasedSupervisedAlgorithm.scala:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
I don't understand why there's memory issues when I have 7 GB per executor allocated. The file is only 2GB. 

Please help, 

Thanks,

**Comment by mn-mikke** [comment]
Hi @vinhdiesal,
Since the core logic of the `XGBoost` algorithm is written as C/C++ library. This algorithm utilizes mainly off-heap memory of H2O-3 cluster. If you're running Sparkling Water in internal backend, try to significantly increase the following Spark properties:
```
spark.driver.memoryOverhead
spark.executor.memoryOverhead
```

Generally, for model training with H2O XGboost, we recommend to set off-heap to 50% of the total memory utilized by JVM process.

Let us know, if it helps.

Regards,
Marek

**Comment by vinhdiesal** [comment]
Hi @mn-mikke , 

I modified the `spark-defaults.conf` as suggested with `.memoryOvehead` set to 4GB, but it results in the same heap space error when I run the `.fit`

```
spark.ui.prometheus.enabled        true
spark.executor.processTreeMetrics.enabled  true
spark.rapids.sql.concurrentGpuTasks             1
spark.rapids.memory.pinnedPool.size            2G
spark.locality.wait                             0s
spark.executor.cores                             4
spark.task.cpus                                  1
spark.sql.files.maxPartitionBytes              512m
spark.sql.shuffle.partitions                    10
spark.driver.memoryOverhead                     4G
spark.executor.memoryOverhead                   4G
spark.task.resource.gpu.amount                  0.25
spark.executor.resource.gpu.discoveryScript    ./usr/local/spark/getGpusResources.sh
spark.executor.resource.gpu.amount              1
spark.worker.resource.gpu.amount                1
spark.worker.resource.gpu.discoveryScript      /usr/local/spark/getGpusResources.sh
spark.jars                                     /Users/vinhdiesal/Downloads/postgresql-42.2.14.jar
spark.executor.memory                           7g
#spark.python.worker.memory                      10g
spark.executor.extraClassPath                   /usr/local/spark/cudf-0.14-cuda10-2.jar,/usr/local/spark/rapids-4-spark_2.12-0.1.0.jar
spark.plugins                                   com.nvidia.spark.SQLPlugin
```

**Comment by mn-mikke** [comment]
cc @honzasterba Do you have an idea how much on-heap and off-heap memory the XGBoost algorithm will require for the model training  on 2GB CSV dataset?

**Comment by mn-mikke** [comment]
>file = "nyc-taxi_csv_2014_yellow_tripdata_2014-01.csv"
frame = h2o.import_file(file)
sparkDF = hc.asSparkFrame(frame)

@vinhdiesal Can you try to load the dataframe via Spark?

**Comment by honzasterba** [comment]
I dont think this is related to xgb off-heap memory. You would have seen a different error.
I would suggest trying to run with more memory available.

**Comment by vinhdiesal** [comment]
I performed two test cases: 

First test cases: Increase executor memory to `9G` with loading dataframe via H20 results in the same heap space error. 

Second test case: Increase executor memory to `9G`with load dataframe via `spark.read.csv()` results in the same heap space error. 

Which spark parameter should I change in order to increase the memory?

**Comment by mn-mikke** [comment]
`spark.executor.memory` is the option that you're looking for. Btw, how much memory is assigned to your driver `spark.driver.memory`?

**Comment by mn-mikke** [comment]
Also what version of Sparkling Water do you run?

**Comment by vinhdiesal** [comment]
`spark.driver.memory` is configured for 35 GB. 
I'm running `pysparkling` from the `Sparkling water for 3.0` binary release package from GITHUB,

**Comment by mn-mikke** [comment]
Is the SW version `3.30.0.7-1-3.0` or something `3.x.y.z-1-3.0` older?

**Comment by mn-mikke** [comment]
Do you experience this only with XGBoost? Have you tried to train a different algorithm? `GBM` for instance?

**Comment by mn-mikke** [comment]
Hi @vinhdiesal,
Do you still need any help? Or can we close this ticket?

**Comment by vinhdiesal** [comment]
Hi @mn-mikke Thanks very much for your help, I will close this issue.
