### ISSUE TITLE
Install fails with PySparkling + Spark 2.1

### ISSUE THREAD

**Issue by szxunchao** [h2oai/sparkling-water#230]
```
Collecting h2o_pysparkling_2.1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading h2o_pysparkling_2.1-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Z8uyPF/h2o-pysparkling-2.1/setup.py", line 13, in <module>
        with open(path.join(here, 'build', 'version.txt'), encoding='utf-8') as f:
      File "/usr/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Z8uyPF/h2o-pysparkling-2.1/build/version.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Z8uyPF/h2o-pysparkling-2.1/
```

**Comment by mmalohlava** [comment]
@szxunchao thank you for bug report! We have already fix here: https://github.com/h2oai/sparkling-water/pull/195 - it will be part of the next release.

However, in meantime please use binary distribution of Sparkling Water

**Comment by szxunchao** [comment]
Thanks!

**Comment by jakubhava** [comment]
@szxunchao The fix will go into the 2.1.5 release. Please use this JIRA number to track the issue https://0xdata.atlassian.net/browse/SW-335

**Comment by toddpi314** [comment]
FYI, Spark 2.0 is afflicted by the same issue with PySparkling.

**Comment by mmalohlava** [comment]
In mean time, i would recommend to use binary download of Sparkling Water from h2o.ai/download.

**Comment by toddpi314** [comment]
Hoping eventually to not have to manually build for Py3. I have yet to see a release targeting 3 that works through pip.

**Comment by mmalohlava** [comment]
@toddpi314 the change is already in master, will be part of next release the following week.
