### ISSUE TITLE
Spark 3.0 using  h2o-pysparkling-3.0 3.30.1.2-1 : java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by anayyar82** [h2oai/sparkling-water#2326]
Hello , While running h2o-pysparkling-3.0 3.30.1.2-1 using Spark 3.0, We are getting below error. 

20/09/21 20:06:50 INFO RestApiUtils: H2O node http://10.139.64.83:54321/3/Ping successfully responded for the GET.

20/09/21 20:06:50 WARN HttpChannel: /sparkling-water/

java.lang.NoSuchMethodError: org.apache.spark.ui.UIUtils$.headerSparkPage(Ljavax/servlet/http/HttpServletRequest;Ljava/lang/String;Lscala/Function0;Lorg/apache/spark/ui/SparkUITab;Lscala/Option;ZZ)Lscala/collection/Seq;

               at org.apache.spark.h2o.SparkSpecificUtils$.headerSparkPage(SparkSpecificUtils.scala:35)

               at org.apache.spark.h2o.ui.SparklingWaterInfoPage.render(SparklingWaterInfoPage.scala:107)

               at org.apache.spark.ui.WebUI.$anonfun$attachPage$1(WebUI.scala:105)

               at org.apache.spark.ui.JettyUtils$$anon$1.doGet(JettyUtils.scala:80)

               at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

               at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

               at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)

               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)

               at org.apache.spark.ui.HttpSecurityFilter.doFilter(HttpSecurityFilter.scala:95)

               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)

               at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)

               at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)

               at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

               at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)

               at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)

               at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)

               at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)

               at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

               at org.eclipse.jetty.server.Server.handle(Server.java:505)

               at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)

               at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)

               at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)

               at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

               at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)

               at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)

               at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)

               at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)

               at java.lang.Thread.run(Thread.java:748)

20/09/21 20:06:55 WARN HttpChannel: /sparkling-water/

java.lang.NoSuchMethodError: org.apache.spark.ui.UIUtils$.headerSparkPage(Ljavax/servlet/http/HttpServletRequest;Ljava/lang/String;Lscala/Function0;Lorg/apache/spark/ui/SparkUITab;Lscala/Option;ZZ)Lscala/collection/Seq;

               at org.apache.spark.h2o.SparkSpecificUtils$.headerSparkPage(SparkSpecificUtils.scala:35)

               at org.apache.spark.h2o.ui.SparklingWaterInfoPage.render(SparklingWaterInfoPage.scala:107)

               at org.apache.spark.ui.WebUI.$anonfun$attachPage$1(WebUI.scala:105)

               at org.apache.spark.ui.JettyUtils$$anon$1.doGet(JettyUtils.scala:80)

               at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

               at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

               at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)

               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)

               at org.apache.spark.ui.HttpSecurityFilter.doFilter(HttpSecurityFilter.scala:95)

               at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)

               at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)

               at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)

               at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)

               at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

               at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)

               at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)

               at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)

               at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)

               at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

               at org.eclipse.jetty.server.Server.handle(Server.java:505)

               at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)

               at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)

               at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)

               at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

               at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)

               at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)

               at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)

               at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)

               at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)

               at java.lang.Thread.run(Thread.java:748)

**Comment by mn-mikke** [comment]
@anayyar82 What is your Spark distribution? Hortenworks, Cloudera, Databricks?

**Comment by mn-mikke** [comment]
@anayyar82 Can share more details about your spark distribution?

**Comment by mn-mikke** [comment]
This problem will be fixed in `3.32.0.3-1` for Databricks deployments by https://h2oai.atlassian.net/browse/SW-2496.
