### ISSUE TITLE
rsparkling `H2OConf()` fails in Azure Databricks cluster using R notebook and RStudio

### ISSUE THREAD

**Issue by josephd000** [h2oai/sparkling-water#2508]
# Main error

Classpath problems?

`Error : java.lang.ClassNotFoundException: ai.h2o.sparkling.H2OConf`

### Documentation error (I guess)

I think this documentation shows an old way of doing things?

`Error in h2o_context(sc) : could not find function "h2o_context" `: following instructions here, http://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/deployment/rsparkling_azure_dbc.html

# Expectation

Using R Notebooks and/or RStudio on Azure Databricks runtime >= 7.6, I can connect to H2O cluster and thus use H2O.

# Config

## Versions

- sparklyr: 1.6.2 (or 1.5.2)
- RSparkling version: 3.32.1.1-1-3.0 (or 3.32.0.5-1-3.0)
- H2O: 3.32.1.1 (zipf) (or 3.32.0.5)
- Hadoop: 2.7 (or 3.2)
- Databricks cluster (Linux): 7.6 ML (includes Apache Spark 3.0.1, Scala 2.12) with "Standard_F4s" driver (single node; and 1 driver + 1 worker)
  - R Notebook
  - RStudio

### R Notebook 1 & 2

```
sparklyr::spark_config()
$sparklyr.cancellable
[1] FALSE

$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$sparklyr.connect.csv.embedded
[1] "^1.*"

$spark.sql.legacy.utcTimestampFunc.enabled
[1] TRUE

$sparklyr.connect.cores.local
[1] 4

$spark.sql.shuffle.partitions.local
[1] 4
```

### RStudio

```
sparklyr::spark_config()
$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$sparklyr.connect.csv.embedded
[1] "^1.*"

$spark.sql.legacy.utcTimestampFunc.enabled
[1] TRUE

$sparklyr.connect.cores.local
[1] 4

$spark.sql.shuffle.partitions.local
[1] 4

attr(,"config")
[1] "default"
attr(,"file")
[1] "/databricks/spark/R/lib/sparklyr/conf/config-template.yml"
```

### Other attempts

I also tried the above Spark config plus (just hoping to find the right path):

```
conf <- sparklyr::spark_config()
conf$`sparklyr.shell.jars` <- c("/databricks/spark/R/lib/h2o/java/h2o.jar", "/databricks/spark/R/lib/rsparkling/java/sparkling_water_assembly.jar") 
conf$`sparklyr.shell.driver-class-path` <- c("/databricks/spark/R/lib/h2o/java/h2o.jar", "/databricks/spark/R/lib/rsparkling/java/sparkling_water_assembly.jar")
sc <- sparklyr::spark_connect(method = "databricks", config = conf, jars = c("/databricks/spark/R/lib/h2o/java/h2o.jar", "/databricks/spark/R/lib/rsparkling/java/sparkling_water_assembly.jar")) 
```

Also tried (I don't use this in my Docker containers that successfully use rsparkling but thought I'd take a stab in case this helped):

```
options(rsparkling.sparklingwater.version = "2.3.11")
 # and
options(rsparkling.sparklingwater.version = "3.0.1")
sc <- spark_connect(method = "databricks")
```

## H2O Rsparkling instructions tried

- http://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/deployment/rsparkling_azure_dbc.html
  - Seems out of date with change to 3.32:
> We have created two new classes - ai.h2o.sparkling.H2OContext and ai.h2o.sparkling.H2OConf. The behaviour of the context and configuration is the same as in the original org.apache.spark.h2o package except that in this case we no longer use H2O client on Spark driver. (https://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/migration_guide.html)
- https://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/rsparkling.html

# Please also provide us with the full and minimal reproducible code.

## R Notebook 1 (`h2o_context(sc)`)

Following instructions here: https://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/deployment/rsparkling_azure_dbc.html

```
# Install Sparklyr
install.packages("sparklyr")

### needed to install RCurl prior to H2O
install.packages("RCurl")

# Install H2O 3.32.1.1 (zipf)
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-zipf/1/R")

# Install RSparkling 3.32.1.1-1-3.0
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.0/3.32.1.1-1-3.0/R")

# Connect to Spark on Databricks
library(rsparkling)
library(sparklyr)
sc <- spark_connect(method = "databricks")

# Start H2O context
h2o_context(sc)

##### Error in h2o_context(sc) : could not find function "h2o_context" 
```

## R Notebook 2 (`h2oConf <- H2OConf()`)

Following  instructions here: https://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/rsparkling.html

```
install.packages("sparklyr")
library(sparklyr)
spark_install(version = "3.0.2")

Sys.setenv(SPARK_HOME="/databricks/spark")
### also tried Sys.setenv(SPARK_HOME="/root/spark"), same error

# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# Install packages H2O depends on
pkgs <- c("methods", "statmod", "stats", "graphics", "RCurl", "jsonlite", "tools", "utils")
for (pkg in pkgs) {
    if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}

# Download, install, and initialize the H2O package for R.
# In this case we are using rel-zipf 1 (3.32.1.1)
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-zipf/1/R")

# Download, install, and initialize the RSparkling
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.0/3.32.1.1-1-3.0/R")

library(rsparkling)
sc <- spark_connect(method = "databricks")

h2oConf <- H2OConf()

##### Error : java.lang.ClassNotFoundException: ai.h2o.sparkling.H2OConf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:106)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

## RStudio (`h2oConf <- H2OConf()`)

```
library(sparklyr)
spark_install(version = "3.0.2")
Sys.setenv(SPARK_HOME = "~/spark/spark-3.0.2-bin-hadoop3.2")

# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# Install packages H2O depends on
pkgs <- c("methods", "statmod", "stats", "graphics", "RCurl", "jsonlite", "tools", "utils")
for (pkg in pkgs) {
    if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}

# In this case we are using rel-zipf 1 (3.32.1.1)
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-zipf/1/R")

# Download, install, and initialize the RSparkling
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.0/3.32.1.1-1-3.0/R")

SparkR::sparkR.session()
library(rsparkling)
sc <- spark_connect(method = "databricks")

h2oConf <- H2OConf()

##### Error: java.lang.ClassNotFoundException: ai.h2o.sparkling.H2OConf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:106)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mn-mikke** [comment]
Hi @josephd000,
We already experienced a problem with running RSparkling on top of Databricks Runtime, [here](https://h2oai.atlassian.net/jira/software/c/projects/SW/issues/SW-2516?jql=project%20%3D%20%22SW%22%20AND%20reporter%20%3D%20%225dc4f5bbb6e6b50c58af0624%22%20ORDER%20BY%20created%20DESC) is a Jira ticket that describes a work around solution.

IMHO, You need to add SW package jar to libraries of Databricks cluster manually.

**Comment by josephd000** [comment]
**Thank you, @mn-mikke !!!** I needed to install a "[Library][1]" to my Databricks workspace, cluster, or job. I could either upload it or just have Databricks fetch it from Maven coordinates.

In Databricks Workspace:

 1. click Home icon
 1. click "Shared" > "Create" > "Library"
 1. click "Maven" (as "Library Source")
 1. click "Search packages" link next to "Coordinates" box
 1. click dropdown box and choose "Maven Central"
 1. enter `ai.h2o.sparkling-water-package` into the "Query" box
 1. choose recent "Artifact Id" with "Release" that matches your `rsparkling` version, for me `ai.h2o:sparkling-water-package_2.12:3.32.0.5-1-3.0`
 1. click "Select" under "Options"
 1. click "Create" to create the Library
     - thankfully, this required no changes to my Databricks R Notebook when run as a Databricks job

```
# install specific R packages
install.packages(c("httr", "xml2"))

# sparklyr and Spark
install.packages(c("sparklyr"))

# h2o
# RSparkling 3.32.0.5-1-3.0 requires H2O of version 3.32.0.5.
install.packages(c("statmod", "RCurl"))
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-zermelo/5/R")

# rsparkling
# RSparkling 3.32.0.5-1-3.0 is built for 3.0.
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.0/3.32.0.5-1-3.0/R")
# connect to H2O cluster with Sparkling Water context

library(sparklyr)
sparklyr::spark_install("3.0.1", hadoop_version = "3.2")
Sys.setenv(SPARK_HOME = "~/spark/spark-3.0.1-bin-hadoop3.2")
sparklyr::spark_default_version()
library(rsparkling)
 
SparkR::sparkR.session()
sc <- sparklyr::spark_connect(method = "databricks", version = "3.0.1")
sparklyr::spark_version(sc)

# next command will not work without adding https://mvnrepository.com/artifact/ai.h2o/sparkling-water-package_2.12/3.32.0.5-1-3.0 file as "Library" to Databricks cluster
h2oConf <- H2OConf()
hc <- H2OContext.getOrCreate(h2oConf)
```

  [1]: https://docs.microsoft.com/en-us/azure/databricks/libraries/

**Comment by mn-mikke** [comment]
Hi @josephd000,
can we close this issue if there is already [a JIRA ticket](https://h2oai.atlassian.net/browse/SW-2516) for it? Or have you experienced more problems? Is anything missing in the Jira ticket?

**Comment by josephd000** [comment]
@mn-mikke , We can close this issue. Thank you again! 👍 

For JIRA ticket:
-  To connect R to an H2O cluster using RStudio "App" (**but not R Notebook**) on Azure Databricks cluster (7.6 ML, 1 driver, 2 workers), one also needs to run `SparkR::sparkR.session()` before `sparklyr::spark_connect()` in order to avoid the following error:
> Error in value[[3L]](cond) : Failed to start sparklyr backend: No connection to backend found. Please re-run sparkR.session()

**Comment by josephd000** [comment]
# Another scenario, same error

Apologies for reopening this, it turns out that there is another very similar scenario that brings up the error:
> Error: java.lang.ClassNotFoundException: ai.h2o.sparkling.H2OConf

The scenario is: using "Databricks Connect" from my local Docker container to connect to Azure Databricks 7.3 LTS ML (1 worker, 1 node) _with the sparkling-water-package_2.12-3.32.0.5-1-3.0.jar installed as a Databricks workspace Library_ (following https://docs.microsoft.com/en-us/azure/databricks/dev-tools/databricks-connect for _sparklyr_). Sparkling Water works locally in this container and remotely on Databricks but not when combining the two with Databricks Connect.

- Note that it appears, perhaps incorrectly, that Databricks Connect sends Spark work to the remote Databricks cluster for execution while Sparkling Water does not hitch a ride on that remote connection. Instead, H2O is executed on the local machine (where H2O interfaces with the local Spark context) but I was nonetheless able to convert from Spark DataFrames to H2O Frames.

# Solution

To make this work from Databricks Connect, one can download the appropriate .jar and point to it in `sparklyr::spark_connect()`. e.g., `jars = "~/DataAnalysis/ExtLibraries/sparkling-water-package_2.12-3.32.0.5-1-3.0.jar"`:

```
sc <- sparklyr::spark_connect(
  method = "databricks", 
  spark_home = "/miniconda3/envs/databricksconnect/lib/python3.7/site-packages/pyspark",
  jars = "~/DataAnalysis/ExtLibraries/sparkling-water-package_2.12-3.32.0.5-1-3.0.jar")

iris_tbl <- sparklyr::copy_to(sc, iris, overwrite = TRUE)

# library(dplyr)
dplyr::src_tbls(sc)

library(magrittr)
iris_tbl %>% dplyr::count()

library(sparklyr)
library(rsparkling)

h2oConf <- H2OConf()
hc <- H2OContext.getOrCreate(h2oConf)
```

Otherwise, `h2oConf <- H2OConf()` shows this error:

```
Error: java.lang.ClassNotFoundException: ai.h2o.sparkling.H2OConf
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:106)
	at sparklyr.StreamHandler.read(stream.scala:61)
	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by koernigo** [comment]
Hi Joseph
I am trying to use Databricks with H2o as well. I am able to create a H2OContext like the one you create above.
However, when I try to convert a Spark DF into an h2o DF I get an error message(see below). You mentioned that you were  able to do this successfully, could you share that code?

library(dplyr)
mtcars_tbl <- copy_to(sc, mtcars, overwrite = TRUE)
mtcars_tbl

# COMMAND ----------

mtcars_hf <- hc$asH2OFrame(mtcars_tbl)
mtcars_hf

Error: java.lang.ClassCastException: cannot assign instance of scala.None$ to field org.apache.spark.rdd.RDD._outputDeterministicLevel of type scala.Enumeration$Value in instance of ai.h2o.sparkling.backend.H2OAwareRDD
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2411)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeReplaceRDDs(ProtoSerializer.scala:6613)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeRDD0(ProtoSerializer.scala:6403)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeRDD(ProtoSerializer.scala:6067)
	at org.apache.spark.sql.util.ProtoSerializer.$anonfun$deserializeRDDOrNull$1(ProtoSerializer.scala:6054)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeRDDOrNull(ProtoSerializer.scala:6054)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeRDD0(ProtoSerializer.scala:6134)
	at org.apache.spark.sql.util.ProtoSerializer.deserializeRDD(ProtoSerializer.scala:6067)
	at com.databricks.service.SparkServiceRPCHandler.execute0(SparkServiceRPCHandler.scala:727)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC0$1(SparkServiceRPCHandler.scala:477)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC0(SparkServiceRPCHandler.scala:372)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:323)
	at com.databricks.service.SparkServiceRPCHandler$$anon$2.call(SparkServiceRPCHandler.scala:309)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.databricks.service.SparkServiceRPCHandler.$anonfun$executeRPC$1(SparkServiceRPCHandler.scala:359)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.service.SparkServiceRPCHandler.executeRPC(SparkServiceRPCHandler.scala:336)
	at com.databricks.service.SparkServiceRPCServlet.doPost(SparkServiceRPCServer.scala:167)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.lang.Thread.run(Thread.java:748)
