### ISSUE TITLE
No contributions under detailed_prediction in 3.32.1.1-1-3.0

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2511]
@mn-mikke I've upgraded to `3.32.1.1-1-3.0` that addresses the https://github.com/h2oai/sparkling-water/issues/2448 issue regarding `Contributions were not enabled using in EasyPredictModelWrapper`. But now it seems that the contributions column is not provided in `detailed_prediction`.
If I try to read `detailed_prediction.contributions` I get the following Spark exception

```scala
org.apache.spark.sql.AnalysisException: No such struct field contributions in label, probabilities;
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.findField(complexTypeExtractors.scala:85)
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:53)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.$anonfun$resolve$1(package.scala:348)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.resolve(package.scala:347)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveChildren(LogicalPlan.scala:101)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.$anonfun$resolveExpressionTopDown$1(Analyzer.scala:1370)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:53)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveReferences$$resolveExpressionTopDown(Analyzer.scala:1372)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.$anonfun$resolveExpressionTopDown$5(Analyzer.scala:1378)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChild$2(TreeNode.scala:368)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$4(TreeNode.scala:427)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:427)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:350)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveReferences$$resolveExpressionTopDown(Analyzer.scala:1378)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.$anonfun$resolveExpressionTopDown$5(Analyzer.scala:1378)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:399)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:350)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveReferences$$resolveExpressionTopDown(Analyzer.scala:1378)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$11.$anonfun$applyOrElse$77(Analyzer.scala:1517)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:118)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:118)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:129)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:134)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:134)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:139)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:139)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$11.applyOrElse(Analyzer.scala:1517)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$11.applyOrElse(Analyzer.scala:1382)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:1382)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:1150)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:149)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:146)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:138)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:138)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:176)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:170)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:130)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:154)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:153)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:68)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:133)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:133)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:68)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:58)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:91)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:89)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:3646)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1456)
	at org.apache.spark.sql.Dataset.withColumns(Dataset.scala:2402)
	at org.apache.spark.sql.Dataset.withColumn(Dataset.scala:2369)
```

I expect the output of `H2OMojoModel.transfom` to be a DataFrame like this
```scala
0 = {StructField@26009} "StructField(label,IntegerType,true)"
1 = {StructField@26010} "StructField(x1,DoubleType,true)"
2 = {StructField@26011} "StructField(x2,IntegerType,true)"
3 = {StructField@26012} "StructField(detailed_prediction,StructType(StructField(label,StringType,true), StructField(probabilities,StructType(StructField(1,DoubleType,false), StructField(2,DoubleType,false)),false), StructField(contributions,StructType(StructField(x1,FloatType,false), StructField(x2,FloatType,false), StructField(BiasTerm,FloatType,false)),false)),true)"
4 = {StructField@26013} "StructField(prediction,StringType,true)"
```
But I'm getting only `label` and `probabilities` under `detailed_prediction`
```scala
StructField(detailed_prediction,StructType(StructField(label,StringType,true), StructField(probabilities,StructType(StructField(0,DoubleType,false), StructField(1,DoubleType,false)),false)),true)
```

It is easy to reproduce with following snippet, I'm using Titanic dataset (prediction column is 0/1)
```
import ai.h2o.sparkling.ml.algos.H2OAutoML
val automl = new H2OAutoML()
      .setFeaturesCols(params.featureCols)
      .setLabelCol(params.labelCol)
      .setColumnsToCategorical(params.categoricalCols)
      .setSplitRatio(params.splitRatio)
      .setWithDetailedPredictionCol(true)
      .setNfolds(params.nFolds)
      .setSeed(params.seed)
      .setWeightCol(params.weightCol)
      .setMaxModels(autoMLParams.maxModels)
      .setClassSamplingFactors(autoMLParams.classSamplingFactors)
      .setConvertInvalidNumbersToNa(autoMLParams.convertInvalidNumbersToNa)
      .setExcludeAlgos(autoMLParams.excludeAlgos)
      .setFoldCol(autoMLParams.foldCol)
      .setIgnoredCols(autoMLParams.ignoredCols)
      .setMaxAfterBalanceSize(autoMLParams.maxAfterBalanceClasses)
      .setMaxRuntimeSecs(autoMLParams.maxRuntimeSecs)
      .setSortMetric(autoMLParams.sortMetric)
      .setStoppingMetric(autoMLParams.stoppingMetric)
      .setStoppingRounds(autoMLParams.stoppingRounds)
      .setStoppingTolerance(autoMLParams.stoppingTolerance)

// train
val model: H2OMOJOModel = automl.train(trainDF)

// enable contributions
val withContributions = model.getParam("withContributions")
model.set(withContributions, false)

// predict
model.transform(trainDF)
```

I guess the fix introduced a regression??

**Comment by mn-mikke** [comment]
Hi @dzlab,
Not all H2O-3 algorithms support contributions. If the algorithm (model) supports contributions, the column is there. if not, the columns is missing.

```    val automl = new H2OAutoML()
    automl.setIncludeAlgos(Array("GLM")) // GLM doesn't support contributions
    automl.setLabelCol("CAPSULE")
    automl.setMaxModels(5)
    automl.setSeed(42)
    automl.setWithContributions(true)

    automl.fit(trainingDF).transform(testingDF).select("detailed_prediction.*").show(truncate=false)

+-----+-----------------------------------------+
|label|probabilities                            |
+-----+-----------------------------------------+
|1    |{0.20256102367709128, 0.7974389763229087}|
|0    |{0.6703331986888158, 0.3296668013111842} |
|1    |{0.3917785228530979, 0.6082214771469021} |
|1    |{0.08661675056712426, 0.9133832494328757}|
|1    |{0.06195128788644455, 0.9380487121135554}|
|0    |{0.932183757373906, 0.06781624262609393} |
|0    |{0.8966697401527993, 0.1033302598472007} |
|1    |{0.48085642300241205, 0.519143576997588} |
|1    |{0.4812508186924568, 0.5187491813075432} |
|0    |{0.7255384348893557, 0.27446156511064435}|
|0    |{0.7582241452905499, 0.2417758547094501} |
|1    |{0.5620386626279812, 0.43796133737201887}|
|1    |{0.4349114884134495, 0.5650885115865505} |
|0    |{0.6383933874714189, 0.36160661252858106}|
|1    |{0.5859774373441726, 0.41402256265582743}|
|0    |{0.6794981002423295, 0.32050189975767046}|
|0    |{0.6534503255028532, 0.34654967449714674}|
|1    |{0.06522550462967647, 0.9347744953703235}|
|1    |{0.35680611360107983, 0.6431938863989202}|
|0    |{0.7611040430994194, 0.23889595690058063}|
+-----+-----------------------------------------+

    val automl = new H2OAutoML()
    automl.setIncludeAlgos(Array("GBM")) // GBM supports contributions
    automl.setLabelCol("CAPSULE")
    automl.setMaxModels(5)
    automl.setSeed(42)
    automl.setWithContributions(true)

    automl.fit(trainingDF).transform(testingDF).select("detailed_prediction.*").show(truncate=false)  
    
+-----+------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
|label|probabilities                             |contributions                                                                                                       |
+-----+------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
|1    |{0.1309358785596857, 0.8690641214403143}  |{-0.031245861, -0.05737646, 0.0045562154, 0.5360036, 0.86595917, 0.08433717, 0.22620986, 0.7832683, -0.5190024}     |
|0    |{0.864750224298404, 0.13524977570159605}  |{-0.30484292, -0.091666296, 0.014697303, -0.76020056, 0.6837218, -0.3505875, 0.16110064, -0.6885365, -0.5190024}    |
|1    |{0.24455963451915053, 0.7554403654808495} |{0.06344716, 0.06934051, -0.14103162, -0.27469838, -0.07573343, 1.215706, 0.028195929, 0.7616191, -0.5190024}       |
|1    |{0.08723020034270557, 0.9127697996572944} |{0.08121226, 0.068361335, -0.030507242, 0.8104472, 0.6859014, 0.2558068, 0.25814196, 0.7375714, -0.5190024}         |
|1    |{0.03523439429694131, 0.9647656057030587} |{0.28857782, 0.11341646, -0.03961538, 0.72594684, 0.51418823, 0.94124705, 0.15522654, 1.1298774, -0.5190024}        |
|0    |{0.9636041511726907, 0.036395848827309236}|{-0.29760665, 0.1757353, 0.011096327, -0.95365644, -0.09568942, 0.007963477, -0.024354752, -1.5807124, -0.5190024}  |
|0    |{0.9486311467133834, 0.05136885328661652} |{-0.110677555, -0.37122518, 0.002769923, 0.29614386, -0.09031614, -0.63803184, 0.16311413, -1.6487628, -0.5190024}  |
|1    |{0.362101187765548, 0.637898812234452}    |{-0.15836202, -0.11408041, 0.003637044, 0.56715405, -0.110499285, 0.22083054, -0.24434994, 0.92092866, -0.5190024}  |
|1    |{0.34335581430421347, 0.6566441856957865} |{-0.1470029, 0.03512684, 0.0038968886, 0.35413936, -0.0957469, 0.2682754, -0.22383246, 0.9725212, -0.5190024}       |
|0    |{0.9059819423823021, 0.09401805761769784} |{-0.040191174, 0.14031765, 0.0036023213, 0.10034033, -0.09649097, -0.5653662, -0.6448929, -0.643849, -0.5190024}    |
|0    |{0.8319379135003677, 0.16806208649963225} |{0.033501208, -0.19634996, 0.0034568023, 0.29751024, -0.08387474, -0.57967424, 0.025752688, -0.58074355, -0.5190024}|
|0    |{0.8019091300424178, 0.19809086995758216} |{-0.3944719, -0.0927316, 0.009527854, -0.256571, -0.13267314, -0.04642565, -0.47516719, 0.5092459, -0.5190024}      |
|1    |{0.3023775133999863, 0.6976224866000137}  |{-0.41993356, 0.4012485, 0.0042455276, 0.3593273, -0.10989224, -0.053301807, 0.2995483, 0.8737627, -0.5190024}      |
|0    |{0.8666577282755994, 0.13334227172440055} |{-0.59894484, -0.07120498, 0.008941271, -0.57178104, -0.15874124, -0.67658406, 0.1613071, 0.55428594, -0.5190024}   |
|1    |{0.41443219711395063, 0.5855678028860494} |{-0.40499362, 0.33056697, 0.013553296, -0.37034956, -0.09501435, 0.29201216, 0.2564772, 0.8424231, -0.5190024}      |
|0    |{0.915955994275756, 0.08404400572424402}  |{-0.5908198, -0.18698251, 0.009527854, -0.5762849, -0.14428207, -0.5321046, -0.3521691, 0.50349015, -0.5190024}     |
|0    |{0.7465809066780149, 0.25341909332198514} |{-0.56763345, 0.015466334, 0.0034965114, 0.6110353, -0.09384439, -0.42805767, 0.32992646, -0.4318461, -0.5190024}   |
|1    |{0.0877104256772423, 0.9122895743227577}  |{-0.49437323, 0.13820913, 0.0017585583, 0.7684786, -0.045805436, 0.77206945, -0.1499647, 1.8705453, -0.5190024}     |
|1    |{0.3685170835955638, 0.6314829164044362}  |{-0.51894933, -0.016405785, 0.0035063415, 0.49124375, -0.07237281, 0.48741427, 0.25686687, 0.42628318, -0.5190024}  |
|0    |{0.7988912255930904, 0.20110877440690958} |{-0.31884292, -2.9491377E-5, 0.005399266, -0.61645323, -0.078748964, 0.44487843, 0.35341692, -0.6499967, -0.5190024}|
+-----+------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
``` 

Would you expect a different behavior on models that doesn't support contributions?

cc @michalkurka

**Comment by dzlab** [comment]
@mn-mikke I think I found the problem, I am running the following instruction after training the model
```
val labels = model.getDomainValues()(labelColumn)
```
Not sure why but this is somehow causing the contributions to not be included even if I set the `setWithContributions`

**Comment by mn-mikke** [comment]
Hi @dzlab,
I struggling to reproduce the problem.

```
import ai.h2o.sparkling.ml.algos.H2OAutoML
val automl = new H2OAutoML()
automl.setIncludeAlgos(Array("GLM")) // GLM doesn't support contributions
automl.setLabelCol("CAPSULE")
automl.setMaxModels(5)
automl.setSeed(42)
automl.setWithContributions(true)
val model = automl.fit(trainingDF)

val labels = model.getDomainValues()("CAPSULE")
04-26 12:49:12.608 192.168.1.103:54321   11285        main  WARN ai.h2o.sparkling.ml.models.H2OMOJOCache: Computing contributions is not allowed on MOJO of type 'class hex.genmodel.algos.glm.GlmMojoModel'!
labels: Array[String] = Array(0, 1)
```

Can you share details about the produced model?

```
model.getModelDetails()
```

Btw: Are you 100% sure that your business logic doesn't try to access the `contributions` column?

**Comment by dzlab** [comment]
@mn-mikke I think we are messing up with the models by saving then later loading them. Also we don't use API so for me it's hard to find the exact sequence of instructions that's causing the contributions to not be available. I close the issue.

**Comment by dzlab** [comment]
@mn-mikke can we get contributions calculate for multi-classification? I noticed I can get them only on binary classification or regression problems. Is this expected (maybe documented somewhere)?

**Comment by mn-mikke** [comment]
@dzlab Yes, that's expected. Shapley values are supported only by tree-based binomial or regression models. I've added note SW documentation https://github.com/h2oai/sparkling-water/pull/2719. Thanks for your question!

**Comment by dzlab** [comment]
Thanks @mn-mikke for the clarification.
