### ISSUE TITLE
Issue while running pipeline.fit() for pysparkling model

### ISSUE THREAD

**Issue by tanish36** [h2oai/sparkling-water#2551]
when I am running the pysparkling modules from a pipeline in colab i am getting the following error :

`Py4JJavaError: An error occurred while calling o20858.fit.
: ai.h2o.sparkling.backend.exceptions.RestApiCommunicationException: H2O node http://172.28.0.2:54321 responded with
Status code: 500 : Server Error
Server error: {"__meta":{"schema_version":3,"schema_name":"H2OErrorV3","schema_type":"H2OError"},"timestamp":1626431262681,"error_url":"/3/FinalizeFrame","msg":"\n\nERROR MESSAGE:\n\nCaught exception: java.lang.NullPointerException\n\n","dev_msg":"\n\nERROR MESSAGE:\n\nCaught exception: java.lang.NullPointerException from: water.parser.ParseDataset.logParseResults(ParseDataset.java:1068)\n\n","http_status":500,"values":{},"exception_type":"java.lang.NullPointerException","exception_msg":"\n\nERROR MESSAGE:\n\nnull\n\n","stacktrace":["java.lang.NullPointerException","    water.parser.ParseDataset.logParseResults(ParseDataset.java:1068)","    ai.h2o.sparkling.extensions.rest.api.ImportFrameHandler.finalize(ImportFrameHandler.scala:68)","    jdk.internal.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)","    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","    java.base/java.lang.reflect.Method.invoke(Method.java:566)","    water.api.Handler.handle(Handler.java:60)","    water.api.RequestServer.serve(RequestServer.java:470)","    water.api.RequestServer.doGeneric(RequestServer.java:301)","    water.api.RequestServer.doPost(RequestServer.java:227)","    javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","    javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","    ai.h2o.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)","    ai.h2o.org.eclipse.jetty.servlet.ServletHand...
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode(RestCommunication.scala:414)
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode$(RestCommunication.scala:394)
	at ai.h2o.sparkling.H2OFrame$.checkResponseCode(H2OFrame.scala:284)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:386)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent$(RestCommunication.scala:370)
	at ai.h2o.sparkling.H2OFrame$.readURLContent(H2OFrame.scala:284)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request(RestCommunication.scala:182)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request$(RestCommunication.scala:172)
	at ai.h2o.sparkling.H2OFrame$.request(H2OFrame.scala:284)
	at ai.h2o.sparkling.backend.utils.RestCommunication.update(RestCommunication.scala:88)
	at ai.h2o.sparkling.backend.utils.RestCommunication.update$(RestCommunication.scala:81)
	at ai.h2o.sparkling.H2OFrame$.update(H2OFrame.scala:284)
	at ai.h2o.sparkling.H2OFrame$.finalizeFrame(H2OFrame.scala:396)
	at ai.h2o.sparkling.backend.Writer$.convert(Writer.scala:103)
	at ai.h2o.sparkling.backend.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:60)
	at ai.h2o.sparkling.H2OContext.$anonfun$asH2OFrame$2(H2OContext.scala:167)
	at ai.h2o.sparkling.backend.utils.H2OContextExtensions.withConversionDebugPrints(H2OContextExtensions.scala:86)
	at ai.h2o.sparkling.backend.utils.H2OContextExtensions.withConversionDebugPrints$(H2OContextExtensions.scala:74)
	at ai.h2o.sparkling.H2OContext.withConversionDebugPrints(H2OContext.scala:65)
	at ai.h2o.sparkling.H2OContext.asH2OFrame(H2OContext.scala:167)
	at ai.h2o.sparkling.H2OContext.asH2OFrame(H2OContext.scala:162)
	at ai.h2o.sparkling.ml.algos.H2OAlgoCommonUtils.prepareDatasetForFitting(H2OAlgoCommonUtils.scala:83)
	at ai.h2o.sparkling.ml.algos.H2OAlgoCommonUtils.prepareDatasetForFitting$(H2OAlgoCommonUtils.scala:55)
	at ai.h2o.sparkling.ml.algos.H2OAlgorithm.prepareDatasetForFitting(H2OAlgorithm.scala:37)
	at ai.h2o.sparkling.ml.algos.H2OAlgorithm.fit(H2OAlgorithm.scala:53)
	at ai.h2o.sparkling.ml.algos.H2OSupervisedAlgorithm.fit(H2OSupervisedAlgorithm.scala:57)
	at ai.h2o.sparkling.ml.algos.H2OTreeBasedSupervisedAlgorithm.fit(H2OTreeBasedSupervisedAlgorithm.scala:30)
	at ai.h2o.sparkling.ml.algos.H2ODRF.fit(H2ODRF.scala:35)
	at ai.h2o.sparkling.ml.algos.H2ODRF.fit(H2ODRF.scala:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)`

Here is my code for which I am getting this error :
`
    def H2OXGBoost_(numericCols,targetcol,trainingDF,testingDF):
       xgb = H2OXGBoost(labelCol=targetcol, featuresCols=numericCols)
       pipeline = Pipeline(stages=[xgb])
       # Fit and export the pipeline
       model = pipeline.fit(trainingDF)
       return model

    from pyspark.sql import SparkSession
    from pyspark.ml.evaluation import MulticlassClassificationEvaluator
    import h2o
    from pysparkling.ml import *
    from pyspark.ml import Pipeline
    spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
    from pysparkling import *
    hc = H2OContext.getOrCreate()
    from pyspark.sql.functions import col 
    sparkDF = spark.read.csv("/content/glass.csv", header=True, inferSchema= True)
    numericCols = ['ri', 'na', 'mg', 'al', 'si', 'k', 'ca', 'ba', 'fe']
    targetcol="type"
    sparkDF = sparkDF.withColumn(targetcol, col(targetcol).cast("string"))
    [trainingDF, testingDF] = sparkDF.randomSplit([0.8, 0.2])
    H2OGBM_(numericCols,targetcol,trainingDF,testingDF)
`
this is the link of my dataset which I am using: https://github.com/tanish36/Tensorflow-Projects/blob/master/glass.csv

when I am using some other dataset this error is not getting generated 
Spark Version : 3.0.2
pysparkling version : 3.0

**Comment by mn-mikke** [comment]
Hi @tanish36, 
thanks for reporting this issue. It is caused by the column in your dataset named `na`. If you rename the column, the problem should disappear. The next version of SW will handle this edge case (Jira ticket https://h2oai.atlassian.net/browse/SW-2580)

**Comment by tanish36** [comment]
Thanks !!!
