### ISSUE TITLE
Idle timeout expired: 30000/30000 ms

### ISSUE THREAD

**Issue by noootime** [h2oai/sparkling-water#2552]
When call the H2OContext.getOrCreate(conf) , I got the excetion:
Idle timeout expired: 30000/30000 ms 

Environment:
- Spark 2.4
- Sparkling water for Spark 2.4
- Python 3.6.8
- Execution mode `YARN-client`

Code: 
```
spark = SparkSession.builder. \
    appName("H2O-GBM-train"). \
    master("yarn"). \
    config("spark.dynamicAllocation.enabled", False). \
    config("spark.executor.memory", "5G"). \
    config("spark.num-executors", 20). \
    config("spark.executor-cores", 4). \
    config("spark.default.parallelism", 200). \
    config("spark.driver.memory", "4G"). \
    config("spark.locality.wait", 4000). \
    config("spark.shuffle.service.enabled", False). \
    config("spark.dynamicAllocation.shuffleTracking.enabled", False). \
    config("spark.scheduler.minRegisteredResourcesRatio", 1). \
    enableHiveSupport().getOrCreate()
spark.sparkContext.addPyFile("./gbm_search.py")

conf = H2OConf(). \
    setNumH2OWorkers(100). \
    setInternalClusterMode(). \
    setNthreads(-1). \
    setRestApiTimeout(600000).setBasePort(54345)
hc = H2OContext.getOrCreate(conf)

def get_data_copy():
    hive_database = config.get('config', 'hive_database')
    hive_table = config.get('config', 'hive_table')
    spark.sql("set hive.support.quoted.identifiers=None")
    search_sql = """select * from  {}.{} limit 6000000""".format(hive_database, hive_table)
    df = spark.sql(search_sql)
    h2o_df = hc.asH2OFrame(df)
    h2o_df[factor_col] = h2o_df[factor_col].asfactor()
    return h2o_df

if __name__ == '__main__':
    config = configparser.ConfigParser()
    config.read('../config/config.ini', encoding='GB18030')

    h2o_df = get_data_copy()
```

**Log**
[full log](https://github.com/h2oai/sparkling-water/files/6835673/log.txt)

```
Status code: 500 : Server Error
Server error: {"__meta":{"schema_version":3,"schema_name":"H2OErrorV3","schema_type":"H2OError"},"timestamp":1626346191426,"error_url":"/3/Chunk","msg":"\n\nERROR MESSAGE:\n\njava.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms\n\n","dev_msg":"\n\nERROR MESSAGE:\n\njava.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms\n\n","http_status":500,"values":{},"exception_type":"java.io.IOException","exception_msg":"\n\nERROR MESSAGE:\n\njava.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms\n\n","stacktrace":["java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms","    ai.h2o.org.eclipse.jetty.server.HttpInput$ErrorState.noContent(HttpInput.java:1080)","    ai.h2o.org.eclipse.jetty.server.HttpInput.read(HttpInput.java:313)","    org.xerial.snappy.SnappyInputStream.readHeader(SnappyInputStream.java:84)","    org.xerial.snappy.SnappyInputStream.<init>(SnappyInputStream.java:59)","    ai.h2o.sparkling.utils.Compression$.decompress(Compression.scala:44)","    ai.h2o.sparkling.extensions.rest.api.ChunkServlet$$anonfun$doPut$1$$anonfun$apply$mcV$sp$2.apply(ChunkServlet.scala:192)","    ai.h2o.sparkling.extensions.rest.api.ChunkServlet$$anonfun$doPut$1$$anonfun$apply$mcV$sp$2.apply(ChunkServlet.scala:191)","    ai.h2o.sparkling.utils.ScalaUtils$.withResource(ScalaUtils.scala:28)","    ai.h2o.sparkling.extensions.rest.api.ChunkServlet$$anonfun$doPut$1.apply$mcV$sp(ChunkServlet.scala:191)","    ai.h2o.sparkling.extensions.rest.api.ServletBase.processRequest(ServletBase.scala:36)","    ai.h2o.sparkling.extensions.rest.api.ChunkServlet.doPut(ChunkServlet.scala:188)","    javax.servlet.http.HttpServlet.service(HttpServlet.java:710)","    javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","    ai.h2o.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)","    ai.h2o.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)","    ai.h2o.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)","    ai.h2o.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)","    ai.h2o.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)","    ai.h2o.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)","    ai.h2o.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)","    ai.h2o.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)","    ai.h2o.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)","    ai.h2o.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)","    ai.h2o.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)","    water.webserver.jetty9.Jetty9ServerAdapter$LoginHandler.handle(Jetty9ServerAdapter.java:130)","    ai.h2o.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)","    ai.h2o.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)","    ai.h2o.org.eclipse.jetty.server.Server.handle(Server.java:531)","    ai.h2o.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)","    ai.h2o.org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:293)","    ai.h2o.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)","    ai.h2o.org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)","    java.lang.Thread.run(Thread.java:748)","Caused by:java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms","    ai.h2o.org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)","    ai.h2o.org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)","    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)","    java.util.concurrent.FutureTask.run(FutureTask.java:266)","    java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)","    java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)","    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","    java.lang.Thread.run(Thread.java:748)"]}
	at ai.h2o.sparkling.backend.utils.RestCommunication$class.checkResponseCode(RestCommunication.scala:412)
	at ai.h2o.sparkling.backend.H2OChunk$.checkResponseCode(H2OChunk.scala:32)
	at ai.h2o.sparkling.backend.utils.RestCommunication$$anonfun$insert$1.apply$mcV$sp(RestCommunication.scala:155)
	at ai.h2o.sparkling.utils.FinalizingOutputStream.close(FinalizingOutputStream.scala:27)
	at java.nio.channels.Channels$WritableByteChannelImpl.implCloseChannel(Channels.java:469)
	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
	at water.AutoBuffer.close(AutoBuffer.java:468)
	at ai.h2o.sparkling.extensions.serde.ChunkAutoBufferWriter.close(ChunkAutoBufferWriter.scala:171)
	at ai.h2o.sparkling.backend.Writer.close(Writer.scala:84)
	at ai.h2o.sparkling.utils.ScalaUtils$.closeResource(ScalaUtils.scala:46)
	at ai.h2o.sparkling.utils.ScalaUtils$.withResource(ScalaUtils.scala:34)
	at ai.h2o.sparkling.backend.Writer$.ai$h2o$sparkling$backend$Writer$$perDataFramePartition(Writer.scala:116)
	at ai.h2o.sparkling.backend.Writer$$anonfun$1.apply(Writer.scala:98)
	at ai.h2o.sparkling.backend.Writer$$anonfun$1.apply(Writer.scala:98)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mn-mikke** [comment]
Hi @noootime, 
may you try to increase the number of partitions of the input dataframe? Does it help?
(E.g.: `df = spark.sql(search_sql).repartition(200)`)

**Comment by noootime** [comment]
Hi @mn-mikke 
    Thanks for your feedback! 
    `spark.sql(search_sql).repartition(200)` is worked for me when the data size is about ten million level.
Once the data size is upper to a hundred million, it still throws the “Idle timeout expired” error.

| limit size  | repartition|
|-------------|------------|
|limit 5,000,000 | without repartition it works
|limit 10,000,000 | with repartition(200) it works
|limit 100,000,000  | with repartition(n) it doesn't work

My workaround:
I just use the mmlspark.lightgbm.LightGBMClassifier instead of h2o's LightGBMClassifier in my application.

**Comment by mn-mikke** [comment]
Hi @noootime, with SW `3.34.0.4-1` shouldn't fix this problem. if you still experience a similar problem, you can try to set the java property `sys.ai.h2o.http.jetty.idleTimeout` (eventually `sys.ai.h2o.https.jetty.idleTimeout`)  to a higher value. The current default value is 5 minutes.

If the problem still persists, reopen the issue. Closing for now.
