### ISSUE TITLE
Dependency version issue of google-api-services-storage

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2643]
I'm importing sparking-water in my project as a fat jar like this
```
val h2oVersion = "3.32.1.2-1-3.1" 
"ai.h2o" % "sparkling-water-package_2.12" % h2oVersion
```

I also include google storage library (which transiently bring also google apis lib)
```
"com.google.cloud.bigdataoss" % "gcs-connector" % "hadoop3-2.2.2"
```

Now when I try to use `gcs-connector` to write into google storage, it does fail with the error below
```
Caused by: java.lang.NoSuchMethodError: com.google.api.services.storage.Storage$Objects$List.setIncludeTrailingDelimiter(Ljava/lang/Boolean;)Lcom/google/api/services/storage/Storage$Objects$List;
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.createListRequest(GoogleCloudStorageImpl.java:1401)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.listStorageObjectsAndPrefixes(GoogleCloudStorageImpl.java:1272)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.listObjectInfo(GoogleCloudStorageImpl.java:1443)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.lambda$getFileInfoInternal$8(GoogleCloudStorageFileSystem.java:1059)
```
After investigation I found that sparkling water is bringing an older version of `com.google.api.services.storage.Storage$Objects$List` that does not have the `setIncludeTrailingDelimiter` method hence the error above.

The issue is that I depend on sparkling-water fat jar so I cannot find a way to exclude or shade the `google-api-services-storage` library that it is brinnging. I also looked how sparkling-water is depdening on this google library without shading (like it does with AWS Java client) but could not find anything.

@mn-mikke any suggestions to solve this dependency version issue?

**Comment by dzlab** [comment]
See how `com.google.api.services.storage` are included in the SW fat jar without shading
![image](https://user-images.githubusercontent.com/1645304/133829394-05576139-9dc8-4a34-9675-41007a12210c.png)

**Comment by dzlab** [comment]
I tried to build sparkling-water locally so I could grap the packages individually instead of add the fat jar as dependency, this is what I get
```
$ sparkling-water git:(master) ls -l build/repo/ai/h2o
total 0
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:53 sparkling-water-core_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:53 sparkling-water-doc_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:54 sparkling-water-examples_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:54 sparkling-water-extensions_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:54 sparkling-water-ml_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:54 sparkling-water-package_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:55 sparkling-water-repl_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:55 sparkling-water-scoring-package_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:55 sparkling-water-scoring_2.12
drwxr-xr-x  6 dzlab  dzlab  192 Sep 17 10:55 sparkling-water-utils_2.12
```
It seems that the build is missing `api-generation` package (no binaries are generated!), but this package is needed by other packages like the ml one! so how I could also locally publish this `api-generation` package?

**Comment by dzlab** [comment]
@mn-mikke this PR https://github.com/h2oai/sparkling-water/pull/2645 does shade google dependencies and solve this issue

**Comment by dzlab** [comment]
@mn-mikke after shading google depdencies I did run into another issue with a one of `google-api-services-storage` dependencies
```
Caused by: java.lang.NoSuchMethodError: io.opencensus.trace.Span.addMessageEvent(Lio/opencensus/trace/MessageEvent;)V
    at com.google.api.client.http.OpenCensusUtils.recordMessageEvent(OpenCensusUtils.java:222)
    at com.google.api.client.http.OpenCensusUtils.recordSentMessageEvent(OpenCensusUtils.java:190)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1010)
    at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:304)
    at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:324)
    at com.google.cloud.hadoop.util.CredentialFactory$GoogleCredentialWithRetry.executeRefreshToken(CredentialFactory.java:170)
    at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:470)
    at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:201)
```
I cannot shade everything! probably need to dependent on a non fat jar of sparkling water.
Can you advice how to make the `api-generation` published that's what is blocking me from using individual jars instead of replying on the fat jar.

**Comment by dzlab** [comment]
@mn-mikke thanks for the hint.
