### ISSUE TITLE
Missing provider for modeling steps XGBoost when training AutoML

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2714]
I'm seeing following error when I try to train an AutoML model, which basiclly means the `ModelingStepsProvider` for XBoost was not loaded.

```
01-11 02:26:31.760 10.0.10.80:54321      48     7751178-43  INFO water.default: Workflow: Loading execution steps: [{XGBoost : [def_2 (1g, 10w), def_1 (2g, 10w), def_3 (3g, 10w), grid_1 (4g, 90w), lr_search (6g, 30w)]}, {GLM : [def_1 (1g, 10w)]}, {DRF : [def_1 (2g, 10w), XRT (3g, 10w)]}, {GBM : [def_5 (1g, 10w), def_2 (2g, 10w), def_3 (2g, 10w), def_4 (2g, 10w), def_1 (3g, 10w), grid_1 (4g, 60w), lr_annealing (6g, 10w)]}, {DeepLearning : [def_1 (3g, 10w), grid_1 (4g, 30w), grid_2 (5g, 30w), grid_3 (5g, 30w)]}, {completion : [resume_best_grids (10g, 60w)]}, {StackedEnsemble : [best_of_family_1 (1g, 5w), best_of_family_2 (2g, 5w), best_of_family_3 (3g, 5w), best_of_family_4 (4g, 5w), best_of_family_5 (5g, 5w), all_2 (2g, 10w), all_3 (3g, 10w), all_4 (4g, 10w), all_5 (5g, 10w), monotonic (6g, 10w), best_of_family_xgboost (6g, 10w), best_of_family_gbm (6g, 10w), all_xgboost (7g, 10w), all_gbm (7g, 10w), best_of_family_xglm (8g, 10w), all_xglm (8g, 10w), best_of_family (10g, 10w), best_N (10g, 10w)]}]
01-11 02:26:31.761 10.0.10.80:54321      48     7751178-43 ERROR water.default: 
java.lang.IllegalArgumentException: Missing provider for modeling steps &#x27;XGBoost&#x27;
	at ai.h2o.automl.AutoMLSession.getModelingSteps(AutoMLSession.java:73)
	at ai.h2o.automl.ModelingStepsRegistry.getOrderedSteps(ModelingStepsRegistry.java:54)
	at ai.h2o.automl.AutoML.getExecutionPlan(AutoML.java:344)
	at ai.h2o.automl.AutoML.planWork(AutoML.java:373)
	at ai.h2o.automl.AutoML.submit(AutoML.java:409)
	at ai.h2o.automl.AutoML.startAutoML(AutoML.java:81)
	at water.automl.api.AutoMLBuilderHandler.build(AutoMLBuilderHandler.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at water.api.Handler.handle(Handler.java:60)
	at water.api.RequestServer.serve(RequestServer.java:470)
	at water.api.RequestServer.doGeneric(RequestServer.java:301)
	at water.api.RequestServer.doPost(RequestServer.java:227)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at water.webserver.jetty9.Jetty9ServerAdapter$LoginHandler.handle(Jetty9ServerAdapter.java:130)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

You can see from the logs of the executor that the XBoost library is found and the core extenstion was loaded properly, also I tried to manually enable xboost on multinode with `-Dsys.ai.h2o.automl.xgboost.multinode.enabled=true`
```
+ exec /tini -s -- /usr/java/default/bin/java -Dsys.ai.h2o.automl.xgboost.multinode.enabled=true -Dspark.network.crypto.enabled=true -Dspark.driver.blockManager.port=10000 -Dspark.authenticate=true -Dspark.ui.port=10013 -Dspark.rpc.message.maxSize=256 -Dspark.vad.port=10011 -Dspark.driver.port=7077 -Xms1024m -Xmx1024m -cp &#x27;/opt/spark/conf::/opt/spark/jars/*:/opt/hadoop3.3.1/etc/hadoop:/opt/hadoop3.3.1/share/hadoop/common/lib/*:/opt/hadoop3.3.1/share/hadoop/common/*:/opt/hadoop3.3.1/share/hadoop/hdfs:/opt/hadoop3.3.1/share/hadoop/hdfs/lib/*:/opt/hadoop3.3.1/share/hadoop/hdfs/*:/opt/hadoop3.3.1/share/hadoop/mapreduce/*:/opt/hadoop3.3.1/share/hadoop/yarn:/opt/hadoop3.3.1/share/hadoop/yarn/lib/*:/opt/hadoop3.3.1/share/hadoop/yarn/*&#x27; org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@dev.svc.cluster.local:7077 --executor-id 1 --cores 1 --app-id spark-application-1641867872252 --hostname 10.0.10.80 --resourceProfileId 0

2022-01-11 02:24:51,484 INFO util.NativeLibrary: Loaded library from lib/linux_64/libxgboost4j_gpu.so (/tmp/libxgboost4j_gpu14080938853620544642.so)

01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Found H2O Core extensions: [HiveTableImporter, StackTraceCollector, HiveFrameSaver, MojoPipeline, XGBoost]

01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Processed H2O arguments: [-internal_security_conf_rel_paths, -name, sparkling-water-4444_spark-application-1641867872252, -port_offset, 1, -nthreads, 1, -hdfs_config, /tmp/./hdfs_conf14896694781998442236.xml, -log_level, INFO, -embedded, -baseport, 54321, -log_dir, /tmp/h2ologs/spark-application-1641867872252, -disable_flow, -ip, 10.0.10.80, -flatfile, /var/data/spark-cee995c5-e826-4812-af1e-bd9989c81281/spark-fe28f50c-7c04-4d35-ac9d-7e9319b91dd5/sparkling-water-96c057c3-2bc9-45a4-be75-2fe47819ad49/flatfile.txt]
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Java availableProcessors: 1
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Java heap totalMemory: 989.9 MB
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Java heap maxMemory: 989.9 MB
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Java version: Java 11.0.10 (from Amazon.com Inc.)
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: JVM launch parameters: [-Dsys.ai.h2o.automl.xgboost.multinode.enabled=true, -Dspark.network.crypto.enabled=true, -Dspark.driver.blockManager.port=10000, -Dspark.authenticate=true, -Dspark.ui.port=10013, -Dspark.rpc.message.maxSize=256, -Dspark.port=10011, -Dspark.driver.port=7077, -Xms1024m, -Xmx1024m]
01-11 02:24:52.176 10.0.10.80:54321      48     ent-loop-1  INFO water.default: JVM process id: 48@exmacstandaloneexmachinaprodbachirchihanic3ai-exec-1
01-11 02:24:52.177 10.0.10.80:54321      48     ent-loop-1  INFO water.default: OS version: Linux 4.14.232-176.381.amzn2.x86_64 (amd64)
01-11 02:24:52.177 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Machine physical memory: 1.38 GB
01-11 02:24:52.177 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Machine locale: en_US

01-11 02:25:00.237 10.0.10.80:54321      48     ent-loop-1  INFO water.default: HiveTableImporter extension initialized
01-11 02:25:00.237 10.0.10.80:54321      48     ent-loop-1  INFO water.default: StackTraceCollector extension initialized
01-11 02:25:00.237 10.0.10.80:54321      48     ent-loop-1  INFO water.default: HiveFrameSaver extension initialized
01-11 02:25:00.237 10.0.10.80:54321      48     ent-loop-1  INFO water.default: MojoPipeline extension initialized
01-11 02:25:00.237 10.0.10.80:54321      48     ent-loop-1  INFO water.default: XGBoost extension initialized
01-11 02:25:00.238 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Registered 5 core extensions in: 2158ms
01-11 02:25:00.238 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Registered H2O core extensions: [HiveTableImporter, StackTraceCollector, HiveFrameSaver, MojoPipeline, XGBoost]
01-11 02:25:01.375 10.0.10.80:54321      48     ent-loop-1  INFO hex.tree.xgboost.XGBoostExtension: Found XGBoost backend with library: xgboost4j_gpu
01-11 02:25:01.375 10.0.10.80:54321      48     ent-loop-1  INFO hex.tree.xgboost.XGBoostExtension: XGBoost supported backends: [WITH_GPU, WITH_OMP]
01-11 02:25:01.443 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Registered: 265 REST APIs in: 1205ms
01-11 02:25:01.444 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Registered REST API extensions: [Algos, XGBoost, Amazon S3, Sparkling Water REST API Extensions, AutoML, Core V3, TargetEncoder, Core V4]
01-11 02:25:01.733 10.0.10.80:54321      48     ent-loop-1  INFO water.default: Registered: 321 schemas in 289ms
01-11 02:25:01.733 10.0.10.80:54321      48     ent-loop-1  INFO water.default: H2O started in 12391ms
```

I also added a logic in the driver to print all implementations of `ModelingStepsProvider` and it seems that XGBoost is there
```
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;DeepLearning&#x27; with class &#x27;ai.h2o.automl.modeling.DeepLearningStepsProvider@259a0a5c&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;StackedEnsemble&#x27; with class &#x27;ai.h2o.automl.modeling.StackedEnsembleStepsProvider@ce00528&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;GBM&#x27; with class &#x27;ai.h2o.automl.modeling.GBMStepsProvider@60354157&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;DRF&#x27; with class &#x27;ai.h2o.automl.modeling.DRFStepsProvider@4cf9cecf&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;completion&#x27; with class &#x27;ai.h2o.automl.modeling.CompletionStepsProvider@39c4f5e6&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;GLM&#x27; with class &#x27;ai.h2o.automl.modeling.GLMStepsProvider@35017eb3&#x27;
2022-01-11T02:26:26.082+0000 level=INFO thread="pool-36-thread-1" logger=ai.h2o.automl.XGBoostModelingStepsRegistry req_id="" user_id=""
registered provider &#x27;XGBoost&#x27; with class &#x27;ai.h2o.automl.modeling.XGBoostStepsProvider@7ff4bebd&#x27;
```

I see that is is defined in the services file https://github.com/h2oai/h2o-3/blob/master/h2o-automl/src/main/resources/META-INF/services/ai.h2o.automl.ModelingStepsProvider So I am thinking maybe this `ai.h2o.automl.modeling.XGBoostStepsProvider` is not available in the executor and hence it throws the exception above?

This is how I define sparkling water dependency in my `build.sbt`
```scala
val h2oVersion = "3.34.0.4-1-3.1" // Nov 2021 https://mvnrepository.com/artifact/ai.h2o/sparkling-water-package
lazy val h2oLibs = Seq(
  "ai.h2o" %% "sparkling-water-ml" % h2oVersion excludeAll (Seq(
    ExclusionRule("ai.h2o", "h2o-persist-gcs")
  ): _*)
)
```

@mn-mikke any clue?

**Comment by mn-mikke** [comment]
cc @sebhrusen

**Comment by mn-mikke** [comment]
@dzlab Do you experience the same problem if you use `sparkling-water-package` instead of `sparkling-water-ml`?

**Comment by sebhrusen** [comment]
@dzlab are you systematically getting the error or does it occur occasionally?
Also, are you running SW on multinode?
I may have an idea about what's happening: a race condition due to the fact that the provider's dictionary in `AutoMLSession` is cleared each time we call `session()` in AutoML…

**Comment by dzlab** [comment]
@mn-mikke @sebhrusen I see this systematically now as I'm using `sparkling-water-ml` before I was using `sparkling-water-package` and never had this issue

**Comment by mn-mikke** [comment]
@dzlab How do you deploy SW/H2O libraries to your cluster? Do you create a fat jar containing your business logic and SW/H2O libraries? Or are libraries deployed to the cluster separately? Can you check presence of the library `ai.h2o:h2o-ext-xgboost:3.34.0.4` on your cluster?

**Comment by dzlab** [comment]
@mn-mikke I deploy my app as fat jar with all dependencies and deploy h2o as part of my spark cluster on k8s, and i use this jar in the spark driver as well as the spark executor.
Also, in the log above the xboost extension seem to be initialized properly but I guess that's in happening in the driver node.

In the fat jar, I see the classes of `ai.h2o:h2o-ext-xgboost:3.34.0.4` 
```
jar tf /opt/lib/my-app.jar | grep ai.h2o.xgboost4j.java
ai/h2o/xgboost4j/java/
ai/h2o/xgboost4j/java/util/
META-INF/services/ai.h2o.xgboost4j.java.INativeLibLoader
ai/h2o/xgboost4j/java/Booster$FeatureImportanceType.class
ai/h2o/xgboost4j/java/Booster.class
ai/h2o/xgboost4j/java/BoosterWrapper.class
ai/h2o/xgboost4j/java/DMatrix$SparseType.class
ai/h2o/xgboost4j/java/DMatrix.class
ai/h2o/xgboost4j/java/DataBatch$BatchIterator.class
ai/h2o/xgboost4j/java/DataBatch.class
ai/h2o/xgboost4j/java/ExternalCheckpointManager.class
ai/h2o/xgboost4j/java/GpuTestSuite.class
ai/h2o/xgboost4j/java/IEvaluation.class
ai/h2o/xgboost4j/java/INativeLibLoader.class
ai/h2o/xgboost4j/java/IObjective.class
ai/h2o/xgboost4j/java/IRabitTracker$TrackerStatus.class
ai/h2o/xgboost4j/java/IRabitTracker.class
ai/h2o/xgboost4j/java/KryoBooster.class
ai/h2o/xgboost4j/java/NativeLibLoader$DefaultNativeLibLoader.class
ai/h2o/xgboost4j/java/NativeLibLoader.class
ai/h2o/xgboost4j/java/NativeLibLoaderService.class
ai/h2o/xgboost4j/java/Rabit$DataType.class
ai/h2o/xgboost4j/java/Rabit$OpType.class
ai/h2o/xgboost4j/java/Rabit.class
ai/h2o/xgboost4j/java/RabitTracker$1.class
ai/h2o/xgboost4j/java/RabitTracker$TrackerProcessLogger.class
ai/h2o/xgboost4j/java/RabitTracker.class
ai/h2o/xgboost4j/java/TrackerProperties.class
ai/h2o/xgboost4j/java/XGBoost$CVPack.class
ai/h2o/xgboost4j/java/XGBoost.class
ai/h2o/xgboost4j/java/XGBoostError.class
ai/h2o/xgboost4j/java/XGBoostJNI.class
ai/h2o/xgboost4j/java/util/BigDenseMatrix.class
ai/h2o/xgboost4j/java/util/UtilUnsafe.class
```

**Comment by dzlab** [comment]
@mn-mikke @sebhrusen this hack before submitting the actual automl training job seems to get the provider loaded in `ModelingStepsRegistry`

```scala
    val allExecutors = sparkContext.getExecutorMemoryStatus.map(_._1)
    val driverHost = sparkContext.getConf.get("spark.driver.host")
    val activeExecutors = allExecutors.filter(! _.split(":")(0).equals(driverHost))
    val numPartitions = activeExecutors.size + 1
    // force load the providers
   sparkContext.parallelize((0 until numPartitions)).repartition(numPartitions).foreachPartition{_ =>
      ModelingStepsRegistry.stepsByName.forEach{case (name, provider) =>
        logInfo("registered provider '{}' with class '{}'", name, provider)
      }
    }
  }
}
```

**Comment by mn-mikke** [comment]
@dzlab One more question. What `H2OContext` do you use? `org.apache.spark.h2o.H2OContext` or `ai.h2o.sparkling.H2OContext`?

**Comment by mn-mikke** [comment]
@dzlab if you're running on K8s, can you try to run [SW with external backend](https://h2o-release.s3.amazonaws.com/sparkling-water/spark-3.1/3.34.0.4-1-3.1/doc/deployment/kubernetes.html#automatic-mode-of-external-backend)? When you create `H2OContext`, it will run H2O nodes in separated pods. Docker images for H2O nodes (sparkling-water-external-backend) that are on docker hub have everything needed for XGBoost and AutoML. If the seme scenario fails with external backend, then it must a bug on our side.

**Comment by dzlab** [comment]
I'm embedding H2O in my application not easy for me to provision the spark cluster with h2o having separate nodes

**Comment by dzlab** [comment]
@mn-mikke so what's happening here is `ModelingStepsRegistry` class static logic is not called in time for loading all the provider implementations. Hence my hack of just calling this class before actual training. I looked into h2o repo and i don't see lot usage of this class and definitely not a clean up of the providers map so not sure why using the sparkling water fat jar has any difference compared to using the individual jar.

**Comment by sebhrusen** [comment]
> ModelingStepsRegistry class static logic is not called in time for loading all the provider implementations

what do you mean by "in time"? It's a static block, it's executed when the class is loaded and therefore before any subsequent use of the class or one of its instances.

are you suggesting that in your environment, the static initialization is not completed at the time the `ModelingStepsRegistry` instance is used by `AutoML`? Could something in your setup be playing with classloaders?

**Comment by dzlab** [comment]
@sebhrusen no I don't have any custom class loading logic, but i'm just trying to find an explanation on why touching the class explicitly would make the provider properly register and the error to go away.
Automl was working fine for me until i switched away from using the fat jar
