### ISSUE TITLE
This H2O node couldn't find the file(s) to parse

### ISSUE THREAD

**Issue by wzy1203** [h2oai/sparkling-water#274]
17/05/10 16:43:03 ERROR yarn.ApplicationMaster: User class threw exception: DistributedException from 519a86958d05/xxx.xx.xxx.xx:54321, caused by java.lang.RuntimeException: This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.
DistributedException from 519a86958d05/xxx.xx.xxx.xx:54321, caused by java.lang.RuntimeException: This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.
        at water.MRTask.getResult(MRTask.java:478)
        at water.MRTask.getResult(MRTask.java:486)
        at water.MRTask.doAll(MRTask.java:402)
        at water.parser.ParseSetup.guessSetup(ParseSetup.java:265)
        at water.parser.ParseSetup.guessSetup(ParseSetup.java:247)
        at water.parser.ParseDataset.parse(ParseDataset.java:38)
        at water.parser.ParseDataset.parse(ParseDataset.java:32)
        at water.util.FrameUtils.parseFrame(FrameUtils.java:63)
        at water.util.FrameUtils.parseFrame(FrameUtils.java:52)
        at water.fvec.H2OFrame.<init>(H2OFrame.scala:66)
        at water.fvec.H2OFrame.<init>(H2OFrame.scala:76)
        at SparklingWater$.main(SparklingWater.scala:23)
        at SparklingWater.main(SparklingWater.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
Caused by: java.lang.RuntimeException: This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.
        at water.parser.ParseSetup$GuessSetupTsk.map(ParseSetup.java:406)
        at water.MRTask.compute2(MRTask.java:601)
        at water.H2O$H2OCountedCompleter.compute1(H2O.java:1244)
        at water.parser.ParseSetup$GuessSetupTsk$Icer.compute1(ParseSetup$GuessSetupTsk$Icer.java)
        at water.H2O$H2OCountedCompleter.compute(H2O.java:1240)
        at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
        at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
        at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by jakubhava** [comment]
Hi @wzy1203, can you pls share the following details ?
- spark version
- sparkling water version
 - deployment type ( spark MASTER variable - local, yarn )
- data on which this exception happened
- reproducible code

Thanks, Kuba

**Comment by wzy1203** [comment]
hi @jakubhava
- spark version 1.6.1
- sparkling water 1.6.0
- yarn  
     -  when it runs local, it successed.
- [data](https://github.com/wzy1203/data/blob/master/iris_wheader.csv)
- ` val conf = new SparkConf().setAppName("SparklingWater")
        val sc = new SparkContext(conf)
        val sqlContext = new SQLContext(sc)

        val h2oContext = H2OContext.getOrCreate(sc)

        addFiles(sc, "hdfs://servicename/user/wzy/data/iris_wheader.csv")

        val irisData = new H2OFrame(new File(SparkFiles.get("iris_wheader.csv")))

        val params = new SVDModel.SVDParameters()
        params._train = irisData._key
        params._valid = irisData._key
        import hex.DataInfo
        import hex.svd.SVDModel.SVDParameters
        params._nv = 4
        params._seed = 4
        params._only_v = false
        params._transform = DataInfo.TransformType.NONE
        params._svd_method = SVDParameters.Method.GramSVD
        params._save_v_frame = false
        params._keep_cross_validation_fold_assignment = true
        params._keep_cross_validation_predictions = true

        val rdd = sc.parallelize(List(1),1)

        val result = rdd.mapPartitions( (iter) => {

            var list = List[String]()
            val svd: SVDModel = new SVD(params).trainModel().get()

            list.::("test").iterator

        })

        result.collect.foreach (println)`

**Comment by jakubhava** [comment]
Thanks for the details @wzy1203 , let me have a look on it

**Comment by jakubhava** [comment]
Ho @wzy1203 sorry for later answer. Still didn't have to properly look on the problem, but in the meanwhile, could you please try to run `val irisData = new H2OFrame(new java.net.URI("hdfs://servicename/user/wzy/data/iris_wheader.csv"))`
instead of the following two lines ?
```
addFiles(sc, "hdfs://servicename/user/wzy/data/iris_wheader.csv")
val irisData = new H2OFrame(new File(SparkFiles.get("iris_wheader.csv")))
```

Thanks a lot!

**Comment by jakubhava** [comment]
Hi @wzy1203 , we have created JIRA to track the issue https://0xdata.atlassian.net/browse/SW-428. I'll close this issue, please use the link above to track the state of the issue
