### ISSUE TITLE
Errors in deploying sparkling water in manual mode on kubernetes

### ISSUE THREAD

**Issue by RajatSablok** [h2oai/sparkling-water#2753]
Gettig the following traceback when trying to deploy sparkling water external backend in manual mode on Kubernetes:

```
Traceback (most recent call last):
  File "/opt/spark/work-dir/inith2o.py", line 23, in <module>
    spark = SparkSession.builder.appName("App name").getOrCreate()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 146, in __init__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
  File "/usr/local/lib/python3.9/dist-packages/py4j/java_gateway.py", line 1585, in __call__
    return_value = get_return_value(
  File "/usr/local/lib/python3.9/dist-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.ExceptionInInitializerError
	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:109)
	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:371)
	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:311)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:359)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:189)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1642)
	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:207)
	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
	... 19 more
```

This is what my config looks like:
```
conf["spark.scheduler.minRegisteredResourcesRatio"]=1
conf["spark.ext.h2o.backend.cluster.mode"]="external"
conf["spark.ext.h2o.external.start.mode"]="manual"
conf["spark.ext.h2o.external.auto.start.backend"]="kubernetes"
conf["spark.ext.h2o.external.cluster.size"]=1
conf["spark.ext.h2o.external.memory"]="2G"
conf["spark.ext.h2o.cloud.name"]="root"
conf["spark.ext.h2o.cloud.representative"]="h2o-service.sparkling-water.svc.cluster.local:54321"
conf["spark.ext.h2o.external.k8s.docker.image"]="h2oai/sparkling-water-external-backend:3.36.0.3-1-3.2" 
```

**Comment by mn-mikke** [comment]
Hi @RajatSablok,
what docker image do you use for spark cluster? h2oai/sparkling-water-python:3.36.0.3-1-3.2 or a different one?

**Comment by mn-mikke** [comment]
@RajatSablok Any update on this issue?

**Comment by RajatSablok** [comment]
@mn-mikke I built a custom base image using the sparkling water zip directly, the issue might have been over there. Now I am using the given base image and it's working fine.
