### ISSUE TITLE
H2O node/pod becomes unhealthy

### ISSUE THREAD

**Issue by RajatSablok** [h2oai/sparkling-water#2779]
Hi team,

Every so often, 1 of my 2 h2o pods becomes unhealthy and starts printing logs like the below:

```
05-20 11:11:05.353 xx.yyy.zzz.ww:54321   1      9.28:54321 ERROR water.default: Got IO error when sending a batch of bytes: 
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:459) ~[?:?]
	at water.H2ONode$SmallMessagesSendThread.sendBuffer(H2ONode.java:609) [h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.run(H2ONode.java:592) [h2o.jar:?]
05-20 11:13:20.521 xx.yyy.zzz.ww:54321   1      9.28:54321 ERROR water.default: Got IO error when sending a batch of bytes: 
java.net.ConnectException: Connection timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:483) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:472) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:692) ~[?:?]
	at water.H2ONode.openChan(H2ONode.java:496) ~[h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.openChan(H2ONode.java:634) ~[h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.sendBuffer(H2ONode.java:608) [h2o.jar:?]
	at water.H2ONode$SmallMessagesSendThread.run(H2ONode.java:592) [h2o.jar:?]
05-20 11:15:35.689 xx.yyy.zzz.ww:54321   1      9.28:54321 ERROR water.default: Got IO error when sending a batch of bytes: 
```

Because of this, the next set of jobs only connect to one pod:

```
22/05/20 12:09:02 INFO H2OContext: Sparkling Water 3.36.0.3-1-3.1 started, status of context: 
Sparkling Water Context:
 * Sparkling Water Version: 3.36.0.3-1-3.1
 * H2O name: 185
 * cluster size: 1
 * list of used nodes:
  (executorId, host, port)
  ------------------------
  (0,xx.yyy.www.aa,54321)
  ------------------------

  Open H2O Flow in browser: http://main-py-50429080e15e8842-driver-svc.default.svc:54321 (CMD + click in Mac OSX)

     
Connecting to H2O server at http://main-py-50429080e15e8842-driver-svc.default.svc:54321 ... successful.
--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         1 hour 10 mins
H2O_cluster_timezone:       Etc/GMT
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.0.3
H2O_cluster_version_age:    3 months and 3 days
H2O_cluster_name:           root
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    6.306 Gb
H2O_cluster_total_cores:    1
H2O_cluster_allowed_cores:  1
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://main-py-50429080e15e8842-driver-svc.default.svc:54321
H2O_connection_proxy:       null
H2O_internal_security:      False
Python_version:             3.9.2 final
--------------------------  ---------------------------------------------------------
```

And as a result of all this, I get this error on my spark pods:

```
2022-05-20 12:22:30,184 : CRITICAL : src.mlExecution.mlExecution : train : Error in mlExecution: An error occurred while calling o119.fit.
: ai.h2o.sparkling.backend.exceptions.RestApiNotReachableException: H2O node http://service-name.default.svc.cluster.local:54321 is not reachable.
Please verify that you are passing ip and port of existing cluster node and the cluster
is running with web enabled.
	at ai.h2o.sparkling.backend.utils.RestCommunication.throwRestApiNotReachableException(RestCommunication.scala:433)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:390)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent$(RestCommunication.scala:370)
	at ai.h2o.sparkling.backend.H2OJob$.readURLContent(H2OJob.scala:54)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request(RestCommunication.scala:182)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request$(RestCommunication.scala:172)
	at ai.h2o.sparkling.backend.H2OJob$.request(H2OJob.scala:54)
	at ai.h2o.sparkling.backend.utils.RestCommunication.query(RestCommunication.scala:67)
	at ai.h2o.sparkling.backend.utils.RestCommunication.query$(RestCommunication.scala:59)
	at ai.h2o.sparkling.backend.H2OJob$.query(H2OJob.scala:54)
	at ai.h2o.sparkling.backend.H2OJob$.ai$h2o$sparkling$backend$H2OJob$$verifyAndGetJob(H2OJob.scala:63)
	at ai.h2o.sparkling.backend.H2OJob.waitForFinishAndPrintProgress(H2OJob.scala:32)
	at ai.h2o.sparkling.ml.utils.EstimatorCommonUtils.trainAndGetDestinationKey(EstimatorCommonUtils.scala:44)
	at ai.h2o.sparkling.ml.utils.EstimatorCommonUtils.trainAndGetDestinationKey$(EstimatorCommonUtils.scala:30)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.trainAndGetDestinationKey(H2OAutoML.scala:42)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at ai.h2o.sparkling.backend.utils.RestCommunication.$anonfun$checkResponseCode$1(RestCommunication.scala:398)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at ai.h2o.sparkling.backend.utils.RestCommunication.retry(RestCommunication.scala:439)
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode(RestCommunication.scala:398)
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode$(RestCommunication.scala:394)
	at ai.h2o.sparkling.backend.H2OJob$.checkResponseCode(H2OJob.scala:54)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:386)
	... 25 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	... 36 more

2022-05-20 12:22:30,185 : INFO : __main__ : start : Output Info Schema
Traceback (most recent call last):
  File "/opt/spark/work-dir/main.py", line 132, in <module>
    start(proxy_json_object)
  File "/opt/spark/work-dir/main.py", line 101, in start
    my_logger.info(str(outputDf.printSchema()))
AttributeError: 'NoneType' object has no attribute 'printSchema'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/h2o/backend/connection.py", line 477, in request
    return self._process_response(resp, save_to)
  File "/usr/local/lib/python3.9/dist-packages/h2o/backend/connection.py", line 833, in _process_response
    raise H2OServerError("HTTP %d %s:\n%s" % (status_code, response.reason, data))
h2o.exceptions.H2OServerError: HTTP 502 Bad Gateway:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 502 Bad Gateway</title>
</head>
<body><h2>HTTP ERROR 502</h2>
<p>Problem accessing /4/sessions. Reason:
<pre>    Bad Gateway</pre></p>
</body>
</html>
```

Can someone help with how to resolve this issue? It's happening very frequently

**Comment by mn-mikke** [comment]
Hi @RajatSablok,
Can you share complete logs from both H2O nodes (pods)?

**Comment by krasinski** [comment]
@RajatSablok the most interesting logs would be those from the node that died :)
but btw. again I would suggest more cores in general

**Comment by RajatSablok** [comment]
OK @krasinski 

We are also facing another issue. Our H2O node never died or went unhealthy, but according to the following logs, spark could not communicate with the H2O cluster. Apparently, this issue was fixed in [this JIRA issue](https://h2oai.atlassian.net/browse/SW-1799) but we are still getting this error.

```
22/05/25 16:23:10 INFO TaskSchedulerImpl: Removed TaskSet 7.0, whose tasks have all completed, from pool 
22/05/25 16:23:10 INFO DAGScheduler: ResultStage 7 (runJob at Writer.scala:99) finished in 551.532 s
22/05/25 16:23:10 INFO DAGScheduler: Job 5 is finished. Cancelling potential speculative or zombie tasks for this job
22/05/25 16:23:10 INFO TaskSchedulerImpl: Killing all running tasks in stage 7: Stage finished
22/05/25 16:23:10 INFO DAGScheduler: Job 5 finished: runJob at Writer.scala:99, took 551.562250 s
22/05/25 16:27:44 INFO ContextHandler: Stopped a.h.o.e.j.s.ServletContextHandler@52346010{/,null,UNAVAILABLE}
22/05/25 16:27:44 INFO AbstractConnector: Stopped ServerConnector@3844adb6{HTTP/1.1,[http/1.1]}{0.0.0.0:54321}
Exception in thread "Thread-30" ai.h2o.sparkling.backend.exceptions.H2OClusterNotReachableException: H2O cluster h2o-service-dummy.sparkling-water-dummy.svc.cluster.local:54321 - root is not reachable,
H2OContext has been closed! Please create a new H2OContext to a healthy and reachable (web enabled)
H2O cluster.
	at ai.h2o.sparkling.H2OContext$$anon$2.run(H2OContext.scala:373)
Caused by: ai.h2o.sparkling.backend.exceptions.RestApiNotReachableException: H2O node http://h2o-service-dummy.sparkling-water-dummy.svc.cluster.local:54321/ is not reachable.
Please verify that you are passing ip and port of existing cluster node and the cluster
is running with web enabled.
	at ai.h2o.sparkling.backend.utils.RestCommunication.throwRestApiNotReachableException(RestCommunication.scala:433)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:390)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent$(RestCommunication.scala:370)
	at ai.h2o.sparkling.backend.utils.RestApiUtils$.readURLContent(RestApiUtils.scala:96)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request(RestCommunication.scala:182)
	at ai.h2o.sparkling.backend.utils.RestCommunication.request$(RestCommunication.scala:172)
	at ai.h2o.sparkling.backend.utils.RestApiUtils$.request(RestApiUtils.scala:96)
	at ai.h2o.sparkling.backend.utils.RestCommunication.query(RestCommunication.scala:67)
	at ai.h2o.sparkling.backend.utils.RestCommunication.query$(RestCommunication.scala:59)
	at ai.h2o.sparkling.backend.utils.RestApiUtils$.query(RestApiUtils.scala:96)
	at ai.h2o.sparkling.backend.utils.RestApiUtils.getPingInfo(RestApiUtils.scala:32)
	at ai.h2o.sparkling.backend.utils.RestApiUtils.getPingInfo$(RestApiUtils.scala:30)
	at ai.h2o.sparkling.backend.utils.RestApiUtils$.getPingInfo(RestApiUtils.scala:96)
	at ai.h2o.sparkling.H2OContext.ai$h2o$sparkling$H2OContext$$getSparklingWaterHeartbeatEvent(H2OContext.scala:335)
	at ai.h2o.sparkling.H2OContext$$anon$2.run(H2OContext.scala:347)
Caused by: java.net.UnknownHostException: h2o-service-dummy.sparkling-water-dummy.svc.cluster.local
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at ai.h2o.sparkling.backend.utils.RestCommunication.$anonfun$checkResponseCode$1(RestCommunication.scala:398)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at ai.h2o.sparkling.backend.utils.RestCommunication.retry(RestCommunication.scala:439)
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode(RestCommunication.scala:398)
	at ai.h2o.sparkling.backend.utils.RestCommunication.checkResponseCode$(RestCommunication.scala:394)
	at ai.h2o.sparkling.backend.utils.RestApiUtils$.checkResponseCode(RestApiUtils.scala:96)
	at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:386)
	... 13 more
Caused by: java.net.UnknownHostException: h2o-service-dummy.sparkling-water-dummy.svc.cluster.local
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	... 24 more
22/05/25 16:29:21 INFO H2OFrame: H2O node http://h2o-service-dummy.sparkling-water-dummy.svc.cluster.local:54321/3/FinalizeFrame successfully responded for the POST.
2022-05-25 16:29:21,043 : ERROR : src.mlExecution.mlExecution : train : An error occurred while calling o106.fit.
: java.lang.RuntimeException: H2OContext has to be running.
	at ai.h2o.sparkling.H2OContext$.$anonfun$ensure$1(H2OContext.scala:416)
	at scala.Option.getOrElse(Option.scala:189)
	at ai.h2o.sparkling.H2OContext$.ensure(H2OContext.scala:416)
	at ai.h2o.sparkling.H2OFrame$.apply(H2OFrame.scala:287)
	at ai.h2o.sparkling.backend.Writer$.convert(Writer.scala:104)
	at ai.h2o.sparkling.backend.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:60)
	at ai.h2o.sparkling.H2OContext.$anonfun$asH2OFrame$2(H2OContext.scala:167)
	at ai.h2o.sparkling.backend.utils.H2OContextExtensions.withConversionDebugPrints(H2OContextExtensions.scala:86)
	at ai.h2o.sparkling.backend.utils.H2OContextExtensions.withConversionDebugPrints$(H2OContextExtensions.scala:74)
	at ai.h2o.sparkling.H2OContext.withConversionDebugPrints(H2OContext.scala:65)
	at ai.h2o.sparkling.H2OContext.asH2OFrame(H2OContext.scala:167)
	at ai.h2o.sparkling.H2OContext.asH2OFrame(H2OContext.scala:162)
	at ai.h2o.sparkling.ml.algos.H2OAlgoCommonUtils.prepareDatasetForFitting(H2OAlgoCommonUtils.scala:88)
	at ai.h2o.sparkling.ml.algos.H2OAlgoCommonUtils.prepareDatasetForFitting$(H2OAlgoCommonUtils.scala:60)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.prepareDatasetForFitting(H2OAutoML.scala:42)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:85)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Unknown Source)

2022-05-25 16:29:21,043 : INFO : __main__ : start : AUTO ML STATUS:False
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7d48e87ee0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='main-py-5c0b6180fbf30bff-driver-svc.spark.svc', port=54321): Max retries exceeded with url: /4/sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d48e87ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

These are the versions that we're using:

```
Sparkling Water version: 3.36.0.3-1-3.1
Spark version: 3.1.2
Integrated H2O version: 3.36.0.3
```

**Comment by krasinski** [comment]
@RajatSablok do you have the logs from the node that died?

about the second issue you mentioned - that doesn't necessarily mean that's the same issue - how is your cluster health? aren't the nodes too busy because of lack of resources?

ideally to look into the issue we would need a description on how to reproduce it

**Comment by mn-mikke** [comment]
Hi @RajatSablok,
Can you share the events for the namespace where you created the H2O statefulset? This should tell us whether the h2o node died itself otherwise it was evicted by k8s.

```kubectl get events -n sparkling-water-dummy -o wide --sort-by=.metadata.creationTimestamp```
