### ISSUE TITLE
Sparkling water (Internal Backend mode) model training stuck at 100% with OOM Error

### ISSUE THREAD

**Issue by gurumoorthy208524** [h2oai/sparkling-water#2787]
In Sparkling water internal backend mode, model training got stuck at 100% for long time. Even for small dataset of around 100mb with 1 million records. When i checked the h2o logs, i can see the following logs
```
2022-05-30T11:16:51.791569112Z 05-30 11:16:51.627 10.171.128.84:54321   14     client-3-1  WARN org.apache.spark.rpc.netty.NettyRpcEnv: Ignored message: HeartbeatResponse(false)
2022-05-30T11:16:57.389791213Z 05-30 11:16:57.389 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:17:57.457602205Z 05-30 11:17:57.457 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:18:57.470322209Z 05-30 11:18:57.469 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.65 GB OOM!
2022-05-30T11:19:57.561733511Z 05-30 11:19:57.561 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:20:57.628072540Z 05-30 11:20:57.627 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.6 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:21:57.670927835Z 05-30 11:21:57.670 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=11.69 GB OOM!
2022-05-30T11:22:57.768870907Z 05-30 11:22:57.768 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.5 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=11.68 GB OOM!
2022-05-30T11:23:57.822428018Z 05-30 11:23:57.821 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:160.2 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:24:57.903366354Z 05-30 11:24:57.902 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.6 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=11.68 GB OOM!
2022-05-30T11:25:57.974622238Z 05-30 11:25:57.973 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.6 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=11.68 GB OOM!
2022-05-30T11:26:58.089590722Z 05-30 11:26:58.089 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.6 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
2022-05-30T11:27:30.276656597Z 05-30 11:27:30.275 10.171.128.84:54321   14     client-3-1  WARN org.apache.spark.rpc.netty.NettyRpcEnv: Ignored message: HeartbeatResponse(false)
2022-05-30T11:27:31.153629746Z 05-30 11:27:31.152 10.171.128.84:54321   14     eartbeater  WARN org.apache.spark.executor.Executor: Issue communicating with driver in heartbeater
2022-05-30T11:27:31.153717997Z org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10000 milliseconds]. This timeout is controlled by spark.executor.heartbeatInterval
2022-05-30T11:27:31.153726180Z 	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
2022-05-30T11:27:31.153733030Z 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
2022-05-30T11:27:31.153739120Z 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
2022-05-30T11:27:31.153744544Z 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
2022-05-30T11:27:31.153749376Z 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
2022-05-30T11:27:31.153754170Z 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
2022-05-30T11:27:31.153758640Z 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:996)
2022-05-30T11:27:31.153763100Z 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:212)
2022-05-30T11:27:31.153767724Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2022-05-30T11:27:31.153772240Z 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1996)
2022-05-30T11:27:31.153776700Z 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
2022-05-30T11:27:31.153781136Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2022-05-30T11:27:31.153785681Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
2022-05-30T11:27:31.153790339Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2022-05-30T11:27:31.153795260Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2022-05-30T11:27:31.153799797Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2022-05-30T11:27:31.153821732Z 	at java.base/java.lang.Thread.run(Unknown Source)
2022-05-30T11:27:31.153825938Z Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
2022-05-30T11:27:31.153830402Z 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
2022-05-30T11:27:31.153834613Z 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
2022-05-30T11:27:31.153838500Z 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
2022-05-30T11:27:31.153843534Z 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
2022-05-30T11:27:31.153847861Z 	... 12 more
2022-05-30T11:27:58.126288707Z 05-30 11:27:58.125 10.171.128.84:54321   14         FJ-2-1  WARN water.default: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:1.09 GB + POJO:159.6 MB + FREE:10.75 GB == MEM_MAX:12.00 GB), desiredKV=23.61 GB OOM!
```
Any help on this issue? Thanks

**Comment by krasinski** [comment]
@gurumoorthy208524 in internal mode memory is shared with Spark - that message we're seeing indicates that there was an out of memory error, not sure what is your setup when it comes to Spark and what exactly you're doing there but that might give you some direction

**Comment by gurumoorthy208524** [comment]
@krasinski the following is my spark config 
```
conf["spark.driver.cores"]=2
conf["spark.driver.memory"]="2g"
conf["spark.executor.cores"]=4  
conf["spark.executor.memory"]="12g"
conf["spark.executor.instances"]=1

**Comment by mn-mikke** [comment]
@gurumoorthy208524, it's difficult to help you if we don't have a full context. For internal backend, Please always send us the full logs from driver and executors, not only the snippets. The other parts of logs also contains statistics about the dataset in memory and the details about the model that you're trying to train.

**Comment by gurumoorthy208524** [comment]
@mn-mikke @krasinski Here are the logs of the spark driver & executor
[36.txt](https://github.com/h2oai/sparkling-water/files/8806497/36.txt)
[36-exec-1.txt](https://github.com/h2oai/sparkling-water/files/8806501/36-exec-1.txt)
