### ISSUE TITLE
NullPointerException when load big csv file from hdfs

### ISSUE THREAD

**Issue by JulianZhang** [h2oai/sparkling-water#36]
My sparking-water is 1.6.3, my spark is CDH 5.7 - spark 1.6
I have a big csv file with  1440790 rows, more than 400 column. 
I import it from hdfs, And during parseFiles I got a error as blow.

DistributedException from xxxx:54321, caused by java.lang.NullPointerException.

and the detail log from spark AM is blow

java.lang.NullPointerException
    at water.fvec.FileVec.chunkOffset(FileVec.java:84)
    at water.persist.PersistHdfs.load(PersistHdfs.java:151)
    at water.persist.PersistManager.load(PersistManager.java:143)
    at water.Value.loadPersist(Value.java:237)
    at water.Value.memOrLoad(Value.java:119)
    at water.Value.write_impl(Value.java:346)
    at water.Value$Icer.write67(Value$Icer.java)
    at water.Value$Icer.write(Value$Icer.java)
    at water.Iced.write(Iced.java:61)
    at water.AutoBuffer.put(AutoBuffer.java:730)
    at water.TaskPutKey$Icer.write66(TaskPutKey$Icer.java)
    at water.TaskPutKey$Icer.write(TaskPutKey$Icer.java)
    at water.H2O$H2OCountedCompleter.write(H2O.java:1220)
    at water.AutoBuffer.put(AutoBuffer.java:730)
    at water.RPC.call(RPC.java:201)
    at water.RPC.call(RPC.java:102)
    at water.TaskPutKey.put(TaskPutKey.java:15)
    at water.DKV.DputIfMatch(DKV.java:149)
    at water.DKV.DputIfMatch(DKV.java:94)
    at water.fvec.FileVec.chunkIdx(FileVec.java:108)
    at water.fvec.Vec.chunkForChunkIdx(Vec.java:891)
    at water.fvec.ByteVec.chunkForChunkIdx(ByteVec.java:20)
    at water.fvec.ByteVec.chunkForChunkIdx(ByteVec.java:16)
    at water.parser.FVecParseReader.getChunkData(FVecParseReader.java:25)
    at water.parser.CsvParser.parseChunk(CsvParser.java:427)
    at water.parser.ParseDataset$MultiFileParseTask$DistributedParse.map(ParseDataset.java:931)
    at water.MRTask.compute2(MRTask.java:619)
    at water.H2O$H2OCountedCompleter.compute1(H2O.java:1184)
    at water.parser.ParseDataset$MultiFileParseTask$DistributedParse$Icer.compute1(ParseDataset$MultiFileParseTask$DistributedParse$Icer.java)
    at water.H2O$H2OCountedCompleter.compute(H2O.java:1180)
    at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
    at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
    at jsr166y.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:914)
    at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:979)
    at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
    at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
java.lang.NullPointerException
    at water.fvec.FileVec.chunkOffset(FileVec.java:84)
    at water.persist.PersistHdfs.load(PersistHdfs.java:151)
    at water.persist.PersistManager.load(PersistManager.java:143)
    at water.Value.loadPersist(Value.java:237)
    at water.Value.memOrLoad(Value.java:119)
    at water.Value.write_impl(Value.java:346)
    at water.Value$Icer.write67(Value$Icer.java)
    at water.Value$Icer.write(Value$Icer.java)
    at water.Iced.write(Iced.java:61)
    at water.AutoBuffer.put(AutoBuffer.java:730)
    at water.TaskPutKey$Icer.write66(TaskPutKey$Icer.java)
    at water.TaskPutKey$Icer.write(TaskPutKey$Icer.java)
    at water.H2O$H2OCountedCompleter.write(H2O.java:1220)
    at water.AutoBuffer.put(AutoBuffer.java:730)
    at water.RPC.call(RPC.java:201)
    at water.RPC.call(RPC.java:102)
    at water.TaskPutKey.put(TaskPutKey.java:15)
    at water.DKV.DputIfMatch(DKV.java:149)
    at water.DKV.DputIfMatch(DKV.java:94)
    at water.fvec.FileVec.chunkIdx(FileVec.java:108)
    at water.fvec.Vec.chunkForChunkIdx(Vec.java:891)
    at water.fvec.ByteVec.chunkForChunkIdx(ByteVec.java:20)
    at water.fvec.ByteVec.chunkForChunkIdx(ByteVec.java:16)
    at water.parser.FVecParseReader.getChunkData(FVecParseReader.java:25)
    at water.parser.CsvParser.parseChunk(CsvParser.java:427)
    at water.parser.ParseDataset$MultiFileParseTask$DistributedParse.map(ParseDataset.java:931)
    at water.MRTask.compute2(MRTask.java:619)
    at water.MRTask.compute2(MRTask.java:577)
    at water.MRTask.compute2(MRTask.java:577)
    at water.MRTask.compute2(MRTask.java:577)
    at water.H2O$H2OCountedCompleter.compute1(H2O.java:1184)
    at water.parser.ParseDataset$MultiFileParseTask$DistributedParse$Icer.compute1(ParseDataset$MultiFileParseTask$DistributedParse$Icer.java)
    at water.H2O$H2OCountedCompleter.compute(H2O.java:1180)
    at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
    at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
    at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
    at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
    at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by jakubhava** [comment]
Hi JulianZhang,
 I'm really sorry for extremely late reply.

Thanks for reporting the issue. It should be fixed in the latest sparkling water versions for both spark 1.6 and 2.0

Kuba
