### ISSUE TITLE
Trouble getting latest Sparkling Water (2.2) to work with R (via rsparkling)

### ISSUE THREAD

**Issue by renegademonkey** [h2oai/sparkling-water#371]
I'm having issues updating rsparkling to work with Sparkling Water 2.2 and Spark 2.2. Everything worked with previous versions (<2.1).

I have installed the rsparkling version R package that comes with the latest Sparkling Water 2.2 binaries (as per https://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/0/index.html), and set the sparkling water version to the install location (i.e. `options(rsparkling.sparklingwater.location = "/Users/me/sparkling-water-2.2.0/")`).

I can now connect to my cluster, but get error

`java.lang.ClassNotFoundException: org.apache.spark.h2o.H2OContext`

I think this may have to do with the h2o version I am using - 3.14.0.2 which is the version recommended in the install page and in the change-log.

Is this the version of h2o sparkling water 2.2 works with? The rsparkling documentation ([https://github.com/h2oai/rsparkling](https://github.com/h2oai/rsparkling)) is not updated to 2.2. Could this error be the result of something else?

I am connecting to a standalone spark cluster, and my setup is:

```
Cluster/local Spark version: 2.2
R: 3.4.2
RStudio: 1.0.153
Sparklyr: 0.6.2
h2o: 3.14.0.2
rsparkling: 2.1
```

**Comment by mmalohlava** [comment]
@renegademonkey thx for report! Do you have any snippet from Spark logs - it seems like it could not find a binary jar providing all Sparkling Water classes.

**Comment by renegademonkey** [comment]
Hi @mmalohlava - thanks for the quick reply! The full Error log is:

`Error: java.lang.ClassNotFoundException: org.apache.spark.h2o.H2OContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:85)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)`

And in the Spark UI under spark jars, the following are loaded:

`file:/Users/rafaelw/sparkling-water-2.2.0/,file:/Users/rafaelw/.ivy2/jars/com.datastax.spark_spark-cassandra-connector_2.11-2.0.0-M1.jar,file:/Users/rafaelw/.ivy2/jars/com.databricks_spark-csv_2.11-1.3.0.jar,file:/Users/rafaelw/.ivy2/jars/com.datastax.cassandra_cassandra-driver-core-3.0.2.jar,file:/Users/rafaelw/.ivy2/jars/org.apache.cassandra_cassandra-clientutil-3.0.2.jar,file:/Users/rafaelw/.ivy2/jars/commons-beanutils_commons-beanutils-1.8.0.jar,file:/Users/rafaelw/.ivy2/jars/com.google.guava_guava-16.0.1.jar,file:/Users/rafaelw/.ivy2/jars/org.joda_joda-convert-1.2.jar,file:/Users/rafaelw/.ivy2/jars/joda-time_joda-time-2.3.jar,file:/Users/rafaelw/.ivy2/jars/com.twitter_jsr166e-1.1.0.jar,file:/Users/rafaelw/.ivy2/jars/org.scala-lang_scala-reflect-2.11.8.jar,file:/Users/rafaelw/.ivy2/jars/io.netty_netty-handler-4.0.33.Final.jar,file:/Users/rafaelw/.ivy2/jars/io.dropwizard.metrics_metrics-core-3.1.2.jar,file:/Users/rafaelw/.ivy2/jars/io.netty_netty-buffer-4.0.33.Final.jar,file:/Users/rafaelw/.ivy2/jars/io.netty_netty-transport-4.0.33.Final.jar,file:/Users/rafaelw/.ivy2/jars/io.netty_netty-codec-4.0.33.Final.jar,file:/Users/rafaelw/.ivy2/jars/io.netty_netty-common-4.0.33.Final.jar,file:/Users/rafaelw/.ivy2/jars/org.slf4j_slf4j-api-1.7.7.jar,file:/Users/rafaelw/.ivy2/jars/org.apache.commons_commons-csv-1.1.jar,file:/Users/rafaelw/.ivy2/jars/com.univocity_univocity-parsers-1.5.1.jar,file:/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sparklyr/java/sparklyr-2.2-2.11.jar`

**Comment by jakubhava** [comment]
Thanks for the report @renegademonkey! If you don't mind I will create a new issue in the RSparkling project as this is related there and will close this one. Please see this issue - https://github.com/h2oai/rsparkling/issues/52. We need to update RSparkling just a little to be compatible with 2.2.
