### ISSUE TITLE
converting spark df to an H2O frame causes '36', caused by java.lang.ArrayIndexOutOfBoundsException: 36 at water.Futures.blockForPending(Futures.java:88) at water.fvec.Frame.finalizePartialFrame(Frame.java:1006) 

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#472]
Latest Sparkling Water (2.2.2) 

Getting following exception when converting spark df to an H2O frame:

```

Py4JJavaError: An error occurred while calling o101.asH2OFrame. : 
	java.lang.RuntimeException: 
	DistributedException from pc1udatahad09.x.y/10.20.32.127:54329: '36', 
	caused by java.lang.ArrayIndexOutOfBoundsException: 36
		 at water.Futures.blockForPending(Futures.java:88)
		 at water.fvec.Frame.finalizePartialFrame(Frame.java:1006)
		 at water.fvec.FrameUtils$class.finalizePartialFrame(FrameUtils.scala:37)
		 at water.fvec.FrameUtils$.finalizePartialFrame(FrameUtils.scala:70)
		 at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.finalizeFrame(WriteConverterCtxUtils.scala:112)
		 at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.convert(WriteConverterCtxUtils.scala:96)
		 at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:82)
		 at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:194)
		 at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:195)
		 at org.apache.spark.h2o.JavaH2OContext.asH2OFrame(JavaH2OContext.java:100)
		 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		 at java.lang.reflect.Method.invoke(Method.java:498)
		 at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
		 at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
		 at py4j.Gateway.invoke(Gateway.java:280)
		 at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
		 at py4j.commands.CallCommand.execute(CallCommand.java:79)
		 at py4j.GatewayConnection.run(GatewayConnection.java:214)
		 at java.lang.Thread.run(Thread.java:748) Caused by: DistributedException from pc1udatahad09.x.y/10.20.32.127:54329: '36', caused by java.lang.ArrayIndexOutOfBoundsException: 36
		 at water.RPC.result(RPC.java:241)
		 at water.RPC.get(RPC.java:253)
		 at water.RPC.get(RPC.java:47)
		 at water.Futures.waitAndCheckForException(Futures.java:30)
		 at water.Futures.cleanCompleted(Futures.java:62)
		 at water.Futures.add(Futures.java:47)
		 at water.TaskPutKey.put(TaskPutKey.java:15)
		 at water.DKV.DputIfMatch(DKV.java:151)
		 at water.DKV.put(DKV.java:84)
		 at water.DKV.put(DKV.java:76)
		 at water.DKV.put(DKV.java:57)
		 at water.fvec.Frame.finalizePartialFrame(Frame.java:1004)
		 ... 19 more 
		 
		 Caused by: java.lang.ArrayIndexOutOfBoundsException: 36
		 at water.Value.initReplicaHome(Value.java:560)
		 at water.TaskPutKey.dinvoke(TaskPutKey.java:26)
		 at water.RPC$RPCCall.compute2(RPC.java:339)
		 at water.H2O$H2OCountedCompleter.compute(H2O.java:1263)
		 at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
		 at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
		 at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
		 at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
		 at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) (<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError(u'An error occurred while calling o101.asH2OFrame.\n', JavaObject id=o167), <traceback object
		 at 0x7f17ef2402d8>)


```

Any ideas how to fix or workaround this?

**Comment by Tagar** [comment]
![Screenshot](https://github.com/Tagar/dropbox/blob/master/h2oexception.png)

**Comment by jakubhava** [comment]
Hi @Tagar , 
 can you please describe your environment ? Are you using YARN ?

Can you also share full, minimal reproducible example and if possible, the data on which it happens ?

Thanks!

**Comment by Tagar** [comment]
Thank you for prompt response @jakubhava 

We use YARN / Hadoop 2.6 (CDH 5.12)

I will ask user if I can share data.

**Comment by Tagar** [comment]
I saw email from the user today that he could not longer reproduce it himself on the same data. So it might be an intermittent problem.. 
Will be back in the office mid-next week and will play with this more.
We have an okay to share the data - so will do that along with yarn logs as long as I can reproduce it myself first.

**Comment by jakubhava** [comment]
thanks for the update @Tagar 

Kuba

**Comment by jakubhava** [comment]
I will close this issue for now @Tagar . But please feel free to re-open in case you can reproduce the issue. 

Thanks a lot!

Kuba

**Comment by Tagar** [comment]
Thanks Kuba

We had other incidents of this problem- latest one today.
But it doesn't happen every time.
Will try to upgrade to latest SW 2.2.3 (up from 2.2.2) and see if it happens there.
