### ISSUE TITLE
Lack of `-driverif` in the automatic h2o cluster start using the external backend?

### ISSUE THREAD

**Issue by DigitalPig** [h2oai/sparkling-water#551]
Hi,

I am on AWS EMR and want to start h2o cluster using the external backend with automatic start. Here is the log I have:

```
import org.apache.spark.h2o._
conf: org.apache.spark.h2o.H2OConf =
Sparkling Water configuration:
  backend cluster mode : external
  cluster start mode   : auto
  cloudName            : Not set yet
  cloud representative : Not set, using cloud name only
  clientBasePort       : 54321
  h2oClientLog         : INFO
  nthreads             : -1
Determining driver host interface for mapper->driver callback...
    [Possible callback IP address: 10.6.40.139]
    [Possible callback IP address: 127.0.0.1]
Using mapper->driver callback IP address and port: 127.0.0.1:32945
(You can override these with -driverif and -driverport/-driverportrange.)
Memory Settings:
    mapreduce.map.java.opts:     -Xms2G -Xmx2G -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Dlog4j.defaultInitOverride=true
    Extra memory percent:        10
    mapreduce.map.memory.mb:     2252
18/01/27 05:04:40 INFO impl.TimelineClientImpl: Timeline service address: http://ip-6-40-139.xxx.com:8188/ws/v1/timeline/
18/01/27 05:04:40 INFO client.RMProxy: Connecting to ResourceManager at ip-6-40-139.xxx.com/10.6.40.139:8032
18/01/27 05:04:41 INFO mapreduce.JobSubmitter: number of splits:1
18/01/27 05:04:41 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1517026424512_0014
18/01/27 05:04:41 INFO mapred.H2OYARNRunner: Setting application type to H2O
18/01/27 05:04:42 INFO impl.YarnClientImpl: Submitted application application_1517026424512_0014
18/01/27 05:04:42 INFO mapreduce.Job: The url to track the job: http://ip-6-40-139.xxx.com:20888/proxy/application_1517026424512_0014/
Job name 'H2O_via_SparklingWater_application_1517026424512_0013' submitted
JobTracker job ID is 'job_1517026424512_0014'
For YARN users, logs command is 'yarn logs -applicationId application_1517026424512_0014'
Waiting for H2O cluster to come up...
18/01/27 05:06:00 INFO impl.TimelineClientImpl: Timeline service address: http://ip-6-40-139.xxx.com:8188/ws/v1/timeline/
18/01/27 05:06:00 INFO client.RMProxy: Connecting to ResourceManager at ip-6-40-139.xxx.com/10.6.40.139:8032
----- YARN cluster metrics -----
Number of YARN worker nodes: 2
----- Nodes -----
Node: http://ip-6-40-110.xxx.com:8042    Rack: /default-rack, RUNNING, 4 containers used, 15.4 / 56.0 GB used, 4 / 32 vcores used
Node: http://ip-6-40-46.xxx.com:8042     Rack: /default-rack, RUNNING, 3 containers used, 16.5 / 56.0 GB used, 3 / 32 vcores used
Node: http://ip-10-6-40-46.xxx.com:8042  Rack: /default-rack,    LOST, 0 containers used,  0.0 / 56.0 GB used, 0 / 32 vcores used
Node: http://ip-10-6-40-110.xxx.com:8042 Rack: /default-rack,    LOST, 0 containers used,  0.0 / 56.0 GB used, 0 / 32 vcores used
----- Queues -----
Queue name:            default
    Queue state:       RUNNING
    Current capacity:  0.28
    Capacity:          1.00
    Maximum capacity:  1.00
    Application count: 2
    ----- Applications in this queue -----
    Application ID:                  application_1517026424512_0013 (Zeppelin)
        Started:                     zeppelin (Sat Jan 27 05:04:18 UTC 2018)
        Tracking URL:                http://ip-6-40-139.xxx.com:20888/proxy/application_1517026424512_0013/
        Queue name:                  default
        Used/Reserved containers:    6 / 0
        Needed/Used/Reserved memory: 28.4 GB / 28.4 GB / 0.0 GB
        Needed/Used/Reserved vcores: 6 / 6 / 0
    Application ID:                  application_1517026424512_0014 (H2O_via_SparklingWater_application_1517026424512_0013)
        Started:                     zeppelin (Sat Jan 27 05:04:41 UTC 2018)
        Application state:           FINISHED
        Tracking URL:                http://ip-6-40-139.xxx.com:20888/proxy/application_1517026424512_0014/
        Queue name:                  default
        Used/Reserved containers:    1 / 0
        Needed/Used/Reserved memory: 3.5 GB / 3.5 GB / 0.0 GB
        Needed/Used/Reserved vcores: 1 / 1 / 0
Queue 'default' approximate utilization: 31.9 / 112.0 GB used, 7 / 64 vcores used
----------------------------------------------------------------------
ERROR: Unable to start any H2O nodes; please contact your YARN administrator.
       A common cause for this is the requested container size (2.2 GB)
       exceeds the following YARN settings:
           yarn.nodemanager.resource.memory-mb
           yarn.scheduler.maximum-allocation-mb
----------------------------------------------------------------------
For YARN users, logs command is 'yarn logs -applicationId application_1517026424512_0014'
java.lang.RuntimeException:
Cluster notification file /mnt/var/lib/zeppelin/notify_H2O_via_SparklingWater_application_1517026424512_0013 could not be created. The possible causes are:
1) External H2O cluster did not cloud within the pre-defined timeout. In that case, please try
   to increase the timeout for starting the external cluster as:
   Python: H2OConf(sc).set_cluster_start_timeout(timeout)....
   Scala:  new H2OConf(sc).setClusterStartTimeout(timeout)....
2) The file could not be created because of missing write rights.
  at org.apache.spark.h2o.backends.external.ExternalH2OBackend.launchH2OOnYarn(ExternalH2OBackend.scala:101)
  at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:131)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:125)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:360)
  ... 49 elided
```

I am under YARN environment. I can confirm that the issue is mainly because the driver network ip is picked incorrectly. I can start h2o hadoop job without any issue using `-driverif 10.6.40.139` however I did not find an option to set this during sparkling water conf. 

Do you happen to know how I can set this property? Thanks!

**Comment by jakubhava** [comment]
Hi @DigitalPig, thanks for the report! I already allowed to specify the desired configuration and the change is already in master and release branches. The Jira is available here - https://0xdata.atlassian.net/browse/SW-693. After the release, you can use the of the setters or `spark.ext.h2o.external.driver.if` directly.

Before the release, I know about one, but it's really really a hacky solution. We can specify the location of H2O extended jar via the `setH2ODriverPath` setter in Scala or `set_h2o_driver_path` in python correspondingly.  You could specify the path to external h2o jar there following by the driverif configuration since it will get expanded to the full command line which is used to start H2O on yarn.

So for example, what you could do is: `conf.setH2ODriverPath("/Users/foo/path/to/exteded.jar -J -driverif -J YOUR_IP")` the `-J` is important for the correct interpretation of the command on the driver side.

Hope that helps!

**Comment by DigitalPig** [comment]
Thanks for the quick response. I followed your instruction of adding those two `-J` options but had another errors:

```
ERROR: Unrecognized option -Dmapreduce.job.tags=H2O/Sparkling-Water,Sparkling-Water/Spark/application_1517293595483_0001
Usage: h2odriver
          [generic Hadoop ToolRunner options]
          [-h | -help]
          [-jobname <name of job in jobtracker (defaults to: 'H2O_nnnnn')>]
              (Note nnnnn is chosen randomly to produce a unique name)
          [-principal <kerberos principal> -keytab <keytab path> [-run_as_user <impersonated hadoop username>] | -run_as_user <hadoop username>]
          [-driverif <ip address of mapper->driver callback interface>]
          [-driverport <port of mapper->driver callback interface>]
          [-driverportrange <range portX-portY of mapper->driver callback interface>; eg: 50000-55000]
          [-network <IPv4network1Specification>[,<IPv4network2Specification> ...]
          [-timeout <seconds>]
          [-disown]
          [-notify <notification file name>]
          -mapperXmx <per mapper Java Xmx heap size>
          [-extramempercent <0 to 20>]
          -n | -nodes <number of H2O nodes (i.e. mappers) to create>
          [-nthreads <maximum typical worker threads, i.e. cpus to use>]
          [-context_path <context_path> the context path for jetty]
          [-baseport <starting HTTP port for H2O nodes; default is 54321>]
          [-flow_dir <server side directory or hdfs directory>]
           [-ea]
          [-verbose:gc]
          [-XX:+PrintGCDetails]
          [-license <license file name (local filesystem, not hdfs)>]
          -o | -output <hdfs output dir>
Notes:
          o  Each H2O node runs as a mapper.
          o  Only one mapper may be run per host.
          o  There are no combiners or reducers.
          o  Each H2O cluster should have a unique jobname.
          o  -mapperXmx, -nodes and -output are required.
          o  -mapperXmx is set to both Xms and Xmx of the mapper to reserve
             memory up front.
          o  -extramempercent is a percentage of mapperXmx.  (Default: 10)
             Extra memory for internal JVM use outside of Java heap.
                 mapreduce.map.memory.mb = mapperXmx * (1 + extramempercent/100)
          o  -libjars with an h2o.jar is required.
          o  -driverif and -driverport/-driverportrange let the user optionally
             specify the network interface and port/port range (on the driver host)
             for callback messages from the mapper to the driver.
          o  -network allows the user to specify a list of networks that the
             H2O nodes can bind to.  Use this if you have multiple network
             interfaces on the hosts in your Hadoop cluster and you want to
             force H2O to use a specific one.
             (Example network specification: '10.1.2.0/24' allows 256 legal
             possibilities.)
          o  -timeout specifies how many seconds to wait for the H2O cluster
             to come up before giving up.  (Default: 120 seconds
          o  -disown causes the driver to exit as soon as the cloud forms.
             Otherwise, Ctrl-C of the driver kills the Hadoop Job.
          o  -notify specifies a file to write when the cluster is up.
             The file contains one line with the IP and port of the embedded
             web server for one of the H2O nodes in the cluster.  e.g.
                 192.168.1.100:54321
          o  All mappers must start before the H2O cloud is considered up.
Examples:
          hadoop jar h2odriver.jar -nodes 1 -mapperXmx 6g -output hdfsOutputDir
          hadoop jar h2odriver.jar -nodes 1 -mapperXmx 6g -notify notify.txt -disown -output hdfsOutputDir
Exit value:
          0 means the cluster exited successfully with an orderly Shutdown.
              (From the Web UI or the REST API.)
          non-zero means the cluster exited with a failure.
              (Note that Ctrl-C is treated as a failure.)
java.lang.RuntimeException:
Cluster notification file /mnt/var/lib/zeppelin/notify_H2O_via_SparklingWater_application_1517293595483_0001 could not be created. The possible causes are:
1) External H2O cluster did not cloud within the pre-defined timeout. In that case, please try
   to increase the timeout for starting the external cluster as:
   Python: H2OConf(sc).set_cluster_start_timeout(timeout)....
   Scala:  new H2OConf(sc).setClusterStartTimeout(timeout)....
2) The file could not be created because of missing write rights.
  at org.apache.spark.h2o.backends.external.ExternalH2OBackend.launchH2OOnYarn(ExternalH2OBackend.scala:101)
  at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:131)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:125)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:360)

```

**Comment by jakubhava** [comment]
I see. Thanks for the hint. So right now I can suggest either wait for a new Sparkling Water release or build Sparkling Water from the master branch which already has this fix in.

In order to build Sparkling water for external backend you need to:

```
./gradlew build -x check # builds sparkling water
./gradlew -PdoExtend extendJar -PdownloadH2O=YOUR_HADOOP_DISTRO # generates extended H2O JAR
```

**Comment by DigitalPig** [comment]
Cool! Thanks for the reply. Does this new feature release in the nightly bleeding edge release yet for sparkling water? https://h2o-release.s3.amazonaws.com/sparkling-water/master/75/index.html

**Comment by jakubhava** [comment]
Yup, it's available there. I completely forgot about the nighly! Feel free to try it from the nightly package

**Comment by jakubhava** [comment]
Hi, @DigitalPig I will go ahead and close this issue since we have a bug fix. But please us know if the solution worked for you. Otherwise, we can reopen.

Thanks!

**Comment by DigitalPig** [comment]
I have tried to download the latest nightly build sparkling water: https://h2o-release.s3.amazonaws.com/sparkling-water/master/82_nightly/sparkling-water-2.2.82_nightly.zip

And I tried to start the external backend like:

```scala
import org.apache.spark.h2o._
val conf = new H2OConf(spark).setExternalClusterMode().useAutoClusterStart().setH2ODriverPath("/home/hadoop/h2odriver-sw2.2.7-hdp2.6-extended.jar").setNumOfExternalH2ONodes(1).setMapperXmx("2G").set("spark.ext.h2o.external.driver.if","10.6.40.219")
val hc = H2OContext.getOrCreate(spark, conf)
```

It still gets the node ip as 127.0.0.1..

```log
Determining driver host interface for mapper->driver callback...
    [Possible callback IP address: 10.6.40.219]
    [Possible callback IP address: 127.0.0.1]
Using mapper->driver callback IP address and port: 127.0.0.1:40893
```

Do I use the correct way of starting the backend?

**Comment by jakubhava** [comment]
@DigitalPig thanks for coming back. There was still a bug, I fixed that in this PR - https://github.com/h2oai/sparkling-water/pull/568

We will be doing new release next week, so you can either wait for that or use tomorrow's nightly. It should be finally resolved now, sorry for delays
