### ISSUE TITLE
Add support for Java 21

### ISSUE THREAD

**Issue by krasinski** [h2oai/sparkling-water#5680]

**Comment by venkim** [comment]
A cluster init from java does not work for any version higher than Java 8. With Java8 - i had to pass a VM argument --permit-illegal-access for the cluster to stay up.

**Comment by hutch3232** [comment]
Is there a plan to work on this? I saw there was another issue for other Java versions: https://github.com/h2oai/sparkling-water/issues/3005 and even a PR which was closed without merging that appeared to enable it: https://github.com/h2oai/sparkling-water/pull/5666

I am trying to use `h2o` and `pysparkling` in Microsoft's Azure/cloud environments with mixed results.

I can spin up a Spark cluster and attach to it with `pysparkling` in Microsoft Fabric and Microsoft ML Studio using Serverless Spark. However, using a Synapse Spark Pool in Azure Synapse Analytics does not work. It seems like new Java versions are preventing compatibility in this latter case.

Here is how I'm trying to connect:
```python
from pyspark.sql import SparkSession
from pysparkling import H2OContext

spark = SparkSession.builder.getOrCreate()
hc = H2OContext.getOrCreate()
```
Here is the traceback:
<details>

```python
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Cell In[5], line 5
      2 from pysparkling import H2OContext
      4 spark = SparkSession.builder.getOrCreate()
----> 5 hc = H2OContext.getOrCreate()

File ~/cluster-env/env/lib/python3.11/site-packages/ai/h2o/sparkling/H2OContext.py:90, in H2OContext.getOrCreate(conf)
     88 package = getattr(jvm.ai.h2o.sparkling, "H2OContext$")
     89 module = package.__getattr__("MODULE$")
---> 90 jhc = module.getOrCreate(selected_conf._jconf)
     91 h2o_context._jhc = jhc
     92 h2o_context._conf = selected_conf

File ~/cluster-env/env/lib/python3.11/site-packages/py4j/java_gateway.py:1322, in JavaMember.__call__(self, *args)
   1316 command = proto.CALL_COMMAND_NAME +\
   1317     self.command_header +\
   1318     args_command +\
   1319     proto.END_COMMAND_PART
   1321 answer = self.gateway_client.send_command(command)
-> 1322 return_value = get_return_value(
   1323     answer, self.gateway_client, self.target_id, [self.name](http://self.name/))
   1325 for temp_arg in temp_args:
   1326     if hasattr(temp_arg, "_detach"):

File /opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py:179, in capture_sql_exception.<locals>.deco(*a, **kw)
    177 def deco(*a: Any, **kw: Any) -> Any:
    178     try:
--> 179         return f(*a, **kw)
    180     except Py4JJavaError as e:
    181         converted = convert_exception(e.java_exception)

File ~/cluster-env/env/lib/python3.11/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o4251.getOrCreate.
: java.lang.IllegalAccessError: class ai.h2o.sparkling.backend.utils.RestCommunication (in unnamed module @0x1baab21c) cannot access class sun.net.www.protocol.http.Handler (in module java.base) because module java.base does not export sun.net.www.protocol.http to unnamed module @0x1baab21c
        at ai.h2o.sparkling.backend.utils.RestCommunication.resolveUrl(RestCommunication.scala:312)
        at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent(RestCommunication.scala:371)
        at ai.h2o.sparkling.backend.utils.RestCommunication.readURLContent$(RestCommunication.scala:360)
        at ai.h2o.sparkling.backend.utils.RestApiUtils$.readURLContent(RestApiUtils.scala:96)
        at ai.h2o.sparkling.backend.utils.RestCommunication.request(RestCommunication.scala:182)
        at ai.h2o.sparkling.backend.utils.RestCommunication.request$(RestCommunication.scala:172)
        at ai.h2o.sparkling.backend.utils.RestApiUtils$.request(RestApiUtils.scala:96)
        at ai.h2o.sparkling.backend.utils.RestCommunication.update(RestCommunication.scala:88)
        at ai.h2o.sparkling.backend.utils.RestCommunication.update$(RestCommunication.scala:81)
        at ai.h2o.sparkling.backend.utils.RestApiUtils$.update(RestApiUtils.scala:96)
        at ai.h2o.sparkling.backend.utils.H2OContextExtensions.lockCloud(H2OContextExtensions.scala:234)
        at ai.h2o.sparkling.backend.utils.H2OContextExtensions.tryToLockCloud(H2OContextExtensions.scala:121)
        at ai.h2o.sparkling.backend.utils.H2OContextExtensions.getAndVerifyWorkerNodes(H2OContextExtensions.scala:136)
        at ai.h2o.sparkling.backend.utils.H2OContextExtensions.getAndVerifyWorkerNodes$(H2OContextExtensions.scala:130)
        at ai.h2o.sparkling.H2OContext.getAndVerifyWorkerNodes(H2OContext.scala:64)
        at ai.h2o.sparkling.H2OContext.<init>(H2OContext.scala:84)
        at ai.h2o.sparkling.H2OContext$.getOrCreate(H2OContext.scala:447)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

</details>

CoPilot suggested I try the following extra configs, but that did not fix it.:
```python
from pyspark import SparkConf
from pyspark.sql import SparkSession
from pysparkling import H2OContext

conf = SparkConf()
conf.set("spark.driver.extraJavaOptions", "--add-exports java.base/sun.net.www.protocol.http=ALL-UNNAMED")
conf.set("spark.executor.extraJavaOptions", "--add-exports java.base/sun.net.www.protocol.http=ALL-UNNAMED")

spark = SparkSession.builder.config(conf=conf).getOrCreate()
hc = H2OContext.getOrCreate()
```

```
Runtime Information
Name    Value
Java Home       /usr/lib/jvm/msopenjdk-17
Java Version    17.0.15 (Microsoft)
Scala Version   version 2.12.18
```

Here are all the JavaOptions specified:

<details>

```python
spark.driver.extraJavaOptions   -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/[java.io](http://java.io/)=ALL-UNNAMED --add-opens=java.base/[java.net](http://java.net/)=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/[sun.nio.ch](http://sun.nio.ch/)=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dlog4j2.configurationFile=file:/usr/hdp/current/spark3-client/conf/driver-log4j2.properties -Detwlogger.component=sparkdriver -DlogFilter.filename=SparkLogFilters.xml -DpatternGroup.filename=SparkPatternGroups.xml -Dlog4jspark.root.logger=INFO,console,RFA,ETW,Anonymizer -Dlog4jspark.log.dir=/var/log/sparkapp/${[user.name](http://user.name/)} -Dlog4jspark.log.file=sparkdriver.log -Djavax.xml.parsers.SAXParserFactory=[com.sun.org](http://com.sun.org/).apache.xerces.internal.jaxp.SAXParserFactoryImpl -XX:+UseParallelGC -XX:+UseParallelOldGC -XX:+TieredCompilation -XX:Tier4CompileThreshold=150000 -XX:OnError="head -n $(grep -n 'siginfo' hs_err_pid%p.log | sed -n '2p' | cut -d: -f1) hs_err_pid%p.log 1>&2" -noverify

spark.executor.extraJavaOptions -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/[java.io](http://java.io/)=ALL-UNNAMED --add-opens=java.base/[java.net](http://java.net/)=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/[sun.nio.ch](http://sun.nio.ch/)=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dlog4j2.configurationFile=file:/usr/hdp/current/spark3-client/conf/executor-log4j2.properties -Djavax.xml.parsers.SAXParserFactory=[com.sun.org](http://com.sun.org/).apache.xerces.internal.jaxp.SAXParserFactoryImpl -Dio.netty.tryReflectionSetAccessible=true -XX:+UseG1GC -XX:OnError="head -n $(grep -n 'siginfo' hs_err_pid%p.log | sed -n '2p' | cut -d: -f1) hs_err_pid%p.log 1>&2"
```

</details>

Microsoft Fabric and ML Stuidio (which work) are using the older Java version of 11.0.27 (Microsoft).
