### ISSUE TITLE
Error when starting an `H2OContext`

### ISSUE THREAD

**Issue by clayms** [h2oai/sparkling-water#584]
When starting an `H2OContext` it seems that everything starts to work, then I get the following types of errors.
`ERROR:root:Exception while sending command.` 
`ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server`
`Py4JError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate`

The code and the complete output and errors are show below.
```
import pyspark
spark = pyspark.sql.SparkSession.builder.master('yarn').appName('H2O_test')\
.config("spark.jars.packages","ai.h2o:sparkling-water-core_2.11:2.2.8,ai.h2o:sparkling-water-core_2.11:2.2.8")\
.config("spark.dynamicAllocation.enabled", True)\
.getOrCreate()

from pysparkling import *
import h2o
hc = H2OContext.getOrCreate(spark)
```

Note: I replaced most of the IP addresses with `#####`
```
Sparkling Water version: 2.2.8
Spark version: 2.2.0.cloudera1
Integrated H2O version: 3.18.0.1
The following Spark configuration is used: 
    (spark.eventLog.enabled,true)
    (spark.yarn.appMasterEnv.PYSPARK_PYTHON,/opt/cloudera/parcels/Anaconda-4.2.0/bin/python)
    (spark.driver.appUIAddress,http://####)
    (spark.driver.bindAddress,100.66.0.12)
    (spark.scheduler.minRegisteredResourcesRatio,1)
    (spark.ui.killEnabled,true)
    (spark.dynamicAllocation.maxExecutors,56)
    (spark.ui.port,20049)
    (spark.dynamicAllocation.executorIdleTimeout,60)
    (spark.ext.h2o.client.log.dir,/home/cdsw/h2ologs/application_1517962050497_0259)
    (spark.dynamicAllocation.enabled,True)
    (spark.serializer,org.apache.spark.serializer.KryoSerializer)
    (spark.authenticate,false)
    (spark.sql.hive.metastore.jars,${env:HADOOP_COMMON_HOME}/../hive/lib/*:${env:HADOOP_COMMON_HOME}/client/*)
    (spark.executorEnv.PYTHONPATH,<CPS>/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p2832.251268/lib/spark2/python/lib/py4j-0.10.4-src.zip<CPS>/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p2832.251268/lib/spark2/python/lib/pyspark.zip)
    (spark.driver.port,31567)
    (spark.serializer.objectStreamReset,100)
    (spark.submit.deployMode,client)
    (spark.yarn.appMasterEnv.PYSPARK_DRIVER_PYTHON,/opt/cloudera/parcels/Anaconda-4.2.0/bin/python)
    (spark.default.parallelism,100)
    (spark.ext.h2o.client.ip,####)
    (spark.executor.extraLibraryPath,/opt/cloudera/parcels/CDH-5.13.1-1.cdh5.13.1.p0.2/lib/hadoop/lib/native)
    (spark.shuffle.service.enabled,true)
    (spark.eventLog.dir,hdfs://nameservice-ha/user/spark/spark2ApplicationHistory)
    (spark.executor.memory,4g)
    (spark.app.name,H2O_test)
    (spark.hadoop.hadoop.treat.subject.external,true)
    (spark.driver.memory,30976m)
    (spark.executor.id,driver)
    (spark.dynamicAllocation.schedulerBacklogTimeout,1)
    (spark.shuffle.service.port,7337)
    (spark.sql.hive.metastore.version,1.1.0)
    (spark.hadoop.yarn.application.classpath,)
    (spark.yarn.jars,local:/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p2832.251268/lib/spark2/jars/*)
    (spark.yarn.rmProxy.enabled,false)
    (spark.yarn.config.gatewayPath,/opt/cloudera/parcels)
    (spark.ext.h2o.cloud.name,sparkling-water-cdsw_application_1517962050497_0259)
    (spark.app.id,application_1517962050497_0259)
    (spark.master,yarn)
    (spark.yarn.historyServer.address,http://ip-######.com:##)
    (spark.sql.warehouse.dir,/user/hive/warehouse)
    (spark.sql.catalogImplementation,hive)
    (spark.locality.wait,30000)
    (spark.hadoop.mapreduce.application.classpath,)
    (spark.rdd.compress,True)
    (spark.kryoserializer.buffer.max,128m)
    (spark.ui.filters,org.apache.spark.deploy.yarn.YarnProxyRedirectFilter)
    (spark.dynamicAllocation.minExecutors,0)
    (spark.yarn.config.replacementPath,{{HADOOP_COMMON_HOME}}/../../..)
    (spark.yarn.isPython,true)
    (spark.driver.extraLibraryPath,/opt/cloudera/parcels/CDH-5.13.1-1.cdh5.13.1.p0.2/lib/hadoop/lib/native)
    (spark.driver.host,10.235.27.98)
    (spark.yarn.am.extraLibraryPath,/opt/cloudera/parcels/CDH-5.13.1-1.cdh5.13.1.p0.2/lib/hadoop/lib/native)
    (spark.driver.blockManager.port,25620)

Found XGBoost backend with library: xgboost4j_gpu
XGBoost supported backends: [WITH_GPU, WITH_OMP]
----- H2O started (client) -----
Build git branch: rel-wolpert
Build git hash: e28b85654e8808337e6ca2b30b17675dba9a947f
Build git describe: jenkins-master-4201-8-ge28b856
Build project version: 3.18.0.1 (latest version: 3.18.0.1)
Build age: 7 days, 7 hours and 26 minutes
Built by: 'jenkins'
Built on: '2018-02-13 04:36:03'
Watchdog Build git branch: (unknown)
Watchdog Build git hash: (unknown)
Watchdog Build git describe: (unknown)
Watchdog Build project version: (unknown)
Watchdog Built by: (unknown)
Watchdog Built on: (unknown)
XGBoost Build git branch: (unknown)
XGBoost Build git hash: (unknown)
XGBoost Build git describe: (unknown)
XGBoost Build project version: (unknown)
XGBoost Built by: (unknown)
XGBoost Built on: (unknown)
Processed H2O arguments: [-name, sparkling-water-cdsw_application_1517962050497_0259, -ga_opt_out, -quiet, -log_level, INFO, -log_dir, /home/cdsw/h2ologs/application_1517962050497_0259, -baseport, 54321, -client, -ip, #####, -flatfile, /tmp/1519149768072-0/flatfile.txt]
Java availableProcessors: 32
Java heap totalMemory: 3.00 GB
Java heap maxMemory: 26.89 GB
Java version: Java 1.8.0_121 (from Oracle Corporation)
JVM launch parameters: [-Xmx30976m]
OS version: Linux 3.10.0-514.el7.x86_64 (amd64)
Machine physical memory: 237.92 GB
X-h2o-cluster-id: 1519149756399
User name: 'cdsw'
Opted out of sending usage metrics.
IPv6 stack selected: false
Possible IP Address: eth0 (eth0), fe80:0:0:0:38b8:73ff:fea9:d1aa%eth0
Possible IP Address: eth0 (eth0), 100.66.0.12
Possible IP Address: lo (lo), 0:0:0:0:0:0:0:1%lo
Possible IP Address: lo (lo), 127.0.0.1
IP address not found on this machine
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
Py4JNetworkError: Error while receiving
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (#####)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (######)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (#####)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (####)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (#####)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
Py4JError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate
Py4JErrorTraceback (most recent call last)
in engine
----> 1 hc = H2OContext.getOrCreate(spark)

/home/cdsw/pysparkling/context.pyc in getOrCreate(spark, conf, verbose, **kwargs)
    132             selected_conf = H2OConf(spark_session)
    133         # Create backing Java H2OContext
--> 134         jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
    135         h2o_context._jhc = jhc
    136         h2o_context._conf = selected_conf

/usr/local/lib/python2.7/site-packages/py4j/java_gateway.pyc in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/lib/python2.7/site-packages/py4j/protocol.pyc in get_return_value(answer, gateway_client, target_id, name)
    325             raise Py4JError(
    326                 "An error occurred while calling {0}{1}{2}".
--> 327                 format(target_id, ".", name))
    328     else:
    329         type = answer[1]

Py4JError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate
```

**Comment by jakubhava** [comment]
Hi @clayms, can you please share what version of Sparkling Water are you using. What environment, how you are starting Sparking-Water, is it some regular standalone app, notebook or python shell?

Thanks, Kuba

**Comment by jakubhava** [comment]
Hi @clayms, without the further information, it will be hard to debug the issue, can you please have a look at and answer the questions above? the full logs would help as well

**Comment by jakubhava** [comment]
I would close this one for now. @clayms please make sure to start PySparkling as described in the documentation or here http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/10/index.html. Thanks!
