### ISSUE TITLE
Unable to set network CIDER in external auto mode

### ISSUE THREAD

**Issue by JeroenSchmidt** [h2oai/sparkling-water#590]
Cluster Specs:
* Hadoop 2.6.3
* Spark 2.2.1
* Sparkling Water 2.2.1 

Hi there,

The networking for my hadoop implementation is on the complex side so If i want to succesfully deploy an external backend manually I need to specify the -network flag otherwise nothing works. 
```
! hadoop jar /cluster/libs-java-old/h2odriver-sw2.2.7-hdp2.2-extended.jar\
-disown\
-nodes 5\
-timeout 10000\
-mapperXmx 6g\
-output /h2o_logs/jeroens/testing_backend\
-network 192.168.0.71/24\
-driverif 192.168.0.19\
-driverport 54321\
-baseport 54322\
-nthreads 5\
-notify /cluster/data/logs/yarn_logs/h2o_logs/testing_back_end_notify
```

Once I have the external manual backend running I can successfully connect to it within pyspark. 

However I am unable to succesfully start external auto mode using the following command:

```
h20_config = H2OConf(spark)\
.set_external_cluster_mode()\
.use_auto_cluster_start()\
.set_h2o_driver_path("/cluster/libs-java-old/h2odriver-sw2.2.7-hdp2.2-extended.jar")\
.set_cluster_config_file("/cluster/data/logs/yarn_logs/h2o_logs/testing_back_end_notify")\
.set_num_of_external_h2o_nodes(3)\
.set_mapper_xmx("2G")\
.set_client_ip("192.168.0.19")\
.set_cloud_timeout(10000)\
.set("spark.ext.h2o.external.network","192.168.0.71/24")
```
From what I can see, there is no `set_network_sider` procedure so I use `.set("spark.ext.h2o.external.network","192.168.0.71/24")` hopping that would work; but it doesnt.

I get a stack error as follows:
```
Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.RuntimeException: 
Cluster notification file /cluster/data/logs/yarn_logs/h2o_logs/testing_back_end_notify could not be created. The possible causes are:

1) External H2O cluster did not cloud within the pre-defined timeout. In that case, please try
   to increase the timeout for starting the external cluster as:
   Python: H2OConf(sc).set_cluster_start_timeout(timeout)....
   Scala:  new H2OConf(sc).setClusterStartTimeout(timeout)....

2) The file could not be created because of missing write rights.
    at org.apache.spark.h2o.backends.external.ExternalH2OBackend.launchH2OOnYarn(ExternalH2OBackend.scala:101)
    at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:131)
    at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:125)
    at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:358)
    at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
    at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:280)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Unknown Source)
```

I would like to know if there is a procedure to set the CIDER for the workers or if you can implement something that does the equivalent as the CLI `-network` flag.

**Comment by jakubhava** [comment]
Hi @JeroenSchmidt, `spark.ext.h2o.external.network` does not exist.

It is currently not possible to specify network mask for the external backend, but this feature is already in master and will be available in the release which is planned for today.

After then, you can set the configuration in the same way as the others as:
`.set_node_network_mask(")\
`

**Comment by jakubhava** [comment]
I will close this issue for now. Please feel free to re-open it in case you are still having troubles in the new release

**Comment by JeroenSchmidt** [comment]
Thanks :)

**Comment by JeroenSchmidt** [comment]
Hi @jakubhava. I upgraded our SW libraries and jars today.
When I run the above code now with `.set_node_network_mask("192.168.0.71/24")` I get the following error:

```
Py4JJavaErrorTraceback (most recent call last)
<ipython-input-11-d94356354878> in <module>()
----> 1 hc = H2OContext.getOrCreate(spark,h20_config)

/conda/envs/py35_dev/lib/python3.5/site-packages/pysparkling/context.py in getOrCreate(spark, conf, verbose, **kwargs)
    132             selected_conf = H2OConf(spark_session)
    133         # Create backing Java H2OContext
--> 134         jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
    135         h2o_context._jhc = jhc
    136         h2o_context._conf = selected_conf

/usr/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/usr/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.io.IOException: Cannot run program "-network": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(Unknown Source)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$anonfun$runBuffered$1.apply(ProcessBuilderImpl.scala:148)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$anonfun$runBuffered$1.apply(ProcessBuilderImpl.scala:148)
	at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:99)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:148)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:114)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.launchH2OOnYarn(ExternalH2OBackend.scala:97)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:142)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:129)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:381)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 25 more
```

Do you have any recommendations?

Is YARN trying to read from HDFS when it runs the external jar?

In manual external mode we are running the external jar from our local file system on our master node.

**Comment by jakubhava** [comment]
@JeroenSchmidt thanks for pointing that out. I didn't test this option out properly and it's actually a simple bug. It will be fixed in the next release and also in the regular nighly release tomorrow

**Comment by JeroenSchmidt** [comment]
Great thanks a lot.
