### ISSUE TITLE
Getting Error While establishing H2O cluster 

### ISSUE THREAD

**Issue by alzuabi** [h2oai/sparkling-water#675]
I have been trying to run Spark 2.2.0 with Sparkling water 2.2.5, in HDP 2.6.4 but getting following exception when I run below code :

`import org.apache.spark.h2o._
val conf = new H2OConf(spark).setExternalClusterMode().useAutoClusterStart().setH2ODriverPath("/home/bduser/sparkling-water-2.2.5/h2odriver-sw2.2.5-hdp2.6-extended.jar").setNumOfExternalH2ONodes(3).setCloudName("test").setMapperXmx("2G")
val hc = H2OContext.getOrCreate(spark, conf)`

import org.apache.spark.h2o._
conf: org.apache.spark.h2o.H2OConf =
Sparkling Water configuration:
  backend cluster mode : external
  cluster start mode   : auto
  cloudName            : test
  cloud representative : Not set, using cloud name only
  clientBasePort       : 54321
  h2oClientLog         : INFO
  nthreads             : -1
Determining driver host interface for mapper->driver callback...
    [Possible callback IP address: 10.2.123.224]
    [Possible callback IP address: 127.0.0.1]
Using mapper->driver callback IP address and port: 10.2.123.224:33219
(You can override these with -driverif and -driverport/-driverportrange.)
Memory Settings:
    mapreduce.map.java.opts:     -Xms2G -Xmx2G -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Dlog4j.defaultInitOverride=true
    Extra memory percent:        10
    mapreduce.map.memory.mb:     2252
18/04/17 17:01:21 INFO client.RMProxy: Connecting to ResourceManager at hdp2node4.server.syriatel/10.2.123.227:8050
18/04/17 17:01:22 INFO client.AHSProxy: Connecting to Application History server at hdp2node3.server.syriatel/10.2.123.226:10200
18/04/17 17:01:27 INFO mapreduce.JobSubmitter: number of splits:3
18/04/17 17:01:28 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1523857615912_0092
18/04/17 17:01:28 INFO mapred.H2OYARNRunner: Setting application type to H2O
18/04/17 17:01:28 INFO impl.YarnClientImpl: Submitted application application_1523857615912_0092
Job name 'test' submitted
JobTracker job ID is 'job_1523857615912_0092'
For YARN users, logs command is 'yarn logs -applicationId application_1523857615912_0092'
Waiting for H2O cluster to come up...
18/04/17 17:01:28 INFO mapreduce.Job: The url to track the job: http://hdp2node4.server.syriatel:8088/proxy/application_1523857615912_0092/
H2O node 10.2.123.227:54321 requested flatfile
H2O node 10.2.123.226:54321 requested flatfile
H2O node 10.2.123.224:54321 requested flatfile
Sending flatfiles to nodes...
    [Sending flatfile to node 10.2.123.227:54321]
    [Sending flatfile to node 10.2.123.226:54321]
    [Sending flatfile to node 10.2.123.224:54321]
H2O node 10.2.123.227:54321 reports H2O cluster size 1
H2O node 10.2.123.226:54321 reports H2O cluster size 1
H2O node 10.2.123.224:54321 reports H2O cluster size 1
H2O node 10.2.123.227:54321 reports H2O cluster size 3
H2O node 10.2.123.226:54321 reports H2O cluster size 3
H2O node 10.2.123.224:54321 reports H2O cluster size 3
Cluster notification file (notify_test) created.
H2O cluster (3 nodes) is up
Open H2O Flow in your web browser: http://10.2.123.224:54321
Disowning cluster and exiting.
For YARN users, logs command is 'yarn logs -applicationId application_1523857615912_0092'
18/04/17 17:02:30 WARN util.ShutdownHookManager: ShutdownHook '' timeout, java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:67)
18/04/17 17:02:40 WARN util.ShutdownHookManager: ShutdownHook 'ClientFinalizer' timeout, java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:67)
java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.getUserJars(Lorg/apache/spark/SparkConf;Z)Lscala/collection/Seq;
  at org.apache.spark.repl.h2o.H2OInterpreter.createSettings(H2OInterpreter.scala:66)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.initializeInterpreter(BaseH2OInterpreter.scala:101)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.<init>(BaseH2OInterpreter.scala:291)
  at org.apache.spark.repl.h2o.H2OInterpreter.<init>(H2OInterpreter.scala:42)
  at water.api.scalaInt.ScalaCodeHandler.createInterpreterInPool(ScalaCodeHandler.scala:100)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:94)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:93)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at water.api.scalaInt.ScalaCodeHandler.initializeInterpreterPool(ScalaCodeHandler.scala:93)
  at water.api.scalaInt.ScalaCodeHandler.<init>(ScalaCodeHandler.scala:37)
  at water.api.scalaInt.ScalaCodeHandler$.registerEndpoints(ScalaCodeHandler.scala:132)
  at water.api.CoreRestAPI$.registerEndpoints(CoreRestAPI.scala:32)
  at water.api.RestAPIManager.register(RestAPIManager.scala:39)
  at water.api.RestAPIManager.registerAll(RestAPIManager.scala:31)
  at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:148)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:121)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:355)
  ... 52 elided

**Comment by jakubhava** [comment]
Please add this call to your H2OConf `setReplDisabled()` and let me know if that helped

**Comment by alzuabi** [comment]
Many thanks @jakubhava,  it works.
