### ISSUE TITLE
Java Memory Errors in Spark Submit

### ISSUE THREAD

**Issue by NkululekoThangelane** [h2oai/sparkling-water#725]
Hi Get the a simliar error for Java Heap Memory when using trying to score new data . New data has less than 1000 records however Sparkling water keeps running in to this GC Memory Error. I have increase executor memory to 60GB for 5 executors but I did not think that this model would need this much memory to score such a smore data set.
conf.set('spark.driver.memory','50G')
conf.set("spark.driver.cores","10")
conf.set("spark.executor.instances", "5")
conf.set("spark.yarn.queue",QUEUE)
conf.set("spark.executor.cores", "10")
conf.set("spark.executor.memory", '60G')
conf.set("spark.dynamicAllocation.enabled" , "false")
conf.set("spark.sql.autoBroadcastJoinThreshold","-1")
conf.set("spark.scheduler.minRegisteredResourcesRatio","1")
conf.set("spark.locality.wait","0")
conf.set("spark.sql.crossJoin.enabled", "true")
conf.set("spark.yarn.executor.memoryOverhead","60G")
conf.set("spark.driver.maxResultSize","50G")

java.lang.OutOfMemoryError: Java heap space
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethod(Class.java:2128)
at java.io.ObjectStreamClass.getInheritableMethod(ObjectStreamClass.java:1442)
at java.io.ObjectStreamClass.access$2200(ObjectStreamClass.java:72)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:508)
at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
at java.security.AccessController.doPrivileged(Native Method)
at java.io.ObjectStreamClass.(ObjectStreamClass.java:472)
at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:108)
at org.apache.spark.rpc.netty.NettyRpcEnv$$anonfun$deserialize$1$$anonfun$apply$1.apply(NettyRpcEnv.scala:259)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
at org.apache.spark.rpc.netty.NettyRpcEnv.deserialize(NettyRpcEnv.scala:308)
at org.apache.spark.rpc.netty.NettyRpcEnv$$anonfun$deserialize$1.apply(NettyRpcEnv.scala:258)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
at org.apache.spark.rpc.netty.NettyRpcEnv.deserialize(NettyRpcEnv.scala:257)

**Comment by jakubhava** [comment]
@NkululekoThangelane Are you using Spark submit or interactive shell? Are you running on YARN?

On YARN, you need to provide the memory configuration in your shell as part of the command line used to start your Spark App.

Such as ./bin/sparkling-shell --conf "spark.driver.memory=50G" --conf "spark.executor.memory=50G" as specifying the memory options later has no effect when you are running on YARN.

Also unless you have some specific requirements, we suggest configuring the driver and executors with the same amount of memory.

**Comment by NkululekoThangelane** [comment]
@jakubhava  Thanks for the getting back to me.
I will test  this and definitely get back to you.

**Comment by jakubhava** [comment]
Hi @NkululekoThangelane, any update?

**Comment by NkululekoThangelane** [comment]
Thanks @jakubhava  I think we found a solution by being able to parse greater memory configs to spark.
