### ISSUE TITLE
'Detected number of Spark workers is 1' error when creating H2O Context

### ISSUE THREAD

**Issue by simonvdk** [h2oai/sparkling-water#797]
I work on Google Cloud Dataproc (Spark 2.2.1, Python 3.4.2) and want to create a H2O cluster using pysparkling but can not create one with more than 1 worker. Here is the process I used:

After installing `h2o-pysparkling-2.2==2.2.19` using pip, I launched a shell with the following configurations:
```
pyspark --master yarn --deploy-mode client \
--conf spark.dynamicAllocation.enabled=false \
--conf spark.sql.autoBroadcastJoinThreshold=-1 \
--conf spark.ext.h2o.dummy.rdd.mul.factor=0 \
--conf spark.locality.wait=30000 \
--conf spark.executor.instances=4 \
--conf spark.executor.memory='2g' \
--conf spark.driver.memory='2g'
```

Then I ran in the shell:
```
from pysparkling import *
import h2o
hc = H2OContext.getOrCreate(spark)
```

This works fine when I create a H2O cluster with 1 worker (`conf spark.executor.instances=1`), but it does not work when I want to create one with more workers. Here is the error I step upon:
```
Traceback (most recent call last):
  File "XXX/python3.4/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "XXX/python3.4/site-packages/pyspark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.lang.IllegalArgumentException: Cannot execute H2O on all Spark executors:
 Expected number of H2O workers is Some(4)
 Detected number of Spark workers is 1
 Num of Spark executors before is 4
 Num of Spark executors after is 4

	at org.apache.spark.h2o.backends.internal.SpreadRDDBuilder.build(SpreadRDDBuilder.scala:72)
	at org.apache.spark.h2o.backends.internal.SpreadRDDBuilder.build(SpreadRDDBuilder.scala:43)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:69)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:127)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:379)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXX/python3.4/site-packages/pysparkling/context.py", line 151, in getOrCreate
    jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
  File "XXX/python3.4/site-packages/pyspark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "XXX/python3.4/site-packages/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: 'Cannot execute H2O on all Spark executors:\n Expected number of H2O workers is Some(4)\n Detected number of Spark workers is 1\n Num of Spark executors before is 4\n Num of Spark executors after is 4\n'
```

I spent quite a lot of time on it but could not find any help on the Internet. The same problem occurs with Spark 2.3.0 and `h2o-pysparkling-2.3==2.3.8`.

Thank you !

**Comment by simonvdk** [comment]
I managed to start a cluster (on both Spark 2.2 and 2.3) by changing the value of the option `spark.ext.h2o.dummy.rdd.mul.factor` to 1.
The default option (10) didn't work for me (it took ages, blocked at 1/3 of the creation and finally crashed) which is why I put it to 0. I guess I'll put it to 1 now.
What is the purpose of this option ? The documentation given (`Multiplication factor for dummy RDD generation. Size of dummy RDD is spark.ext.h2o.cluster.size * spark.ext.h2o.dummy.rdd.mul.factor .`) does not make sense to me; what is 'dummy RDD generation' ?

**Comment by jakubhava** [comment]
Hi @simonvdk.

I would suggest not changing the `spark.ext.h2o.dummy.rdd.mul.factor` unless you are really sure about what you are doing. It is required for several technical reasons. 

You are using internal sparkling water backend in which we need to discover all Spark executors at the beginning. We achieve this by creating artificial task which tries to utilize all Spark executors.

I would suggest disabling dynamic allocation and yarn preemption to make the environment more stable. If you would like to use dynamic allocation and yarn preemption on the Spark side, then I suggest having a look on the External Sparkling Water backend.

**Comment by simonvdk** [comment]
Thank you for your answer, it works fine for now with the dynamic allocation disabled and `spark.ext.h2o.dummy.rdd.mul.factor` set to 1 (the default value of 10 does not work for me), I will keep this in mind if I have further errors related to this !

**Comment by jakubhava** [comment]
Perfect, thank you!
