### ISSUE TITLE
Cloudera/Data Science Workbench session initialization problem

### ISSUE THREAD

**Issue by urbaman** [h2oai/sparkling-water#850]
Hi,

we're trying to use h2oai inside our environment (Cloudera 5x, Workbench 1.3.0, Spark 2.3) but it fails during initialization, with the attached log (full with commands and resulting error): 
[errors_sparklyr_h2o.txt](https://github.com/h2oai/sparkling-water/files/2209437/errors_sparklyr_h2o.txt)

Ultimately, without h2o we can open Spark or R sessions without any problems, but with h2o  we can't connect:

> Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: biz.k11i#xgboost-predictor;0.3.0: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1283)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:50)
	at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:363)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:249)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:170)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (54132): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/SPARK2-2.3.0.cloudera2-1.cdh5.13.3.p0.316101/lib/spark2/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.3.8','ai.h2o:sparkling-water-ml_2.11:2.3.8','ai.h2o:sparkling-water-repl_2.11:2.3.8','no.priv.garshol.duke:duke:1.2', '/home/cdsw/R/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 54132
    Log: /tmp/RtmpjsDpxa/fileef69cfd95b_spark.log

Only thing we can find is that xgboost-predictor's repos are under "http://dl.bintray.com/komiya-atsushi/maven/" instead of "http://dl.bintray.com/spark-packages/maven/", and it's the only dependency not found.
We don't even know if that's the real problem with the connection error.

Thank you.

**Comment by jakubhava** [comment]
Thank you for the report! Currently, H2O requires dependency `biz.k11i:xgboost-predictor:0.3.0` from this repository http://dl.bintray.com/komiya-atsushi/maven. With regular `spark-submit` or `spark-shell` it is possible to specify the list of additional repositories from which we should load artifacts as `--repositories http://dl.bintray.com/komiya-atsushi/maven`. However SparklyR does not have API for that.

What you can do to solve this error is to run `spark-shell --repositories http://dl.bintray.com/komiya-atsushi/maven --packages biz.k11i:xgboost-predictor:0.3.0` which will download the required dependency to the local cache. After that you can close the shell and start RSparkling.

Please let me know if that helped! Thanks, Kuba

**Comment by jakubhava** [comment]
Hi @urbaman , I'm closing this issue for now as we have an answer. Please feel free to comment or recreate this issue if you need more help

**Comment by urbaman** [comment]
Hi @jakubhava 

We finally succeeded installing everything from Workbench Data Science, but now we have another problem, always while connecting:

```
h2o_sc <- spark_connect(
  master = "yarn-client",
  #master = "local",
  app_name = "h2o_on_spark")
```

We're getting:

```
Error in force(code) : 
  Failed during initialize_connection: java.io.FileNotFoundException: File file:/home/cdsw/.ivy2/jars/net.sourceforge.f2j_arpack_combined_all-0.1.jar does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:598)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:811)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:588)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:432)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:340)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:292)
	at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:396)
	at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:488)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10$$anonfun$apply$7.apply(Client.scala:610)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10$$anonfun$apply$7.apply(Client.scala:609)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:609)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:608)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:608)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:876)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:173)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:57)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:164)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:500)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2486)
	at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

    Log: /tmp/RtmpvCh6vz/fileee49c338e0_spark.log


---- Output Log ----
18/08/02 12:17:43 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/com.github.rwl_jtransforms-2.4.0.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/com.github.rwl_jtransforms-2.4.0.jar
18/08/02 12:17:43 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/ai.h2o_h2o-jaas-pam-3.20.0.2.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/ai.h2o_h2o-jaas-pam-3.20.0.2.jar
18/08/02 12:17:44 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/log4j_log4j-1.2.17.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/log4j_log4j-1.2.17.jar
18/08/02 12:17:44 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/com.google.guava_guava-16.0.1.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/com.google.guava_guava-16.0.1.jar
18/08/02 12:17:44 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/commons-lang_commons-lang-2.6.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/commons-lang_commons-lang-2.6.jar
18/08/02 12:17:44 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty.orbit_javax.transaction-1.1.1.v201105210645.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty.orbit_javax.transaction-1.1.1.v201105210645.jar
18/08/02 12:17:45 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-webapp-8.1.17.v20150415.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty_jetty-webapp-8.1.17.v20150415.jar
18/08/02 12:17:45 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-jndi-8.1.17.v20150415.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty_jetty-jndi-8.1.17.v20150415.jar
18/08/02 12:17:45 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-xml-8.1.17.v20150415.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty_jetty-xml-8.1.17.v20150415.jar
18/08/02 12:17:46 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-servlet-8.1.17.v20150415.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty_jetty-servlet-8.1.17.v20150415.jar
18/08/02 12:17:46 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-util-8.1.17.v20150415.jar -> hdfs://nameservice1/user/aardenio/.sparkStaging/application_1528446310048_0221/org.eclipse.jetty_jetty-util-8.1.17.v20150415.jar
18/08/02 12:17:46 INFO yarn.Client: Uploading resource file:/home/cdsw/.ivy2/jars/org.eclipse.jetty_jetty-security-8.1.17.v20150415.jar
```

If we look inside /home/cdsw/.ivy2/jars/ we find a different file: net.sourceforge.f2j_arpack_combined_all-0.1-javadoc.jar instead of the one hi's searching for.

Do you know of any related issues or how to solve/wolkaround it?

Thank you very much,
Nicola.

**Comment by jakubhava** [comment]
Hi @urbaman, can you try cleaning your local ivy cache?

**Comment by urbaman** [comment]
Hi @jakubhava thank you very much, we cleared ivy2 cache and that problem also disappeared, now we're stuck with:

```
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (14497): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/SPARK2-2.3.0.cloudera2-1.cdh5.13.3.p0.316101/lib/spark2/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.3.8','ai.h2o:sparkling-water-ml_2.11:2.3.8','ai.h2o:sparkling-water-repl_2.11:2.3.8','no.priv.garshol.duke:duke:1.2', '/home/cdsw/R/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 14497
    Log: /tmp/RtmpynOBwi/filef05f4b527b_spark.log


---- Output Log ----
	found commons-io#commons-io;2.4 in central
	found org.eclipse.jetty.aggregate#jetty-servlet;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-plus;8.1.17.v20150415 in central
	found org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 in central
	found org.eclipse.jetty#jetty-webapp;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-xml;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-util;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-servlet;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-security;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-server;8.1.17.v20150415 in central
	found org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 in central
	found org.eclipse.jetty#jetty-continuation;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-http;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-io;8.1.17.v20150415 in central
	found org.eclipse.jetty#jetty-jndi;8.1.17.v20150415 in central
	found org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v201005082020 in central
	found org.eclipse.jetty.orbit#javax.activation;1.1.0.v201105071233 in central
	found com.github.rwl#jtransforms;2.4.0 in central
	found ai.h2o#h2o-jaas-pam;3.20.0.2 in central
	found org.kohsuke#libpam4j;1.8 in central
	found net.java.dev.jna#jna;4.0.0 in central
	found log4j#log4j;1.2.17 in central
	found com.google.guava#guava;16.0.1 in central
	found commons-lang#commons-lang;2.6 in central
	found no.priv.garshol.duke#duke;1.2 in central
	found org.apache.lucene#lucene-core;4.0.0 in central
	found org.apache.lucene#lucene-analyzers-common;4.0.0 in central
	found org.apache.lucene#lucene-spatial;4.0.0 in central
	found com.spatial4j#spatial4j;0.3 in central
	found org.apache.lucene#lucene-queries;4.0.0 in central
	found org.mapdb#mapdb;0.9.9 in central
	found ai.h2o#h2o-algos;3.20.0.2 in central
	found com.github.fommil.netlib#core;1.1.2 in central
	found net.sourceforge.f2j#arpack_combined_all;0.1 in central
	found com.github.fommil.netlib#netlib-native_ref-osx-x86_64;1.1 in central
	found com.github.fommil.netlib#native_ref-java;1.1 in central
	found com.github.fommil#jniloader;1.1 in central
	found com.github.fommil.netlib#netlib-native_ref-linux-x86_64;1.1 in central
	found com.github.fommil.netlib#netlib-native_ref-linux-i686;1.1 in central
	found com.github.fommil.netlib#netlib-native_ref-win-x86_64;1.1 in central
	found com.github.fommil.netlib#netlib-native_ref-win-i686;1.1 in central
	found com.github.fommil.netlib#netlib-native_ref-linux-armhf;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-osx-x86_64;1.1 in central
	found com.github.fommil.netlib#native_system-java;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-linux-x86_64;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-linux-i686;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-linux-armhf;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-win-x86_64;1.1 in central
	found com.github.fommil.netlib#netlib-native_system-win-i686;1.1 in central
	found com.googlecode.matrix-toolkits-java#mtj;1.0.4 in central
	found ai.h2o#h2o-web;3.20.0.2 in central
	found ai.h2o#h2o-avro-parser;3.20.0.2 in central
	found ai.h2o#h2o-ext-xgboost;3.20.0.2 in central
	found ai.h2o#h2o-genmodel-ext-xgboost;3.20.0.2 in central
	found ai.h2o#xgboost4j;0.7.8 in central
	found commons-logging#commons-logging;1.2 in central
	found ai.h2o#xgboost4j-linux-gpuv4;0.7.8 in central
	found ai.h2o#xgboost4j-linux-minimal;0.7.8 in central
	found ai.h2o#xgboost4j-osx-minimal;0.7.8 in central
	found ai.h2o#xgboost4j-linux-ompv3;0.7.8 in central
	found ai.h2o#h2o-parquet-parser;3.20.0.2 in central
	found ai.h2o#h2o-orc-parser;3.20.0.2 in central
	found ai.h2o#h2o-scala_2.11;3.20.0.2 in central
	found ai.h2o#h2o-persist-hdfs;3.20.0.2 in central
	found net.java.dev.jets3t#jets3t;0.9.0 in central
	found commons-codec#commons-codec;1.4 in central
	found org.apache.httpcomponents#httpclient;4.1.2 in central
	found org.apache.httpcomponents#httpcore;4.1.2 in central
	found com.jamesmurty.utils#java-xmlbuilder;0.4 in central
	found org.apache.hadoop#hadoop-hdfs;2.7.3 in central
	found org.mortbay.jetty#jetty;6.1.26 in central
	found org.mortbay.jetty#jetty-util;6.1.26 in central
	found com.sun.jersey#jersey-core;1.9 in central
	found com.sun.jersey#jersey-server;1.9 in central
	found asm#asm;3.2 in central
	found commons-cli#commons-cli;1.2 in central
	found commons-daemon#commons-daemon;1.0.13 in central
	found com.google.protobuf#protobuf-java;2.5.0 in central
	found javax.servlet#servlet-api;2.5 in central
	found org.codehaus.jackson#jackson-core-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-mapper-asl;1.9.13 in central
	found xmlenc#xmlenc;0.52 in central
	found io.netty#netty;3.6.2.Final in central
	found io.netty#netty-all;4.0.23.Final in central
	found xerces#xercesImpl;2.9.1 in central
	found xml-apis#xml-apis;1.3.04 in central
	found org.apache.htrace#htrace-core;3.1.0-incubating in central
	found org.fusesource.leveldbjni#leveldbjni-all;1.8 in central
	found org.apache.hadoop#hadoop-aws;2.7.3 in central
	found org.apache.hadoop#hadoop-common;2.7.3 in central
	found org.apache.hadoop#hadoop-annotations;2.7.3 in central
	found commons-httpclient#commons-httpclient;3.1 in central
	found commons-net#commons-net;3.1 in central
	found commons-collections#commons-collections;3.2.2 in central
	found com.sun.jersey#jersey-json;1.9 in central
	found org.codehaus.jettison#jettison;1.1 in central
	found com.sun.xml.bind#jaxb-impl;2.2.3-1 in central
	found javax.xml.bind#jaxb-api;2.2.2 in central
	found javax.xml.stream#stax-api;1.0-2 in central
	found javax.activation#activation;1.1 in central
```

So we're back with inability to connect while having no  hints at any  specific problem (we still can connect if we don't use rsparkling/h2o).

**Comment by jakubhava** [comment]
Does your node on which you are starting the session has access to the internet? Also could you please share the full code?

One thing you could try is starting RSparkling as: 

options(rsparkling.sparklingwater.location = "/path/to/sparkling_water.jar")
options(rsparkling.sparklingwater.version = "2.3.8")
library(rsparkling)

where you can download this Sparkling Water from https://s3.amazonaws.com/h2o-release/sparkling-water/rel-2.3/8/index.html. This configuration tells RSparklin to use this file instead of fetching the files from the maven repository
