### ISSUE TITLE
Sparkling Water on Zeppelin - RuntimeException

### ISSUE THREAD

**Issue by hakangurel** [h2oai/sparkling-water#919]
Hi,

Trying to follow the [documentation](https://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.3/10/doc/tutorials/use_on_zeppelin.html)

`export SPARK_HOME=...# Spark 2.3 home
export SPARK_SUBMIT_OPTIONS="--packages ai.h2o:sparkling-water-package_2.11:2.3.10"
bin/zeppelin.sh -Pspark-2.3`

generates the following error:

`Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: ai.h2o#mojo2-runtime-api;0.12.1: not found, download failed: commons-logging#commons-logging;1.2!commons-logging.jar]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1303)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:53)
	at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:364)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

Working on zeppelin-0.8.0-bin-all and spark-2.3.1

Thanks,

**Comment by jakubhava** [comment]
Hello, this is a known issue, sorry for delays, please see https://github.com/h2oai/sparkling-water/issues/705
