### ISSUE TITLE
RSparkling unresolved dependencies ai.h2o#mojo2-runtime-api;0.13.2: not found

### ISSUE THREAD

**Issue by ndegara** [h2oai/sparkling-water#959]
Could anyone help with this please? I'm trying to install rsparkling as described in:
https://github.com/h2oai/sparkling-water/tree/master/r

However I get the following error:

::          UNRESOLVED DEPENDENCIES         ::

:: ai.h2o#mojo2-runtime-api;0.13.2: not found

This is the information about the system and versions:
- rsparkling_0.2.10
- observed in yarn-client and also local
- h2o, spark and sparkling water versions according to rsparkling::h2o_release_table()
Spark_Version: 2.3.1
Sparkling_Water_Version: 2.3.15
H2O_Version: 3.20.0.9

This is the sessionInfo():
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsparkling_0.2.10 sparklyr_0.9.1   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19     dbplyr_1.2.2     compiler_3.4.1   pillar_1.3.0     later_0.7.5      bindr_0.1.1     
 [7] bitops_1.0-6     r2d3_0.2.2       base64enc_0.1-3  tools_3.4.1      digest_0.6.17    jsonlite_1.5    
[13] tibble_1.4.2     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.2  rlang_0.2.2      shiny_1.1.0     
[19] DBI_1.0.0        rstudioapi_0.7   parallel_3.4.1   yaml_2.2.0       bindrcpp_0.2.2   withr_2.1.2     
[25] dplyr_0.7.6      httr_1.3.1       rappdirs_0.3.1   htmlwidgets_1.3  rprojroot_1.3-2  grid_3.4.1      
[31] tidyselect_0.2.4 glue_1.3.0       forge_0.1.0      R6_2.2.2         h2o_3.20.0.9     purrr_0.2.5     
[37] tidyr_0.8.1      magrittr_1.5     backports_1.1.2  promises_1.0.1   htmltools_0.3.6  assertthat_0.2.0
[43] mime_0.5         xtable_1.8-3     httpuv_1.4.5     config_0.3       openssl_1.0.2    RCurl_1.95-4.11 
[49] lazyeval_0.2.1   broom_0.5.0      crayon_1.3.4    
```

This is a log of the error I get according to the following code:
```
> library(sparklyr)
> options(rsparkling.sparklingwater.version = "2.3.15")
> library(rsparkling)
> sc <- spark_connect(master = "yarn-client", spark_home = '/usr/lib/spark')


.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:53)
	at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:364)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
> sc <- spark_connect(master = "yarn-client", spark_home = '/usr/lib/spark')
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (79922): Gateway in localhost:8880 did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.3.15','ai.h2o:sparkling-water-ml_2.11:2.3.15','ai.h2o:sparkling-water-repl_2.11:2.3.15','no.priv.garshol.duke:duke:1.2', '/home/ndegara/R/x86_64-redhat-linux-gnu-library/3.4/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 79922
    Log: /tmp/Rtmp512jiH/file15bd72d2fd738_spark.log


---- Output Log ----
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from central in [default]
	org.eclipse.jetty#jetty-continuation;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-http;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-io;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-jndi;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-plus;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-security;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-server;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-servlet;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-util;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-webapp;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-xml;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty.aggregate#jetty-servlet;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty.orbit#javax.activation;1.1.0.v201105071233 from central in [default]
	org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v201005082020 from central in [default]
	org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 from central in [default]
	org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 from central in [default]
	org.fusesource.leveldbjni#leveldbjni-all;1.8 from central in [default]
	org.javassist#javassist;3.18.2-GA from central in [default]
	org.joda#joda-convert;1.7 from central in [default]
	org.kohsuke#libpam4j;1.8 from central in [default]
	org.mapdb#mapdb;0.9.9 from central in [default]
	org.mortbay.jetty#jetty;6.1.26 from central in [default]
	org.mortbay.jetty#jetty-util;6.1.26 from central in [default]
	xerces#xercesImpl;2.9.1 from central in [default]
	xml-apis#xml-apis;1.3.04 from central in [default]
	xmlenc#xmlenc;0.52 from central in [default]
	:: evicted modules:
	com.github.fommil.netlib#core;1.1 by [com.github.fommil.netlib#core;1.1.2] in [default]
	commons-codec#commons-codec;1.4 by [commons-codec#commons-codec;1.6] in [default]
	commons-logging#commons-logging;1.1.1 by [commons-logging#commons-logging;1.2] in [default]
	org.apache.httpcomponents#httpclient;4.1.2 by [org.apache.httpcomponents#httpclient;4.3.6] in [default]
	org.apache.httpcomponents#httpcore;4.1.2 by [org.apache.httpcomponents#httpcore;4.3.3] in [default]
	com.google.guava#guava;11.0.2 by [com.google.guava#guava;16.0.1] in [default]
	commons-logging#commons-logging;1.1.3 by [commons-logging#commons-logging;1.2] in [default]
	joda-time#joda-time;2.8.1 by [joda-time#joda-time;2.9.9] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |  113  |   0   |   0   |   8   ||  104  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: ai.h2o#mojo2-runtime-api;0.13.2

	==== local-m2-cache: tried

	  file:/home/ndegara/.m2/repository/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  file:/home/ndegara/.m2/repository/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

	==== local-ivy-cache: tried

	  /home/ndegara/.ivy2/local/ai.h2o/mojo2-runtime-api/0.13.2/ivys/ivy.xml

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  /home/ndegara/.ivy2/local/ai.h2o/mojo2-runtime-api/0.13.2/jars/mojo2-runtime-api.jar

	==== central: tried

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: ai.h2o#mojo2-runtime-api;0.13.2: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: ai.h2o#mojo2-runtime-api;0.13.2: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1303)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:53)
	at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:364)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

**Comment by jakubhava** [comment]
Duplicate for https://github.com/h2oai/sparkling-water/issues/705

**Comment by ndegara** [comment]
Yes, #705 is a related issue but I thought this was specific for rsparkling.
