### ISSUE TITLE
SW 2.3.16 release broken when connecting to h2o backend cluster? java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#976]
Just upgraded to SW to 2.3.16 and couldn't connect to backend h2o external cluster anymore.

```
Traceback (most recent call last)
<ipython-input-6-c37d158031d0> in <module>()
     15             ## .set("spark.ext.h2o.cloud.representative", "10.210.44.109:33105")
     16         )
---> 17 hc = H2OContext.getOrCreate(spark, conf)

/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/pysparkling/context.pyc in getOrCreate(spark, conf, verbose, pre_create_hook, h2o_connect_hook, **kwargs)
    159 
    160         # Create backing Java H2OContext
--> 161         jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
    162         h2o_context._jhc = jhc
    163         h2o_context._conf = selected_conf

/opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-1.cdh5.13.3.p0.458809/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-1.cdh5.13.3.p0.458809/lib/spark2/python/lib/pyspark.zip/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-1.cdh5.13.3.p0.458809/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.apache.spark.h2o.backends.SharedBackendUtils$$anonfun$getH2OClientArgsLocalNode$4.apply(SharedBackendUtils.scala:148)
	at org.apache.spark.h2o.backends.SharedBackendUtils$$anonfun$getH2OClientArgsLocalNode$4.apply(SharedBackendUtils.scala:148)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.h2o.backends.SharedBackendUtils$class.getH2OClientArgsLocalNode(SharedBackendUtils.scala:148)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.getH2OClientArgsLocalNode(ExternalH2OBackend.scala:38)
	at org.apache.spark.h2o.backends.SharedBackendUtils$class.getH2OClientArgs(SharedBackendUtils.scala:156)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.org$apache$spark$h2o$backends$external$ExternalBackendUtils$$super$getH2OClientArgs(ExternalH2OBackend.scala:38)
	at org.apache.spark.h2o.backends.external.ExternalBackendUtils$class.getH2OClientArgs(ExternalBackendUtils.scala:37)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.getH2OClientArgs(ExternalH2OBackend.scala:38)
	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:195)
	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:130)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:401)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.zeppelin.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at org.apache.zeppelin.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at org.apache.zeppelin.py4j.Gateway.invoke(Gateway.java:290)
	at org.apache.zeppelin.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at org.apache.zeppelin.py4j.commands.CallCommand.execute(CallCommand.java:79)
	at org.apache.zeppelin.py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Tagar** [comment]
Was connecting as 

```python
from pysparkling import *
conf = (H2OConf(spark)
            .set_external_cluster_mode()
            .use_manual_cluster_start()
            .set_h2o_cluster("10.210.44.111", 55099)
            .set_cloud_name("H2O external cluster for somebody")
            .set_external_write_confirmation_timeout(360)
            ## .set_client_port_base(44708)
            ## .set_node_base_port(44708)
            ## .set("spark.ext.h2o.cloud.representative", "10.210.44.109:33105") 
        )
hc = H2OContext.getOrCreate(spark, conf)
```

**Comment by jakubhava** [comment]
Please share H2O/SW Java logs with us as well, thank you @Tagar

**Comment by Tagar** [comment]
We just downgraded . Can you please try to reproduce connecting to backend cluster on this version ?

```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
```

It seems some variable wasn't initialized **None.get** ?

**Comment by Tagar** [comment]
Downgrade fixed the issue (we were on 2.3.**13** before), so I'm not sure if it's 2.3.16 or 15 or 14 that's broken for us.

**Comment by Tagar** [comment]
This is the line where the exception happens

https://github.com/h2oai/sparkling-water/blob/52b2f38de4b1182230215093cac6cd4b2cd6c5b9/core/src/main/scala/org/apache/spark/h2o/backends/SharedBackendUtils.scala#L148

**Comment by Tagar** [comment]
I think I found the root cause in 

https://github.com/h2oai/sparkling-water/blob/52b2f38de4b1182230215093cac6cd4b2cd6c5b9/core/src/main/scala/water/init/NetworkUtils.scala#L31

it assumes h2o server is on the same subnet as client. Why? This will not always be the case, and 
actually not the case for us!

**Comment by jakubhava** [comment]
@Tagar You can still set the client IP explicitly

**Comment by jakubhava** [comment]
https://github.com/h2oai/sparkling-water/pull/977 @Tagar this PR ensures we fallback to original IP discovery in case SW can't find the correct network. 

This means that it should unblock you in your use-case. Please feel free to test our nightly http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.3/nightly/index.html

**Comment by jakubhava** [comment]
Please check the next nightly tomorrow, thx

**Comment by Tagar** [comment]
Thank you @jakubhava
